/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotStatusCell.h"


__attribute__((visibility("hidden")))
@interface _PTHTweetbotRetweetStatusCell : PTHTweetbotStatusCell {
}
+(float)cellHeightWithItem:(id)item forTableView:(id)tableView;
-(void)updateStatus;
@end

