/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface _PTHSteppedSlider : XXUnknownSuperclass {
}
-(void)setValue:(float)value animated:(BOOL)animated;
-(void)setBounds:(CGRect)bounds;
-(void)colorThemeDidChange;
-(void)setEnabled:(BOOL)enabled;
-(void)updateTrackImage;
-(id)initWithFrame:(CGRect)frame;
@end

