/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface _PTHUIControlCategoryBlockTarget : XXUnknownSuperclass {
	id _block;
}
@property(copy, nonatomic) id block;
-(void).cxx_destruct;
-(void)_sendControl:(id)control event:(id)event;
@end

