/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSString;
@protocol NSObject, NSCoding;

@interface PTHKeychainItem : XXUnknownSuperclass {
	NSString* _serviceName;
	NSString* _accountName;
}
@property(readonly, assign, nonatomic) BOOL exists;
@property(copy, nonatomic) id<NSObject, NSCoding> passwordValue;
@property(copy, nonatomic) NSString* password;
@property(copy, nonatomic) NSData* passwordData;
@property(copy, nonatomic) NSString* accountName;
@property(copy, nonatomic) NSString* serviceName;
+(void)deleteItemsWithAccountName:(id)accountName;
+(void)deleteItemsWithServiceName:(id)serviceName;
+(id)itemWithServiceName:(id)serviceName accountName:(id)name;
+(id)itemsWithServiceName:(id)serviceName;
+(id)itemsWithAccountName:(id)accountName;
+(id)items;
-(void).cxx_destruct;
-(id)description;
-(void)setAttribute:(id)attribute forKey:(id)key;
-(id)attributeForKey:(id)key;
-(id)attributes;
-(void)delete;
-(id)itemAttributes;
-(id)initWithServiceName:(id)serviceName accountName:(id)name;
@end

