/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHPageViewDelegate.h"
#import "PTHPageViewDataSource.h"
#import "PTHViewController.h"

@class UILabel, PTHPageView, NSMutableArray, NSArray;

@interface PTHNoticeViewController : PTHViewController <PTHPageViewDataSource, PTHPageViewDelegate> {
	NSArray* _notices;
	NSMutableArray* _noticeViews;
	UILabel* _postedDateLabel;
	PTHPageView* _pageView;
}
-(void).cxx_destruct;
-(void)dealloc;
-(void)ok:(id)ok;
-(void)pageViewDidChangePage:(id)pageView;
-(void)pageViewDidScroll:(id)pageView;
-(id)pageView:(id)view pageAtIndex:(int)index;
-(unsigned)numberOfPagesInPageView:(id)pageView;
-(void)_updatePostedDateLabel;
-(void)openActionURL:(id)url;
-(void)loadView;
-(id)newViewForNotice:(id)notice;
-(id)initWithNotices:(id)notices;
@end

