/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHStreamHandlerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSNetServiceDelegate.h"

@class NSNetService, NSFileHandle, NSString, NSDictionary, NSMutableArray;
@protocol PTHNetServiceServerDelegate;

@interface PTHNetServiceServer : XXUnknownSuperclass <PTHStreamHandlerDelegate, NSNetServiceDelegate> {
	NSString* _type;
	NSString* _name;
	BOOL _running;
	NSNetService* _netService;
	NSFileHandle* _serverSocket;
	NSMutableArray* _clientStreamHandlers;
	unsigned _outputFormat;
	NSDictionary* _serviceDictionary;
	id<PTHNetServiceServerDelegate> _delegate;
	BOOL _backgroundEnabled;
}
@property(assign, nonatomic) unsigned outputFormat;
@property(assign, nonatomic, getter=isBackgroundEnabled) BOOL backgroundEnabled;
@property(copy, nonatomic) NSDictionary* serviceDictionary;
@property(readonly, assign, nonatomic) BOOL hasClients;
@property(assign, nonatomic) __weak id<PTHNetServiceServerDelegate> delegate;
-(void).cxx_destruct;
-(void)dealloc;
-(void)stop;
-(void)streamHandlerDidClose:(id)streamHandler;
-(void)streamHandler:(id)handler didOutputObject:(id)object;
-(void)streamHandler:(id)handler didReceiveObject:(id)object;
-(BOOL)outputObject:(id)object;
-(void)connectionReceived:(id)received;
-(void)unpublish;
-(void)republish;
-(BOOL)start;
-(id)initWithType:(id)type name:(id)name;
@end

