/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, PTHPageView, NSMutableArray;

@interface PTHPageViewControl : XXUnknownSuperclass {
	NSMutableArray* _dotViews;
	int _currentPage;
	unsigned _pageCount;
	UIImage* _pageDotImage;
	UIImage* _pageDotSelectedImage;
	unsigned _dotSpacing;
	BOOL _hidesForSinglePage;
	PTHPageView* _pageView;
}
@property(assign, nonatomic) unsigned pageCount;
@property(assign, nonatomic) int currentPage;
@property(assign, nonatomic) BOOL hidesForSinglePage;
@property(assign, nonatomic) unsigned dotSpacing;
@property(retain, nonatomic) UIImage* pageDotSelectedImage;
@property(retain, nonatomic) UIImage* pageDotImage;
@property(assign, nonatomic) __weak PTHPageView* pageView;
-(void).cxx_destruct;
-(CGSize)intrinsicContentSize;
-(void)layoutSubviews;
-(void)switchPageIfNeeded:(id)needed event:(id)event;
-(void)update;
-(void)awakeFromNib;
-(id)initWithFrame:(CGRect)frame;
-(void)setup;
@end

