/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIFont, UIPickerView, NSMutableDictionary;

@interface PTHPickerSelectionView : XXUnknownSuperclass {
	NSMutableDictionary* _labelDictionary;
	UIPickerView* _pickerView;
}
@property(readonly, assign, nonatomic) UIFont* font;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(void)attachToPickerView:(id)pickerView;
-(void)removeLabelForComponent:(int)component;
-(void)addLabel:(id)label forComponent:(int)component;
-(id)labelForComponent:(int)component;
-(void)reloadAllComponents;
-(id)initWithFrame:(CGRect)frame;
@end

