/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImage, UIColor;

@interface PTHProgressView : XXUnknownSuperclass {
	UIImage* _maskImage;
	BOOL _isIndeterminate;
	BOOL _isSpinning;
	float _progress;
	float _spinnerWidth;
	UIColor* _spinnerBackgroundColor;
	UIColor* _fromColor;
	UIColor* _toColor;
	float _spinnerIndeterminateDuration;
	NSString* _colorGroupName;
}
@property(copy, nonatomic) NSString* colorGroupName;
@property(assign, nonatomic) float spinnerIndeterminateDuration;
@property(retain, nonatomic) UIColor* toColor;
@property(retain, nonatomic) UIColor* fromColor;
@property(retain, nonatomic) UIColor* spinnerBackgroundColor;
@property(assign, nonatomic) float spinnerWidth;
@property(assign, nonatomic) float progress;
-(void).cxx_destruct;
-(void)dealloc;
-(CGSize)intrinsicContentSize;
-(void)drawRect:(CGRect)rect;
-(void)setBounds:(CGRect)bounds;
-(void)_updateState;
-(void)didMoveToWindow;
-(void)_stopSpinning;
-(void)_startSpinning;
-(void)colorThemeDidChange;
-(id)initWithFrame:(CGRect)frame;
@end

