/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHViewController.h"

@class ACAccountStore, NSArray;

@interface PTHSettingsTapbotsAboutController : PTHViewController {
	ACAccountStore* _acAccountStore;
	NSArray* _acAccounts;
}
+(void)requestACAccounts:(id)accounts;
-(void).cxx_destruct;
-(void)dealloc;
-(unsigned)supportedInterfaceOrientations;
-(void)showPrivacy:(id)privacy;
-(void)openReviewPage:(id)page;
-(void)openGiftPage:(id)page;
-(void)follow:(id)follow credit:(id)credit;
-(void)loadView;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

