/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface PTHTapbotsInfoFAQ : XXUnknownSuperclass {
	NSString* _question;
	NSString* _answer;
}
@property(readonly, assign, nonatomic) NSString* answer;
@property(readonly, assign, nonatomic) NSString* question;
-(void).cxx_destruct;
-(void)loadImage:(id)image;
-(id)initWithDictionary:(id)dictionary;
@end

