/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotStatusCursor.h"


@interface PTHTweetbotStatusConversationCursor : PTHTweetbotStatusCursor {
}
+(Class)itemClass;
-(void)loadNewer:(id)newer;
-(void)_loadReplyStatus:(id)status completionBlock:(id)block;
@end

