/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "PTHViewController.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class PTHTweetbotTableViewStatusView, PTHTweetbotRefreshView, NSMutableArray, UITableView, PTHTweetbotAccount;

__attribute__((visibility("hidden")))
@interface PTHTweetbotDirectMessageThreadsController : PTHViewController <UITableViewDelegate, UITableViewDataSource> {
	PTHTweetbotAccount* _account;
	UITableView* _tableView;
	NSMutableArray* _directMessageThreads;
	PTHTweetbotRefreshView* _refreshView;
	PTHTweetbotTableViewStatusView* _statusView;
	BOOL _hasUpdated;
	BOOL _hasPlayedRefreshPull;
}
@property(readonly, assign, nonatomic) PTHTweetbotAccount* account;
+(void)initialize;
-(void).cxx_destruct;
-(void)dealloc;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(unsigned)supportedInterfaceOrientations;
-(void)selectDirectMessageThreadForUser:(id)user completion:(id)completion;
-(void)_streamingTransitioned;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)updateInsets;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)_setMarkAllRead:(id)read;
-(void)update;
-(void)_updateUnreadTab;
-(void)loadNewerIfNeeded;
-(void)loadNewer;
-(void)_loadNewerDidStop;
-(void)_loadNewerDidStart;
-(void)reloadData;
-(id)initWithAccount:(id)account;
@end

