/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotCursor.h"

@class PTHTweetbotUser;

@interface PTHTweetbotUserCursor : PTHTweetbotCursor {
	PTHTweetbotUser* _user;
}
@property(readonly, assign, nonatomic) PTHTweetbotUser* user;
-(void).cxx_destruct;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setAccount:(id)account;
-(id)uniqueID;
-(id)initWithTweetbotUser:(id)tweetbotUser;
@end

