/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotObject.h"

@class NSString;

@interface PTHTweetbotCachedUser : PTHTweetbotObject {
	NSString* _name;
	NSString* _screenName;
	NSString* _profileImageURLString;
}
@property(copy, nonatomic) NSString* profileImageURLString;
@property(readonly, assign, nonatomic) NSString* displayName;
@property(copy, nonatomic) NSString* screenName;
@property(copy, nonatomic) NSString* name;
-(void).cxx_destruct;
-(id)description;
-(id)profileImageURLForSize:(unsigned)size;
-(BOOL)isLoaded;
@end

