/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "PTHTweetbotLoadingTableViewController.h"


__attribute__((visibility("hidden")))
@interface PTHTweetbotSuggestedCategoriesController : PTHTweetbotLoadingTableViewController {
}
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)loadDataIfNeeded:(BOOL)needed;
-(id)nothingFoundTitle;
-(void)configure:(id)configure forItem:(id)item;
-(id)initWithAccount:(id)account;
@end

