/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHViewController.h"

@class PTHTweetbotAccount;

__attribute__((visibility("hidden")))
@interface PTHTweetbotDeveloperAccountSettingsController : PTHViewController {
	PTHTweetbotAccount* _account;
}
-(void).cxx_destruct;
-(unsigned)supportedInterfaceOrientations;
-(void)updateUI:(id)ui;
-(void)loadView;
-(id)initWithAccount:(id)account;
@end

