/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotMediaParser.h"


@interface PTHTweetbotFlickrMediaParser : PTHTweetbotMediaParser {
}
+(BOOL)loadMediaURLFromEntity:(id)entity completion:(id)completion;
+(BOOL)loadThumbnailURLWithSize:(unsigned)size fromEntity:(id)entity completion:(id)completion;
+(BOOL)sourceFromEntity:(id)entity size:(unsigned)size completion:(id)completion;
+(int)mediaTypeForEntity:(id)entity;
+(id)parsableHosts;
@end

