/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "UITextFieldDelegate.h"
#import "PTHViewController.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class NSString, PTHSearchBar, UITableView, PTHTweetbotAccount;

__attribute__((visibility("hidden")))
@interface PTHTweetbotPeopleSearchController : PTHViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, UISearchBarDelegate> {
	PTHTweetbotAccount* _account;
	UITableView* _tableView;
	PTHSearchBar* _searchBar;
	BOOL _userSelectMode;
	NSString* _searchText;
}
@property(assign) BOOL userSelectMode;
@property(copy, nonatomic) NSString* searchText;
-(void).cxx_destruct;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(unsigned)supportedInterfaceOrientations;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)viewDidLayoutSubviews;
-(void)reloadData;
-(void)loadView;
-(id)initWithAccount:(id)account;
@end

