/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHColorGroupTableViewCell.h"

@class UIViewController, PTHTweetbotStatusFilter;

__attribute__((visibility("hidden")))
@interface PTHTweetbotMuteCell : PTHColorGroupTableViewCell {
	PTHTweetbotStatusFilter* _filter;
}
@property(retain, nonatomic) PTHTweetbotStatusFilter* filter;
@property(assign, nonatomic) __weak UIViewController* viewController;
-(void).cxx_destruct;
-(void)dealloc;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)setNeedsDisplay;
-(void)updateTime;
-(void)_longPress:(id)press;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(id)initWithColorGroupName:(id)colorGroupName reuseIdentifier:(id)identifier;
@end

