/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotObject.h"

@class NSString, PTHTweetbotUser, NSURL, PTHTweetbotCursor, PTHTweetbotPlace, NSArray, PTHTweetbotStatusActivity, NSDate, NSAttributedString, PTHTweetbotBoundingBox;

@interface PTHTweetbotStatus : PTHTweetbotObject {
	NSArray* _entities;
	BOOL _favorited;
	BOOL _retweeted;
	BOOL _mentionsCurrentUser;
	BOOL _searchResult;
	NSDate* _createdAt;
	NSString* _text;
	unsigned _retweetCount;
	unsigned _favoriteCount;
	NSString* _source;
	NSString* _sourceText;
	NSURL* _sourceURL;
	PTHTweetbotBoundingBox* _boundingBox;
	PTHTweetbotPlace* _place;
	NSString* _locationName;
	PTHTweetbotUser* _user;
	PTHTweetbotUser* _retweetedByUser;
	PTHTweetbotStatusActivity* _activity;
	NSAttributedString* _statusDetailLinkedText;
	NSString* _userScreenName;
	long long _userTID;
	long long _retweetedByUserTID;
	long long _retweetedStatusTID;
	long long _originalTID;
	long long _replyStatusTID;
	long long _replyUserTID;
	long long _currentUserRetweetTID;
}
@property(assign, nonatomic) long long currentUserRetweetTID;
@property(copy, nonatomic) NSString* userScreenName;
@property(retain, nonatomic) NSAttributedString* statusDetailLinkedText;
@property(readonly, assign, nonatomic) PTHTweetbotStatusActivity* activity;
@property(assign, nonatomic, getter=isSearchResult) BOOL searchResult;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* favoritesCursor;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* retweetsCursor;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* threadCursor;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* conversationCursor;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* repliesCursor;
@property(readonly, assign, nonatomic) NSString* emailHTML;
@property(readonly, assign, nonatomic) NSURL* favstarURL;
@property(readonly, assign, nonatomic) NSURL* twitterURL;
@property(readonly, assign, nonatomic) BOOL hasImages;
@property(readonly, assign, nonatomic) unsigned mediaCount;
@property(readonly, assign, nonatomic) BOOL hasMedia;
@property(readonly, assign, nonatomic) NSArray* entities;
@property(retain, nonatomic) PTHTweetbotUser* retweetedByUser;
@property(retain, nonatomic) PTHTweetbotUser* user;
@property(readonly, assign, nonatomic) BOOL isFromCurrentUser;
@property(readonly, assign, nonatomic) BOOL isReplyToCurrentUser;
@property(readonly, assign, nonatomic) BOOL isReply;
@property(readonly, assign, nonatomic) BOOL canUnretweet;
@property(readonly, assign, nonatomic) BOOL canRetweet;
@property(readonly, assign, nonatomic) BOOL isRetweet;
@property(retain, nonatomic) NSString* locationName;
@property(retain, nonatomic) PTHTweetbotPlace* place;
@property(retain, nonatomic) PTHTweetbotBoundingBox* boundingBox;
@property(retain, nonatomic) NSURL* sourceURL;
@property(copy, nonatomic) NSString* sourceText;
@property(copy, nonatomic) NSString* source;
@property(readonly, assign, nonatomic) NSAttributedString* attributedText;
@property(readonly, assign, nonatomic) NSString* decodedText;
@property(assign, nonatomic) BOOL mentionsCurrentUser;
@property(assign, nonatomic) unsigned favoriteCount;
@property(assign, nonatomic) unsigned retweetCount;
@property(assign, nonatomic, getter=isRetweeted) BOOL retweeted;
@property(assign, nonatomic, getter=isFavorited) BOOL favorited;
@property(assign, nonatomic) long long replyUserTID;
@property(assign, nonatomic) long long replyStatusTID;
@property(assign, nonatomic) long long originalTID;
@property(assign, nonatomic) long long retweetedStatusTID;
@property(assign, nonatomic) long long retweetedByUserTID;
@property(assign, nonatomic) long long userTID;
@property(copy, nonatomic) NSString* text;
@property(retain, nonatomic) NSDate* createdAt;
+(id)imageDataForPost:(id)post;
+(void)postDraft:(id)draft progress:(id)progress result:(id)result;
+(id)newWithAccount:(id)account dictionary:(id)dictionary;
+(id)newWithAccount:(id)account tid:(long long)tid;
-(void).cxx_destruct;
-(id)description;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setAccount:(id)account;
-(BOOL)hasString:(id)string;
-(void)updateActivityIfNeeded:(id)needed;
-(void)updateActivity:(id)activity;
-(void)unfavorite:(id)unfavorite;
-(void)favorite:(id)favorite;
-(void)unretweet:(id)unretweet;
-(void)retweet:(id)retweet;
-(void)refresh:(id)refresh;
-(void)destroy:(id)destroy;
-(void)_loadSourceInfo;
-(id)attributedText:(BOOL)text;
-(void)resetStatusDetailLinkedText;
-(void)updateFromDictionary:(id)dictionary;
-(BOOL)_updateFromDictionary:(id)dictionary;
-(id)_createdAtFromDictionary:(id)dictionary;
-(id)initWithAccount:(id)account tid:(long long)tid;
-(id)statusDetailLinkedTextCreateIfNeeded;
@end

