/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "NSObject.h"


@protocol PTHTweetbotEntityTextLabelDelegate <NSObject>
@optional
-(void)entityTextLabel:(id)label didLongPressEntity:(id)entity entityFrame:(CGRect)frame;
-(void)entityTextLabel:(id)label didTouchUpPlace:(CGRect)place;
-(void)entityTextLabel:(id)label didTouchUpEntity:(id)entity entityFrame:(CGRect)frame;
@end

