/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotCursor.h"


@interface PTHTweetbotHomeTimelineCursor : PTHTweetbotCursor {
}
+(Class)itemClass;
-(id)queryDictionary;
-(id)newItemWithDictionary:(id)dictionary;
-(id)requestURLString;
-(BOOL)canSync;
-(BOOL)usesTIDPagination;
-(BOOL)hasReadStatus;
@end

