/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PTHShapeView;

__attribute__((visibility("hidden")))
@interface PTHTweetbotLaunchController : XXUnknownSuperclass {
	PTHShapeView* _settingsButton;
	id _completion;
}
@property(copy, nonatomic) id completion;
+(void)initialize;
-(void).cxx_destruct;
-(unsigned)supportedInterfaceOrientations;
-(int)preferredStatusBarStyle;
-(void)_showSettings:(id)settings;
-(void)finish;
-(void)showSignIn;
-(void)addAccounts:(id)accounts store:(id)store cleanup:(id)cleanup;
-(void)showSelectAccounts:(id)accounts store:(id)store;
-(void)showThankYou;
-(void)_swapConstraints:(id)constraints toConstraints:(id)constraints2 completion:(id)completion;
-(void)runLaunchAnimation:(id)animation;
-(void)prepareLaunchAnimation;
-(void)loadView;
@end

