/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "PTHViewController.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class UIBarButtonItem, UILabel, NSMutableArray, UITableView, PTHTweetbotAccount;

__attribute__((visibility("hidden")))
@interface PTHTweetbotMuteController : PTHViewController <UITableViewDelegate, UITableViewDataSource> {
	PTHTweetbotAccount* _account;
	UITableView* _tableView;
	UILabel* _footerLabel;
	UIBarButtonItem* _leftBarButtonItem;
	NSMutableArray* _userFilters;
	NSMutableArray* _keywordFilters;
	NSMutableArray* _hashtagFilters;
	NSMutableArray* _sourceFilters;
}
-(void).cxx_destruct;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(unsigned)supportedInterfaceOrientations;
-(void)_updateFilters:(BOOL)filters;
-(void)showStatusFilterOptionsFromRect:(CGRect)rect inView:(id)view permittedArrowDirections:(unsigned)directions statusFilter:(id)filter completion:(id)completion;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldHighlightRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)_itemAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayHeaderView:(id)view2 forSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)addFilter:(id)filter;
-(void)toggleMode;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)reloadData;
-(id)initWithAccount:(id)account;
@end

