/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotStatusCursorController.h"

@class PTHTweetbotCursor, PTHTweetbotUser;

__attribute__((visibility("hidden")))
@interface PTHTweetbotUserTweetsController : PTHTweetbotStatusCursorController {
	PTHTweetbotUser* _user;
	PTHTweetbotCursor* _timelineCursor;
	PTHTweetbotCursor* _mentionsCursor;
	PTHTweetbotCursor* _favoritesCursor;
}
-(void).cxx_destruct;
-(void)_update:(id)update;
-(id)nothingFoundTitle;
-(id)searchTitle;
-(BOOL)shouldHideBackBarButtonTitle;
-(void)loadView;
-(id)initWithTweetbotUser:(id)tweetbotUser;
@end

