/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotSyncService.h"

@class NSMutableDictionary;

@interface PTHTweetbotTweetMarkerSyncService : PTHTweetbotSyncService {
	NSMutableDictionary* _tidsDictionary;
}
+(id)title;
-(void).cxx_destruct;
-(void)dealloc;
-(void)postPosition;
-(void)_postPositionForCursor:(id)cursor;
-(void)_postPosition;
-(void)getPosition;
-(id)queryDictionary;
-(id)request;
-(id)initWithAccount:(id)account;
@end

