/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotService.h"


@interface PTHTweetbotMediaService : PTHTweetbotService {
}
+(unsigned)maxUploadCount;
+(BOOL)canUploadMovies;
+(BOOL)canUploadImages;
+(id)genericServiceFailureTweetbotError;
+(id)serviceClasses;
-(void)cancel;
-(void)uploadMediaData:(id)data withMessage:(id)message withType:(int)type progress:(id)progress completion:(id)completion;
@end

