/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotAvatarDetailCell.h"

@class PTHTweetbotDirectMessageThread, PTHShapeView;

__attribute__((visibility("hidden")))
@interface PTHTweetbotDirectMessageThreadCell : PTHTweetbotAvatarDetailCell {
	PTHShapeView* _readIndicator;
}
@property(readonly, assign, nonatomic) PTHTweetbotDirectMessageThread* thread;
+(float)textHeight;
+(void)initialize;
-(void).cxx_destruct;
-(void)dealloc;
-(void)colorThemeDidChange;
-(void)setItem:(id)item;
-(void)_updateDirectMessageThread;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

