/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotTableViewController.h"

@class PTHTweetbotCursorGapCell, PTHTweetbotCursorUnreadItemsView, PTHTweetbotRefreshView, PTHTweetbotCursor, PTHTweetbotCursorLoadingOlderView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface PTHTweetbotCursorController : PTHTweetbotTableViewController {
	NSMutableArray* _cursorItems;
	BOOL _hasPositioned;
	PTHTweetbotRefreshView* _refreshView;
	PTHTweetbotCursorGapCell* _gapCell;
	BOOL _manuallyScrolling;
	BOOL _loadNewerOnAppear;
	BOOL _hasPlayedRefreshPull;
	BOOL _manuallyRefreshing;
	BOOL _loadingOlder;
	BOOL _loadingGap;
	NSMutableArray* _transitionBlocks;
	BOOL _transitioning;
	BOOL _showMark;
	PTHTweetbotCursorLoadingOlderView* _loadingOlderView;
	BOOL _unreadItemsShowing;
	PTHTweetbotCursorUnreadItemsView* _unreadItemsView;
	BOOL _hideNewItemsBar;
	BOOL _disableRefresh;
	PTHTweetbotCursor* _tweetbotCursor;
}
@property(assign, nonatomic) BOOL manuallyScrolling;
@property(assign, nonatomic) long long selectedTID;
@property(readonly, assign, nonatomic) long long fullyVisibleTID;
@property(assign, nonatomic) BOOL disableRefresh;
@property(retain, nonatomic) PTHTweetbotCursor* tweetbotCursor;
+(void)showTableViewAnimations:(id)animations completion:(id)completion;
-(void).cxx_destruct;
-(void)dealloc;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)shouldShowItem:(id)item;
-(void)searchTableViewControllerDidEndSearch:(id)searchTableViewController;
-(void)scrollViewDidScrollToTop:(id)scrollView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollToTop;
-(void)_didBecomeActive;
-(void)_cacheThumbnails;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)_resetLastRead;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidStop:(id)scrollView;
-(void)storePosition;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)_streamingTransitioned;
-(void)loadGap;
-(void)loadOlder;
-(void)loadNewerIfNeeded;
-(void)loadNewer;
-(void)_loadNewerDidStop;
-(void)_loadNewerDidStart;
-(void)didUpdate;
-(void)nextTransition;
-(void)runTransition:(id)transition;
-(void)update;
-(void)_update;
-(id)newItems;
-(BOOL)updateStatusViewIfNeeded:(id)needed;
-(BOOL)_deleteItemIfNeeded:(id)needed;
-(BOOL)_addNonFirstItemIfNeeded:(id)needed;
-(BOOL)_hideSearchIfNeeded:(id)needed;
-(BOOL)_updateLastIfNeeded:(id)needed;
-(BOOL)_updateGapIfNeeded:(id)needed;
-(void)setItems:(id)items;
-(float)_positionForDisplayTopTID;
-(unsigned)rowForTID:(long long)tid;
-(void)updateInsets;
-(void)_syncPositionChanged;
-(void)_syncPositionIfNeeded:(BOOL)needed;
-(void)_markIfNeeded;
-(void)_updateShowMark;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)loadView;
-(unsigned)itemDisplayCount;
-(void)_updateUnreadItemsView:(BOOL)view;
-(float)_unreadItemsPosition;
-(void)_fontSizeChanged;
-(id)initWithTweetbotCursor:(id)tweetbotCursor;
@end

