/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, UIViewController, PTHTweetbotEntity, UILongPressGestureRecognizer, NSString, NSURL, PTHAttributedLabel, PTHTweetbotStatus, NSDateFormatter, NSDate, NSFormatter, UIImage, NSAttributedString, UIColor, PTHTimeDifferenceFormatter;

__attribute__((visibility("hidden")))
@interface PTHTweetbotStatusView : XXUnknownSuperclass <UIGestureRecognizerDelegate> {
	PTHTweetbotStatus* _status;
	UIViewController* _viewController;
	int _interfaceIdiom;
	PTHTweetbotEntity* _thumbnailEntity;
	PTHAttributedLabel* _attributedLabel;
	UILongPressGestureRecognizer* _longRecognizer;
	NSFormatter* _timeFormatter;
	CGRect _profileImageRect;
	CGRect _profileBadgeImageRect;
	CGRect _selectedShadowRect;
	CGRect _textRect;
	CGRect _usernameDateRect;
	CGRect _separatorLineRect;
	CGRect _retweetRect;
	float _retweetTextWidth;
	CGRect _thumbnailRect;
	UIImage* _thumbnailImage;
	int _thumbnailMediaType;
	BOOL _showsLinks;
	BOOL _ignoresPlaceTouch;
	BOOL _rectsNeedUpdate;
	unsigned _thumbnailCount;
	BOOL _registeredForSecondNotification;
	BOOL _iTunesiOSApp;
	BOOL _iTunesMacApp;
	NSMutableArray* _accessibleElements;
	BOOL _animatingFavorited;
	CGRect _favoriteRect;
	BOOL _animatingRetweet;
	NSAttributedString* _retweetAttributedString;
	CGRect _markedRect;
	PTHTweetbotStatus* _markedStatus;
	BOOL _favorited;
	BOOL _popular;
	BOOL _conversation;
	BOOL _retweeted;
	BOOL _marked;
	BOOL _selected;
	BOOL _profileSelected;
	BOOL _retweetSelected;
	BOOL _thumbnailSelected;
	BOOL _placeSelected;
	BOOL _showTime;
	BOOL _hideSeparatorLine;
	int _type;
	PTHTweetbotEntity* _selectedEntity;
	int _imageType;
	UIColor* _separatorLineColor;
	UIColor* _timeColor;
	UIColor* _userColor;
	UIColor* _screenNameColor;
	UIColor* _retweetTextColor;
	UIColor* _retweetTextSelectedColor;
	UIColor* _thumbnailBackgroundColor;
	UIColor* _thumbnailBorderColor;
	UIColor* _avatarOutlineColor;
	UIColor* _backgroundSelectedColor;
	UIColor* _backgroundOverlayPatternColor;
	NSAttributedString* _attributedText;
	UIImage* _profileImage;
	NSURL* _profileImageURL;
	NSString* _username;
	NSString* _screenName;
	NSDate* _date;
	unsigned _colorKey;
	UIColor* _topSeparatorLineColor;
}
@property(retain, nonatomic) UIColor* topSeparatorLineColor;
@property(assign, nonatomic) unsigned colorKey;
@property(readonly, assign, nonatomic) NSDateFormatter* absoluteDateFormatter;
@property(readonly, assign, nonatomic) PTHTimeDifferenceFormatter* timeDifferenceFormatter;
@property(retain, nonatomic) NSDate* date;
@property(copy, nonatomic) NSString* screenName;
@property(copy, nonatomic) NSString* username;
@property(retain, nonatomic) PTHTweetbotEntity* thumbnailEntity;
@property(retain, nonatomic) UIImage* thumbnailImage;
@property(retain, nonatomic) NSURL* profileImageURL;
@property(retain, nonatomic) UIImage* profileImage;
@property(readonly, copy, nonatomic) NSString* retweetUserString;
@property(retain, nonatomic) NSAttributedString* attributedText;
@property(retain, nonatomic) UIColor* backgroundOverlayPatternColor;
@property(retain, nonatomic) UIColor* backgroundSelectedColor;
@property(retain, nonatomic) UIColor* avatarOutlineColor;
@property(retain, nonatomic) UIColor* thumbnailBorderColor;
@property(retain, nonatomic) UIColor* thumbnailBackgroundColor;
@property(retain, nonatomic) UIColor* retweetTextSelectedColor;
@property(retain, nonatomic) UIColor* retweetTextColor;
@property(retain, nonatomic) UIColor* screenNameColor;
@property(retain, nonatomic) UIColor* userColor;
@property(retain, nonatomic) UIColor* timeColor;
@property(assign, nonatomic) BOOL hideSeparatorLine;
@property(readonly, assign, nonatomic) CGRect separatorLineRect;
@property(retain, nonatomic) UIColor* separatorLineColor;
@property(assign, nonatomic) BOOL showTime;
@property(assign, nonatomic) int imageType;
@property(assign, nonatomic) BOOL ignoresPlaceTouch;
@property(assign, nonatomic) BOOL placeSelected;
@property(retain, nonatomic) PTHTweetbotEntity* selectedEntity;
@property(assign, nonatomic, getter=isThumbnailSelected) BOOL thumbnailSelected;
@property(assign, nonatomic, getter=isRetweetSelected) BOOL retweetSelected;
@property(assign, nonatomic, getter=isProfileSelected) BOOL profileSelected;
@property(assign, nonatomic) int type;
@property(assign, nonatomic, getter=isSelected) BOOL selected;
@property(assign, nonatomic, getter=isMarked) BOOL marked;
@property(assign, nonatomic, getter=isRetweeted) BOOL retweeted;
@property(assign, nonatomic, getter=hasConversation) BOOL conversation;
@property(assign, nonatomic, getter=isPopular) BOOL popular;
@property(assign, nonatomic, getter=isFavorited) BOOL favorited;
@property(assign, nonatomic) __weak UIViewController* viewController;
@property(retain, nonatomic) PTHTweetbotStatus* status;
@property(assign, nonatomic) int interfaceIdiom;
+(float)heightForStatus:(id)status imageType:(int)type forWidth:(float)width;
+(float)heightForStatus:(id)status interfaceIdiom:(int)idiom imageType:(int)type retweet:(BOOL)retweet forWidth:(float)width;
+(float)heightForStatusText:(id)statusText forWidth:(float)width;
+(id)attributedTextForStatus:(id)status;
+(id)linkedAttributedTextForAttributedText:(id)attributedText isMention:(BOOL)mention isSelected:(BOOL)selected;
+(id)placeFontForIdiom:(int)idiom;
+(id)textFontForIdiom:(int)idiom;
+(id)retweetUserFontForIdiom:(int)idiom;
+(id)retweetedByFontForIdiom:(int)idiom;
+(id)timeFontForIdiom:(int)idiom;
+(id)screenNameFontForIdiom:(int)idiom;
+(id)userNameFontForIdiom:(int)idiom;
+(void)initialize;
-(void).cxx_destruct;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)drawRetweetInRect:(CGRect)rect;
-(void)drawFavoriteInRect:(CGRect)rect;
-(void)setBounds:(CGRect)bounds;
-(void)setFrame:(CGRect)frame;
-(void)_updateRects;
-(CGSize)intrinsicContentSize;
-(id)colorNamed:(id)named;
-(void)_updateColors;
-(void)_animateRetweet;
-(void)_animateFavorited;
-(void)_updateDateSecond;
-(void)_updateDate;
-(void)_updateProfileImage:(id)image;
-(void)_resetDisplayName;
-(void)_resetImages;
-(void)_resetDisplay;
-(void)colorThemeDidChange;
-(id)initWithFrame:(CGRect)frame;
-(int)indexOfAccessibilityElement:(id)accessibilityElement;
-(id)accessibilityElementAtIndex:(int)index;
-(int)accessibilityElementCount;
-(id)accessibleElements;
-(BOOL)isAccessibilityElement;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(BOOL)isInCell;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)longPress:(id)press;
-(unsigned)_touchTypeFromTouch:(CGPoint)touch getEntity:(id*)entity getHitFrame:(CGRect*)frame;
-(void)_setupRecognizers;
@end

