/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, NSArray;

@interface PTHTweetbotStatusActivity : XXUnknownSuperclass {
	NSArray* _favoriterTIDs;
	NSArray* _replierTIDs;
	NSArray* _retweeterTIDs;
	NSDate* _updateDate;
}
@property(retain, nonatomic) NSDate* updateDate;
@property(readonly, assign, nonatomic) BOOL isCurrent;
@property(retain, nonatomic) NSArray* retweeterTIDs;
@property(retain, nonatomic) NSArray* replierTIDs;
@property(retain, nonatomic) NSArray* favoriterTIDs;
-(void).cxx_destruct;
@end

