/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotCursor.h"

@class PTHTweetbotPlace, CLLocation;

@interface PTHTweetbotGeoSearchCursor : PTHTweetbotCursor {
	int _granularity;
	unsigned _maxResults;
	CLLocation* _location;
}
@property(readonly, assign, nonatomic) PTHTweetbotPlace* closestPlace;
@property(readonly, assign, nonatomic) CLLocation* location;
@property(assign, nonatomic) unsigned maxResults;
@property(assign, nonatomic) int granularity;
+(Class)itemClass;
-(void).cxx_destruct;
-(id)itemsArrayFromResponse:(id)response;
-(id)queryDictionary;
-(id)requestURLString;
-(id)uniqueID;
-(id)initWithAccount:(id)account location:(id)location;
@end

