/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotObject.h"

@class PTHTweetbotCursor, PTHTweetbotUser, NSString;

@interface PTHTweetbotList : PTHTweetbotObject {
	PTHTweetbotUser* _user;
	PTHTweetbotCursor* _statusesCursor;
	BOOL _private;
	NSString* _name;
	NSString* _slug;
	NSString* _fullName;
	NSString* _listDescription;
	NSString* _userScreenName;
	int _subscriberCount;
	int _memberCount;
	long long _userTID;
}
@property(readonly, assign, nonatomic) PTHTweetbotCursor* subscribersCursor;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* membersCursor;
@property(readonly, assign, nonatomic) PTHTweetbotCursor* statusesCursor;
@property(assign, nonatomic) int memberCount;
@property(assign, nonatomic) int subscriberCount;
@property(assign, nonatomic, getter=isPrivate) BOOL private;
@property(readonly, assign, nonatomic) PTHTweetbotUser* user;
@property(copy, nonatomic) NSString* userScreenName;
@property(assign, nonatomic) long long userTID;
@property(readonly, assign, nonatomic) BOOL isFromCurrentUser;
@property(copy, nonatomic) NSString* listDescription;
@property(copy, nonatomic) NSString* fullName;
@property(copy, nonatomic) NSString* slug;
@property(copy, nonatomic) NSString* name;
+(void)createWithName:(id)name privacy:(BOOL)privacy description:(id)description forAccount:(id)account result:(id)result;
-(void).cxx_destruct;
-(id)description;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setAccount:(id)account;
-(int)compare:(id)compare;
-(void)checkMembership:(id)membership result:(id)result;
-(void)removeMember:(id)member result:(id)result;
-(void)addMember:(id)member result:(id)result;
-(void)checkSubscription:(id)subscription result:(id)result;
-(void)unsubscribe:(id)unsubscribe;
-(void)subscribe:(id)subscribe;
-(void)destroy:(id)destroy;
-(void)refresh:(id)refresh;
-(id)queryDictionary;
-(void)updateFromDictionary:(id)dictionary;
-(void)updateListWithName:(id)name privacy:(BOOL)privacy description:(id)description result:(id)result;
-(id)initWithUser:(id)user slug:(id)slug;
@end

