/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import "PTHTweetbotCursorController.h"

@class PTHTweetbotUser, PTHTweetbotCursor;

__attribute__((visibility("hidden")))
@interface PTHTweetbotUserListedController : PTHTweetbotCursorController {
	PTHTweetbotUser* _user;
	PTHTweetbotCursor* _listMembershipsCursor;
	PTHTweetbotCursor* _listsCursor;
}
-(void).cxx_destruct;
-(void)_update:(id)update;
-(float)topLayoutExtraOffset1;
-(id)modalCancelButtonTitle;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(unsigned)itemDisplayCount;
-(id)nothingFoundTitle;
-(id)itemsTitle;
-(id)itemTitle;
-(id)searchTitle;
-(Class)cellClass;
-(BOOL)shouldHideBackBarButtonTitle;
-(void)viewDidLoad;
-(id)initWithTweetbotUser:(id)tweetbotUser;
@end

