/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PTHTweetbotCursorController.h"
#import "Tweetbot-Structs.h"

@class PTHTweetbotSuggestedCategory;

__attribute__((visibility("hidden")))
@interface PTHTweetbotSuggestedCategoryController : PTHTweetbotCursorController {
	PTHTweetbotSuggestedCategory* _suggestedCategory;
	BOOL _userSelectMode;
}
@property(assign) BOOL userSelectMode;
-(void).cxx_destruct;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)searchTitle;
-(Class)cellClass;
-(void)viewDidLoad;
-(id)initWithSuggestedCategory:(id)suggestedCategory;
@end

