/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Tweetbot-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, PTHTweetbotEntity, NSURL, PTHURLRequest, MPMoviePlayerController, CAKeyframeAnimation, PTHTweetbotPostDraftMedia, PTHTweetbotAccount, UIImage, PTHImageLoader;

@interface PTHTweetbotMediaLoader : XXUnknownSuperclass {
	PTHTweetbotEntity* _entity;
	PTHTweetbotPostDraftMedia* _draftMedia;
	NSURL* _mediaURL;
	BOOL _loading;
	BOOL _loaded;
	BOOL _cancelled;
	PTHURLRequest* _imageRequest;
	id _progressBlock;
	id _responseBlock;
	PTHImageLoader* _imageLoader;
	UIImage* _thumbnailImage;
	unsigned _maxSize;
	UIImage* _image;
	MPMoviePlayerController* _moviePlayerController;
	CAKeyframeAnimation* _animation;
	int _mediaType;
	NSString* _mediaTitle;
	NSURL* _webURL;
	NSString* _imageFilename;
	PTHTweetbotAccount* _account;
	int _preferredMediaType;
}
@property(readonly, assign, nonatomic) BOOL hasLoadingProgress;
@property(assign, nonatomic) int preferredMediaType;
@property(readonly, assign, nonatomic) PTHTweetbotAccount* account;
@property(readonly, assign, nonatomic) NSString* imageFilename;
@property(readonly, assign, nonatomic) NSURL* webURL;
@property(readonly, assign, nonatomic) NSString* mediaTitle;
@property(readonly, assign, nonatomic) int mediaType;
@property(readonly, assign, nonatomic) NSURL* movieURL;
@property(readonly, assign, nonatomic) CAKeyframeAnimation* animation;
@property(readonly, assign, nonatomic) MPMoviePlayerController* moviePlayerController;
@property(readonly, assign, nonatomic) UIImage* image;
@property(assign, nonatomic) unsigned maxSize;
@property(retain, nonatomic) UIImage* thumbnailImage;
@property(retain, nonatomic) PTHImageLoader* imageLoader;
-(void).cxx_destruct;
-(void)dealloc;
-(void)copyImageToPasteboard;
-(BOOL)canCopyImage;
-(void)saveImage:(id)image;
-(BOOL)canSaveImage;
-(void)cancel;
-(void)loadWithProgress:(id)progress response:(id)response;
-(void)_loadUnknown;
-(void)_loadHTMLUnknown;
-(void)_loadMovie;
-(void)_loadDraftMovie;
-(void)_loadMediaPlayer;
-(void)_movieStateDidChange:(id)_movieState;
-(void)_loadImage;
-(void)_loadDraftImage;
-(void)_processImage;
-(void)_processImageSource:(CGImageSourceRef)source;
-(void)_sendResponse:(id)response;
-(id)initWithPostDraftMedia:(id)postDraftMedia;
-(id)initWithAccount:(id)account mediaTitle:(id)title mediaURL:(id)url mediaType:(int)type webURL:(id)url5;
-(id)initWithEntity:(id)entity;
-(id)init;
@end

