//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotMediaParser.h"

@interface _PTHTweetbotRawMediaParser : PTHTweetbotMediaParser
{
}

+ (BOOL)loadThumbnailURLWithSize:(unsigned int)arg1 fromEntity:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (int)mediaTypeForEntity:(id)arg1;

@end

