//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UIImage;

@interface _PTHTweetbotMediaLoaderView : UIView
{
    UIImage *_backgroundImage;
    UIImage *_frameImage;
    float _indeterminateProgress;
    NSTimer *_indeterminateTimer;
    float _progress;
}

@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)_updateIndeterminate;
- (id)initWithFrame:(struct CGRect)arg1;

@end

