//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PTHCustomTabBar;

@interface PTHCustomTabBarContainerView : UIView
{
    BOOL _customTabBarHidden;
    PTHCustomTabBar *_customTabBar;
    UIView *_controllerView;
    UIView *_backgroundView;
}

@property(nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) UIView *controllerView; // @synthesize controllerView=_controllerView;
@property(nonatomic, getter=isCustomTabBarHidden) BOOL customTabBarHidden; // @synthesize customTabBarHidden=_customTabBarHidden;
@property(nonatomic) PTHCustomTabBar *customTabBar; // @synthesize customTabBar=_customTabBar;
- (void)layoutSubviews;
- (void)setCustomTabBarHidden:(BOOL)arg1 animated:(BOOL)arg2;

@end

