//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray, UIView;

@interface PTHDial : UIControl
{
    NSArray *_notchViews;
    unsigned int _value;
    UIView *_backgroundView;
    BOOL _didMove;
}

@property(nonatomic) unsigned int value; // @synthesize value=_value;
- (void)dealloc;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)cancelTrackingWithEvent:(id)arg1;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
@property(copy, nonatomic) NSArray *notchViews;
- (void)setValue:(unsigned int)arg1 animated:(BOOL)arg2;
- (unsigned int)_currentValue;
- (int)_position;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithTitles:(id)arg1;
- (id)initWithTitleArray:(id)arg1;

@end

