//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString;

@interface PTHGroupedTableViewCell : UITableViewCell
{
    int _position;
    NSString *_backgroundImageNamePrefix;
    int _leftCapWidth;
    int _topCapHeight;
}

+ (int)positionInArray:(id)arg1 atIndex:(int)arg2;
@property(nonatomic) int topCapHeight; // @synthesize topCapHeight=_topCapHeight;
@property(nonatomic) int leftCapWidth; // @synthesize leftCapWidth=_leftCapWidth;
@property(copy, nonatomic) NSString *backgroundImageNamePrefix; // @synthesize backgroundImageNamePrefix=_backgroundImageNamePrefix;
@property(nonatomic) int position; // @synthesize position=_position;
- (void)dealloc;
- (void)setSelectionStyle:(int)arg1;
- (void)_updateBackground;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

