//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PTHHelpController, UIView;

@protocol PTHHelpControllerDelegate <NSObject>

@optional
- (void)helpControllerDidEndDecelerating:(PTHHelpController *)arg1;
- (void)helpControllerDidScroll:(PTHHelpController *)arg1;
- (void)configureHelpController:(PTHHelpController *)arg1 pageView:(UIView *)arg2 atIndex:(int)arg3;
@end

