//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHPageViewDataSource.h"
#import "PTHPageViewDelegate.h"

@class NSMutableArray, PTHHelpStep, PTHHitInsetButton, PTHPageView, PTHPageViewControl, UIView;

@interface PTHHelpController : PTHViewController <PTHPageViewDelegate, PTHPageViewDataSource>
{
    NSMutableArray *_steps;
    PTHHelpStep *_preStep;
    float _descriptionOffset;
    PTHHitInsetButton *_nextButton;
    NSMutableArray *_visibleSteps;
    NSMutableArray *_views;
    UIView *_preView;
    BOOL _delegateRespondsToDidScroll;
    BOOL _firstTime;
    id <PTHHelpControllerDelegate> _delegate;
    PTHPageView *_pageView;
    PTHPageViewControl *_pageViewControl;
    Class _pageViewClass;
}

+ (void)setHasShownFirstTimeHelp:(BOOL)arg1;
+ (BOOL)hasShownFirstTimeHelp;
@property(nonatomic) Class pageViewClass; // @synthesize pageViewClass=_pageViewClass;
@property(readonly, nonatomic) PTHPageViewControl *pageViewControl; // @synthesize pageViewControl=_pageViewControl;
@property(readonly, nonatomic) PTHPageView *pageView; // @synthesize pageView=_pageView;
@property(nonatomic, getter=isFirstTime) BOOL firstTime; // @synthesize firstTime=_firstTime;
@property(nonatomic) id <PTHHelpControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)pageViewDidEndDecelerating:(id)arg1;
- (void)pageViewDidScroll:(id)arg1;
- (id)pageView:(id)arg1 pageAtIndex:(int)arg2;
- (id)prependView:(id)arg1;
- (id)_viewForStep:(id)arg1 pageView:(id)arg2;
- (void)next:(id)arg1;
- (unsigned int)numberOfPagesInPageView:(id)arg1;
- (id)imageViewAtIndex:(int)arg1;
- (id)actionLabelAtIndex:(int)arg1;
- (id)descriptionLabelAtIndex:(int)arg1;
- (id)titleLabelAtIndex:(int)arg1;
- (id)helpViewAtIndex:(int)arg1;
- (void)removePreStep;
- (id)newViewWithHelpStep:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

