//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, NSURL;

@interface PTHNotice : NSObject
{
    NSDate *_startDate;
    NSDate *_endDate;
    unsigned int _startVersion;
    unsigned int _endVersion;
    NSString *_title;
    NSString *_message;
    NSString *_actionTitle;
    NSURL *_actionURL;
    unsigned int _startOSVersion;
    unsigned int _endOSVersion;
}

+ (void)setReadNotices:(id)arg1;
+ (void)resetReadNotices;
+ (id)unreadNotices;
@property(nonatomic) unsigned int endOSVersion; // @synthesize endOSVersion=_endOSVersion;
@property(nonatomic) unsigned int startOSVersion; // @synthesize startOSVersion=_startOSVersion;
@property(retain, nonatomic) NSURL *actionURL; // @synthesize actionURL=_actionURL;
@property(copy, nonatomic) NSString *actionTitle; // @synthesize actionTitle=_actionTitle;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) unsigned int endVersion; // @synthesize endVersion=_endVersion;
@property(nonatomic) unsigned int startVersion; // @synthesize startVersion=_startVersion;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
- (void)dealloc;
- (id)description;
- (id)initWithDictionary:(id)arg1;

@end

