//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, UIFont;

@interface PTHShadowGlowLabel : UIView
{
    BOOL _adjustsFontSizeToFitWidth;
    NSString *_text;
    UIFont *_font;
    int _textAlignment;
    UIColor *_textColor;
    UIColor *_shadowColor;
    UIColor *_glowColor;
    float _glowBlur;
    unsigned int _blurCount;
    int _lineBreakMode;
    float _minimumFontSize;
    int _baselineAdjustment;
    struct CGSize _shadowOffset;
}

@property(nonatomic) int baselineAdjustment; // @synthesize baselineAdjustment=_baselineAdjustment;
@property(nonatomic) float minimumFontSize; // @synthesize minimumFontSize=_minimumFontSize;
@property(nonatomic) BOOL adjustsFontSizeToFitWidth; // @synthesize adjustsFontSizeToFitWidth=_adjustsFontSizeToFitWidth;
@property(nonatomic) int lineBreakMode; // @synthesize lineBreakMode=_lineBreakMode;
@property(nonatomic) unsigned int blurCount; // @synthesize blurCount=_blurCount;
@property(nonatomic) float glowBlur; // @synthesize glowBlur=_glowBlur;
@property(retain, nonatomic) UIColor *glowColor; // @synthesize glowColor=_glowColor;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(retain, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) int textAlignment; // @synthesize textAlignment=_textAlignment;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)sizeToFit;
@property(readonly, nonatomic) struct CGSize textSize;
- (struct CGSize)textSizeForString:(id)arg1;
- (struct CGSize)_textSizeWithoutGlowAndShadows:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

