//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface PTHSQLiteDatabase : NSObject
{
    NSString *_path;
    NSMutableDictionary *_preparedStatements;
    BOOL _open;
    BOOL _deleted;
    BOOL _verified;
    struct sqlite3 *_database;
    struct dispatch_queue_s *_queue;
    BOOL _skipBackup;
}

+ (BOOL)asynchronous;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) BOOL skipBackup; // @synthesize skipBackup=_skipBackup;
- (void)dealloc;
- (id)verifyDatabase:(struct sqlite3 *)arg1;
- (id)databaseWasCreated:(struct sqlite3 *)arg1;
- (void)connectionDidClose;
- (void)connectionDidOpen:(struct sqlite3 *)arg1;
@property(readonly, nonatomic) BOOL isConnectionOpen;
@property int userVersion;
- (void)dispatchFetchSingleColumn:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)executeFetchSingleColumn:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)performFetchSingleColumn:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)dispatchFetch:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)executeFetch:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)performFetch:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)dispatchPreparedStatement:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)executePreparedStatement:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)performPreparedStatement:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)dispatchStatement:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)executeStatement:(id)arg1 result:(CDUnknownBlockType)arg2;
- (int)performStatement:(id)arg1 error:(id *)arg2;
- (void)dispatch:(CDUnknownBlockType)arg1;
- (void)dispatchTransaction:(CDUnknownBlockType)arg1;
- (void)executeTransaction:(CDUnknownBlockType)arg1;
- (void)performTransaction:(CDUnknownBlockType)arg1;
- (void)_closeConnectionForBackground;
- (void)closeConnectionSync;
- (void)closeConnection;
- (void)_closeConnection;
- (BOOL)open:(id *)arg1;
- (void)delete;
- (void)_delete;
- (void)dispatchSync:(CDUnknownBlockType)arg1;
- (void)dispatchAsync:(CDUnknownBlockType)arg1;
- (id)initWithPath:(id)arg1;
- (id)newValueFromStatement:(struct sqlite3_stmt *)arg1 atColumn:(unsigned int)arg2;

@end

