//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface PTHStack : NSObject
{
    unsigned int _capacity;
    NSMutableArray *_array;
}

@property(readonly) unsigned int capacity; // @synthesize capacity=_capacity;
- (void)dealloc;
- (id)description;
- (id)valueForKeyPath:(id)arg1;
@property(readonly) BOOL isFull;
@property(readonly) unsigned int count;
@property(readonly) NSArray *array;
- (void)removeAllObjects;
- (id)popFirstObject;
- (id)popLastObject;
- (void)pushObject:(id)arg1;
- (id)initWithCapacity:(unsigned int)arg1;
- (id)init;

@end

