//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKStoreProductViewController.h"

#import "SKStoreProductViewControllerDelegate.h"

@interface PTHStoreProductViewController : SKStoreProductViewController <SKStoreProductViewControllerDelegate>
{
    CDUnknownBlockType _completion;
}

@property(copy) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)dealloc;
- (void)productViewControllerDidFinish:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)presentProductPage:(unsigned int)arg1 forViewController:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

@end

