//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusCursorController.h"

@class PTHTweetbotStatus;

@interface PTHTweetbotStatusThreadController : PTHTweetbotStatusCursorController
{
    PTHTweetbotStatus *_status;
}

- (void)dealloc;
- (void)_share:(id)arg1;
- (void)didUpdate;
- (id)newItems;
- (BOOL)needsToolbar;
- (id)searchTitle;
- (id)initWithStatus:(id)arg1;

@end

