//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotOAuthMediaService.h"

@interface PTHTweetbotCustomMediaService : PTHTweetbotOAuthMediaService
{
}

+ (BOOL)verifyWithAccount:(id)arg1;
+ (id)title;
+ (BOOL)canUploadMovies;
+ (BOOL)canUploadImages;
+ (id)customHelpURL;
- (id)urlStringFromResponse:(id)arg1;
- (id)uploadPostDictionary;
- (id)uploadMessageKey;
- (id)uploadMediaKey;
- (id)uploadURL;
- (int)uploadResponseType;

@end

