//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCell.h"

@class NSMutableArray, PTHHitInsetButton, PTHTweetbotStatus, PTHTweetbotStatusView, UIView;

@interface PTHTweetbotStatusCell : PTHTweetbotCell
{
    PTHTweetbotStatusView *_statusView;
    BOOL _isFavorited;
    UIView *_drawerView;
    PTHHitInsetButton *_actionButton;
    PTHHitInsetButton *_replyButton;
    PTHHitInsetButton *_retweetButton;
    PTHHitInsetButton *_favoriteButton;
    PTHHitInsetButton *_shareButton;
    unsigned int _cellType;
    NSMutableArray *_tapGestureRecognizers;
    BOOL _sliding;
}

+ (unsigned int)selectedDrawerHeightforTableView:(id)arg1;
+ (unsigned int)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (Class)statusViewClass;
@property(readonly, retain, nonatomic) PTHTweetbotStatusView *statusView; // @synthesize statusView=_statusView;
- (void)dealloc;
- (void)layoutSubviews;
@property(nonatomic, getter=isMarked) BOOL marked;
- (void)setItem:(id)arg1;
- (void)_statusWasUpdated:(id)arg1;
- (void)_userWasUpdated:(id)arg1;
- (void)updateStatus;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)showActions:(id)arg1;
- (void)_showActionLongOptions:(id)arg1;
- (void)_showFavoriteLongOptions:(id)arg1;
- (void)_showRetweetLongOptions:(id)arg1;
- (void)retweet:(id)arg1;
- (void)toggleFavorite:(id)arg1;
- (void)_updateFavorite:(BOOL)arg1;
- (void)reply:(id)arg1;
- (void)showShare:(id)arg1;
- (void)_swipeLeft:(id)arg1;
- (void)_swipeRight:(id)arg1;
- (void)_slideAnimation:(BOOL)arg1 controllerClass:(Class)arg2;
- (id)_createSlideBackgroundView:(BOOL)arg1 shadowView:(id *)arg2 spinnerView:(id *)arg3;
- (BOOL)_hideDrawer;
- (void)setViewController:(id)arg1;
- (void)longPress:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(readonly, retain, nonatomic) PTHTweetbotStatus *status;

@end

