//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, NSURL, PTHFramedImageView, UIImage;

@interface PTHTweetbotPostSearchItemCell : UIControl
{
    UIImage *_backgroundImage;
    UIImage *_highlightedBackgroundImage;
    PTHFramedImageView *_framedImageView;
    NSURL *_imageURL;
    BOOL _hasImage;
    id _item;
    NSString *_title;
}

+ (id)titleForItem:(id)arg1;
+ (float)widthForItem:(id)arg1;
+ (float)widthForString:(id)arg1;
+ (void)initialize;
@property(nonatomic) BOOL hasImage; // @synthesize hasImage=_hasImage;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) id item; // @synthesize item=_item;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

