//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHTweetbotPostAccountControllerDelegate.h"
#import "PTHTweetbotPostToolbarViewDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, PTHHelpPointer, PTHLocationManager, PTHTweetbotAccount, PTHTweetbotMediaService, PTHTweetbotPostDraft, PTHTweetbotPostDraftMedia, PTHTweetbotPostPhoneAccountController, PTHTweetbotPostPhoneView, PTHTweetbotURLShortnerService, UITextView, UIView;

@interface PTHTweetbotPostController : PTHViewController <UITextViewDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, PTHTweetbotPostToolbarViewDelegate, PTHTweetbotPostAccountControllerDelegate>
{
    PTHTweetbotAccount *_account;
    PTHTweetbotPostDraft *_draft;
    BOOL _ignoreShortenErrors;
    PTHTweetbotPostPhoneView *_postView;
    PTHHelpPointer *_draftsHelpPointer;
    PTHLocationManager *_locationManager;
    BOOL _firstTime;
    PTHTweetbotPostDraftMedia *_pickedMedia;
    PTHTweetbotPostPhoneAccountController *_accountController;
    UIView *_accountShadowView;
    UIView *_postShadowView;
    struct _NSRange _selectedRange;
    unsigned int _postTask;
    BOOL _backgroundPost;
    BOOL _cancelled;
    PTHTweetbotURLShortnerService *_currentShortnerService;
    PTHTweetbotMediaService *_currentMediaService;
    BOOL _searchingLocation;
    NSString *_locationErrorString;
    int _cursorPosition;
}

@property(nonatomic) int cursorPosition; // @synthesize cursorPosition=_cursorPosition;
@property(nonatomic) BOOL searchingLocation; // @synthesize searchingLocation=_searchingLocation;
@property(retain, nonatomic) NSString *locationErrorString; // @synthesize locationErrorString=_locationErrorString;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
@property(readonly, retain, nonatomic) UITextView *textView;
- (void)stopLocationSearch;
- (void)startLocationSearch;
- (void)_startLocationSearch;
- (void)_showGeo:(id)arg1;
- (void)_updateGEOButton;
- (id)_locationTitle;
- (void)showCameraOptions:(id)arg1;
- (void)showOptions:(id)arg1;
- (id)draftsButtonTitleEnabled:(char *)arg1;
- (void)_showAddNote:(CDUnknownBlockType)arg1;
- (void)addMedia:(id)arg1;
- (void)_showImagePicker:(int)arg1 inView:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)showDraftsInView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)_updateSelectedEntity;
- (BOOL)disablesAutomaticKeyboardDismissal;
- (void)searchEntity:(id)arg1 control:(id)arg2;
- (void)replaceEntity:(id)arg1 withText:(id)arg2;
- (void)addHashtag:(id)arg1;
- (void)addUser:(id)arg1;
- (void)_addUserOrHashtag:(id)arg1;
- (id)selectedEntity;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (void)didSelectAccount:(id)arg1;
- (void)_switchAccounts:(id)arg1;
- (void)setAccount:(id)arg1;
- (void)selectedMedia:(id)arg1 inView:(id)arg2;
- (void)loadView;
- (id)postToolbarView;
- (void)ok:(id)arg1;
- (id)modalCancelButtonTitle;
- (void)_updatePostButton;
- (void)_keyUpNotification:(id)arg1;
- (id)initWithDraft:(id)arg1;
- (void)_post:(CDUnknownBlockType)arg1;
- (void)_postUploadMedia:(CDUnknownBlockType)arg1;
- (void)_postShortenURLs:(id)arg1 cleanupBlock:(CDUnknownBlockType)arg2;
- (void)cancelPost:(id)arg1;
- (void)post:(id)arg1;

@end

