//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PTHTweetbotOfflineQueue : NSObject
{
}

+ (id)sharedController;
- (void)dealloc;
- (void)_reachabilityDidChange;
- (void)addQueueItem:(id)arg1;
- (void)addQueueAction:(SEL)arg1 targetClass:(Class)arg2 argument:(id)arg3;
- (id)init;

@end

