//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHTweetbotEntityTextLabelDelegate.h"
#import "UIScrollViewDelegate.h"

@class PTHControlCell, PTHFramedImageView, PTHGradientView, PTHHitInsetButton, PTHTweetbotEntityTextLabel, PTHTweetbotPhoneProfileCursorControlCell, PTHTweetbotRelationship, PTHTweetbotUser, UIImageView, UILabel, UIScrollView, UIView;

@interface PTHTweetbotPhoneProfileController : PTHViewController <PTHTweetbotEntityTextLabelDelegate, UIScrollViewDelegate>
{
    PTHTweetbotUser *_user;
    UIScrollView *_scrollView;
    PTHGradientView *_followingStatusBackgroundView;
    UILabel *_followingLabel;
    PTHGradientView *_mainBackgroundView;
    PTHFramedImageView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_screenNameLabel;
    PTHTweetbotEntityTextLabel *_descriptionLabel;
    UIImageView *_violatorView;
    PTHHitInsetButton *_optionsButton;
    PTHHitInsetButton *_reportButton;
    UIImageView *_coverImageView;
    PTHGradientView *_coverImageTopShadow;
    PTHGradientView *_coverImageBottomShadow;
    BOOL _needsCoverImage;
    PTHControlCell *_locationCell;
    PTHControlCell *_webCell;
    PTHGradientView *_statusBackgroundView;
    UILabel *_statusTimeLabel;
    UIView *_cursorsBackground;
    PTHTweetbotPhoneProfileCursorControlCell *_tweetsCell;
    PTHTweetbotPhoneProfileCursorControlCell *_followersCell;
    PTHTweetbotPhoneProfileCursorControlCell *_followingCell;
    PTHTweetbotPhoneProfileCursorControlCell *_listMembershipsCell;
    PTHGradientView *_detailsBackgroundView;
    UILabel *_detailsLabel;
    UIView *_footerView;
    BOOL _needsProfileImage;
    BOOL _hasRefreshed;
    PTHTweetbotRelationship *_relationship;
}

- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)entityTextLabel:(id)arg1 didLongPressEntity:(id)arg2 entityFrame:(struct CGRect)arg3;
- (void)entityTextLabel:(id)arg1 didTouchUpEntity:(id)arg2 entityFrame:(struct CGRect)arg3;
- (void)_showUser:(id)arg1;
- (void)_showFavstar:(id)arg1;
- (id)modalCancelButtonTitle;
- (void)_showCoverImage:(id)arg1;
- (void)_showAvatarImage:(id)arg1;
- (void)_showReport:(id)arg1;
- (void)_showOptions:(id)arg1;
- (void)_showListMemberships:(id)arg1;
- (void)_showFollowing:(id)arg1;
- (void)_showFollowers:(id)arg1;
- (void)_showTweets:(id)arg1;
- (void)_showLocation:(id)arg1;
- (void)_showWeb:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)update:(BOOL)arg1;
- (void)_addCoverImageView;
- (void)_updateFollowing:(BOOL)arg1;
- (void)loadView;
- (void)edit:(id)arg1;
- (id)initWithTweetbotUser:(id)arg1;
- (void)_swipeRight:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

