//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotObject.h"

@class NSArray, NSMutableArray, PTHTweetbotDirectMessage, PTHTweetbotUser;

@interface PTHTweetbotDirectMessageThread : PTHTweetbotObject
{
    NSMutableArray *_messagesAndDrafts;
    PTHTweetbotUser *_toUser;
    unsigned int _unreadItemCount;
    long long _lastReadTID;
}

@property(nonatomic) long long lastReadTID; // @synthesize lastReadTID=_lastReadTID;
@property(readonly, nonatomic) unsigned int unreadItemCount; // @synthesize unreadItemCount=_unreadItemCount;
@property(copy, nonatomic) NSArray *messagesAndDrafts; // @synthesize messagesAndDrafts=_messagesAndDrafts;
@property(retain, nonatomic) PTHTweetbotUser *toUser; // @synthesize toUser=_toUser;
- (void)dealloc;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setAccount:(id)arg1;
- (BOOL)hasString:(id)arg1;
@property(readonly, nonatomic, getter=isRead) BOOL read;
- (void)markRead;
- (void)removeMessage:(id)arg1;
- (void)addMessage:(id)arg1;
- (BOOL)updateMessagesAndDrafts:(id)arg1;
- (void)resetUnreadItemCount;
- (unsigned int)_unreadItemCount;
- (void)destroy:(CDUnknownBlockType)arg1;
@property(readonly, retain, nonatomic) PTHTweetbotDirectMessage *latestMessage;
@property(readonly, copy, nonatomic) NSArray *messages;
@property(readonly, nonatomic) long long toUserTID;

@end

