//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, PTHTweetbotAccount, PTHTweetbotPostDraft, UIBarButtonItem, UITableView;

@interface PTHTweetbotPostDraftsController : PTHViewController <UITableViewDelegate, UITableViewDataSource>
{
    PTHTweetbotAccount *_account;
    UITableView *_tableView;
    UIBarButtonItem *_editBarButtonItem;
    UIBarButtonItem *_doneBarButtonItem;
    NSMutableArray *_postDrafts;
    PTHTweetbotPostDraft *_postDraft;
}

@property(retain, nonatomic) PTHTweetbotPostDraft *postDraft; // @synthesize postDraft=_postDraft;
- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)modalCancelButtonTitle;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)_updateVisiblePositions;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)loadView;
- (void)viewMode;
- (void)editMode;
- (id)initWithAccount:(id)arg1;

@end

