//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCell.h"

@class PTHGradientView, PTHTweetbotAvatarFramedView, UIControl, UIImageView, UILabel, UIView;

@interface PTHTweetbotStatusMediaCell : PTHTweetbotCell
{
    UIImageView *_statusImageView;
    UIImageView *_spinnerView;
    PTHTweetbotAvatarFramedView *_avatarImageView;
    UILabel *_statusLabel;
    UIControl *_headerView;
    UIView *_headerViewBackground;
    PTHGradientView *_headerShadowView;
    UIImageView *_playImageView;
    BOOL _imageHidden;
}

+ (unsigned int)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
@property(nonatomic) BOOL imageHidden; // @synthesize imageHidden=_imageHidden;
- (void)dealloc;
- (void)layoutSubviews;
- (void)setScrollPosition:(float)arg1;
- (void)setItem:(id)arg1;
- (void)showDetail:(id)arg1;
- (void)_showImage;
- (id)entity;
- (id)status;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

