//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, PTHTweetbotAccount, UILabel, UITableView, UIView;

@interface PTHTweetbotTimelineListController : PTHViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_listView;
    PTHTweetbotAccount *_account;
    UILabel *_footerLabel;
    NSMutableArray *_publicLists;
    NSMutableArray *_privateLists;
    NSMutableArray *_subscribedLists;
    UIView *_privateListsHeader;
    UIView *_publicListsHeader;
    UIView *_subscribedListsHeader;
    id <PTHTweetbotTimelineListControllerDelegate> _delegate;
}

@property(nonatomic) id <PTHTweetbotTimelineListControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UITableView *listView; // @synthesize listView=_listView;
- (void)dealloc;
- (void)_updateCells;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)_positionAtIndexPath:(id)arg1;
- (id)_listAtIndexPath:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)_updateFooter:(BOOL)arg1;
- (void)update;
- (void)loadView;
- (id)initWithAccount:(id)arg1;

@end

