//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSString, PTHTweetbotAccount, PTHTweetbotSearchCell, PTHTweetbotSearchFieldCell, UITableView;

@interface PTHTweetbotPeopleSearchController : PTHViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate>
{
    PTHTweetbotAccount *_account;
    UITableView *_tableView;
    PTHTweetbotSearchFieldCell *_searchFieldCell;
    BOOL _hasSearchText;
    PTHTweetbotSearchCell *_userCell;
    BOOL _userSelectMode;
    NSString *_searchText;
}

@property BOOL userSelectMode; // @synthesize userSelectMode=_userSelectMode;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (void)viewWillAppear:(BOOL)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)_hideKeyboard;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)loadView;
- (id)initWithAccount:(id)arg1;

@end

