//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStandardCell.h"

@class UIImageView;

@interface PTHTweetbotDirectMessagesPeopleSearchCell : PTHTweetbotStandardCell
{
    UIImageView *_findUserImageView;
}

- (void)dealloc;
- (void)layoutSubviews;
- (void)setItem:(id)arg1;
- (float)textHorizontalOffset;
- (struct CGPoint)avatarImageOffset;
- (id)user;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

