//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class UIColor, UIImage;

@interface PTHTextField : UITextField
{
    UIImage *_backgroundImage;
    UIImage *_highlightedBackgroundImage;
    UIColor *_highlightedTextColor;
    UIColor *_oldTextColor;
    struct UIEdgeInsets _textInset;
    struct UIEdgeInsets _clearButtonInset;
}

@property(retain, nonatomic) UIColor *oldTextColor; // @synthesize oldTextColor=_oldTextColor;
@property(retain, nonatomic) UIColor *highlightedTextColor; // @synthesize highlightedTextColor=_highlightedTextColor;
@property(nonatomic) struct UIEdgeInsets clearButtonInset; // @synthesize clearButtonInset=_clearButtonInset;
@property(nonatomic) struct UIEdgeInsets textInset; // @synthesize textInset=_textInset;
- (void)dealloc;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setHighlightedPNGName:(id)arg1 leftCapWidth:(int)arg2;
- (void)setPNGName:(id)arg1 leftCapWidth:(int)arg2;
- (void)setHighlightedCachedPNGName:(id)arg1 leftCapWidth:(int)arg2;
- (void)setCachedPNGName:(id)arg1 leftCapWidth:(int)arg2;
- (struct CGRect)clearButtonRectForBounds:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;

@end

