//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotObject.h"

@class NSArray, NSAttributedString, NSDate, NSString, NSURL, PTHTweetbotBoundingBox, PTHTweetbotCursor, PTHTweetbotPlace, PTHTweetbotStatusActivity, PTHTweetbotUser;

@interface PTHTweetbotStatus : PTHTweetbotObject
{
    BOOL _favorited;
    BOOL _retweeted;
    BOOL _mentionsCurrentUser;
    NSDate *_createdAt;
    NSString *_text;
    NSString *_source;
    NSString *_userScreenName;
    NSArray *_entities;
    PTHTweetbotUser *_user;
    PTHTweetbotUser *_retweetedByUser;
    PTHTweetbotBoundingBox *_boundingBox;
    PTHTweetbotPlace *_place;
    NSString *_sourceText;
    NSURL *_sourceURL;
    NSAttributedString *_statusDetailLinkedText;
    PTHTweetbotStatusActivity *_activity;
    NSString *_locationName;
    unsigned int _retweetCount;
    unsigned int _favoriteCount;
    long long _userTID;
    long long _retweetedByUserTID;
    long long _replyStatusTID;
    long long _retweetedStatusTID;
    long long _currentUserRetweetTID;
    long long _replyUserTID;
    long long _originalTID;
}

+ (id)imageDataForPost:(id)arg1;
+ (void)postDraft:(id)arg1 progress:(CDUnknownBlockType)arg2 result:(CDUnknownBlockType)arg3;
+ (id)newWithAccount:(id)arg1 dictionary:(id)arg2;
+ (id)newWithAccount:(id)arg1 tid:(long long)arg2;
@property(nonatomic) unsigned int favoriteCount; // @synthesize favoriteCount=_favoriteCount;
@property(nonatomic) unsigned int retweetCount; // @synthesize retweetCount=_retweetCount;
@property(retain, nonatomic) NSString *locationName; // @synthesize locationName=_locationName;
@property(nonatomic) long long originalTID; // @synthesize originalTID=_originalTID;
@property(readonly, retain, nonatomic) PTHTweetbotStatusActivity *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) NSAttributedString *statusDetailLinkedText; // @synthesize statusDetailLinkedText=_statusDetailLinkedText;
@property(retain, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(retain, nonatomic) NSString *sourceText; // @synthesize sourceText=_sourceText;
@property(retain, nonatomic) PTHTweetbotPlace *place; // @synthesize place=_place;
@property(retain, nonatomic) PTHTweetbotBoundingBox *boundingBox; // @synthesize boundingBox=_boundingBox;
@property(retain, nonatomic) PTHTweetbotUser *retweetedByUser; // @synthesize retweetedByUser=_retweetedByUser;
@property(retain, nonatomic) PTHTweetbotUser *user; // @synthesize user=_user;
@property(nonatomic) BOOL mentionsCurrentUser; // @synthesize mentionsCurrentUser=_mentionsCurrentUser;
@property(nonatomic, getter=isRetweeted) BOOL retweeted; // @synthesize retweeted=_retweeted;
@property(nonatomic, getter=isFavorited) BOOL favorited; // @synthesize favorited=_favorited;
@property(nonatomic) long long replyUserTID; // @synthesize replyUserTID=_replyUserTID;
@property(nonatomic) long long currentUserRetweetTID; // @synthesize currentUserRetweetTID=_currentUserRetweetTID;
@property(nonatomic) long long retweetedStatusTID; // @synthesize retweetedStatusTID=_retweetedStatusTID;
@property(nonatomic) long long replyStatusTID; // @synthesize replyStatusTID=_replyStatusTID;
@property(nonatomic) long long retweetedByUserTID; // @synthesize retweetedByUserTID=_retweetedByUserTID;
@property(copy, nonatomic) NSString *userScreenName; // @synthesize userScreenName=_userScreenName;
@property(nonatomic) long long userTID; // @synthesize userTID=_userTID;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSDate *createdAt; // @synthesize createdAt=_createdAt;
- (void)dealloc;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setAccount:(id)arg1;
- (BOOL)hasString:(id)arg1;
- (void)updateActivityIfNeeded:(CDUnknownBlockType)arg1;
- (void)updateActivity:(CDUnknownBlockType)arg1;
- (void)unfavorite:(CDUnknownBlockType)arg1;
- (void)favorite:(CDUnknownBlockType)arg1;
- (void)unretweet:(CDUnknownBlockType)arg1;
- (void)retweet:(CDUnknownBlockType)arg1;
- (void)refresh:(CDUnknownBlockType)arg1;
- (void)destroy:(CDUnknownBlockType)arg1;
@property(readonly, retain, nonatomic) PTHTweetbotCursor *retweetsCursor;
@property(readonly, retain, nonatomic) PTHTweetbotCursor *threadCursor;
@property(readonly, retain, nonatomic) PTHTweetbotCursor *conversationCursor;
@property(readonly, retain, nonatomic) PTHTweetbotCursor *repliesCursor;
@property(readonly, nonatomic) BOOL isFromCurrentUser;
@property(readonly, nonatomic) BOOL isReplyToCurrentUser;
@property(readonly, nonatomic) BOOL isReply;
@property(readonly, nonatomic) BOOL canRetweet;
@property(readonly, nonatomic) BOOL canUnretweet;
@property(readonly, nonatomic) BOOL isRetweet;
@property(readonly, nonatomic) NSString *emailHTML;
@property(readonly, nonatomic) NSURL *favstarURL;
@property(readonly, nonatomic) NSURL *twitterURL;
- (void)_loadSourceInfo;
@property(readonly, retain, nonatomic) NSAttributedString *attributedText;
- (id)attributedText:(BOOL)arg1;
@property(readonly, retain, nonatomic) NSString *decodedText;
- (void)resetStatusDetailLinkedText;
@property(readonly, nonatomic) BOOL hasImages;
@property(readonly, nonatomic) unsigned int mediaCount;
@property(readonly, nonatomic) BOOL hasMedia;
@property(readonly, retain, nonatomic) NSArray *entities; // @synthesize entities=_entities;
- (void)updateFromDictionary:(id)arg1;
- (BOOL)_updateFromDictionary:(id)arg1;
- (id)_createdAtFromDictionary:(id)arg1;
- (id)initWithAccount:(id)arg1 tid:(long long)arg2;
- (id)statusDetailLinkedTextCreateIfNeeded;

@end

