//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotMediaService.h"

@class PTHURLRequest;

@interface PTHTweetbotCloudAppMediaService : PTHTweetbotMediaService
{
    PTHURLRequest *_cloudRequest;
    PTHURLRequest *_s3Request;
}

+ (void)authenticate:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)keychainAccountName;
+ (BOOL)needsAuthentication;
+ (id)title;
+ (BOOL)canUploadText;
+ (BOOL)canUploadMovies;
+ (BOOL)canUploadImages;
- (void)dealloc;
- (void)cancel;
- (void)uploadMediaData:(id)arg1 withMessage:(id)arg2 withType:(int)arg3 progress:(CDUnknownBlockType)arg4 completion:(CDUnknownBlockType)arg5;
- (id)newRequest;

@end

