//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusCursor.h"

@interface PTHTweetbotStatusRepliesCursor : PTHTweetbotStatusCursor
{
}

+ (Class)itemClass;
- (id)newItemWithDictionary:(id)arg1;
- (id)queryDictionary;
- (id)itemsArrayFromResponse:(id)arg1;
- (id)requestURLString;
- (BOOL)hasReadStatus;

@end

