//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHShadowedScrollViewController.h"

@class PTHSettingsControlCell;

@interface PTHTweetbotDisplaySettingsController : PTHShadowedScrollViewController
{
    PTHSettingsControlCell *_selectedFontCell;
    PTHSettingsControlCell *_selectedNameCell;
    PTHSettingsControlCell *_selectedDateCell;
    PTHSettingsControlCell *_selectedNewTweetsBarCell;
}

+ (id)nameForNewTweetsBarType:(int)arg1;
+ (id)nameForDateFormatType:(int)arg1;
+ (id)nameForDisplayNameType:(int)arg1;
+ (id)nameForFontSizeType:(int)arg1;
@property(retain, nonatomic) PTHSettingsControlCell *selectedNewTweetsBarCell; // @synthesize selectedNewTweetsBarCell=_selectedNewTweetsBarCell;
@property(retain, nonatomic) PTHSettingsControlCell *selectedDateCell; // @synthesize selectedDateCell=_selectedDateCell;
@property(retain, nonatomic) PTHSettingsControlCell *selectedNameCell; // @synthesize selectedNameCell=_selectedNameCell;
@property(retain, nonatomic) PTHSettingsControlCell *selectedFontCell; // @synthesize selectedFontCell=_selectedFontCell;
- (void)dealloc;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)_selectedNewTweetsBarCell:(id)arg1;
- (void)_selectedDateCell:(id)arg1;
- (void)_selectedNameCell:(id)arg1;
- (void)_selectedFontCell:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

