//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class PTHAttributedLabel, PTHGradientView, PTHSmartifyController, PTHTweetbotPostDraft, PTHTweetbotPostGeoButton, PTHTweetbotPostToolbarView, UITextView;

@interface PTHTweetbotPostPhoneView : UIView <UITextViewDelegate>
{
    struct CGRect _keyboardFrame;
    BOOL _keyboardVisible;
    PTHGradientView *_shadowView;
    PTHGradientView *_keyboardBackgroundView;
    PTHSmartifyController *_smartifyController;
    UIView *_replyBackgroundView;
    PTHAttributedLabel *_replyLabel;
    BOOL _animating;
    BOOL _geoButtonHidden;
    BOOL _keyboardFirstTime;
    UITextView *_textView;
    PTHTweetbotPostGeoButton *_geoButton;
    PTHTweetbotPostToolbarView *_postToolbarView;
    PTHTweetbotPostDraft *_postDraft;
    id <UITextViewDelegate> _delegate;
}

@property(nonatomic) id <UITextViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PTHTweetbotPostDraft *postDraft; // @synthesize postDraft=_postDraft;
@property(readonly, nonatomic) PTHTweetbotPostToolbarView *postToolbarView; // @synthesize postToolbarView=_postToolbarView;
@property(readonly, nonatomic) PTHTweetbotPostGeoButton *geoButton; // @synthesize geoButton=_geoButton;
@property(readonly, nonatomic) UITextView *textView; // @synthesize textView=_textView;
- (void)dealloc;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)toggleSmartify:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)layoutSubviews;
- (void)keyboardDidChange:(id)arg1;
- (void)setGEOTitle:(id)arg1 buttonState:(int)arg2 animated:(BOOL)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

