//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotService.h"

@interface PTHTweetbotNoneService : PTHTweetbotService
{
}

+ (BOOL)canUploadText;
+ (BOOL)canUploadMovies;
+ (BOOL)canUploadImages;
+ (unsigned int)maxUploadCount;
+ (BOOL)verifyWithAccount:(id)arg1;
+ (id)title;

@end

