//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PTHGradientView, UIImageView;

@interface PTHTweetbotBackgroundView : UIView
{
    UIImageView *_imageView;
    PTHGradientView *_topShadowView;
    PTHGradientView *_bottomShadowView;
    float _bottomShadowOffset;
    float _topShadowOffset;
}

@property(nonatomic) float topShadowOffset; // @synthesize topShadowOffset=_topShadowOffset;
@property(nonatomic) float bottomShadowOffset; // @synthesize bottomShadowOffset=_bottomShadowOffset;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

