//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, PTHTweetbotListsCursor, PTHTweetbotUser, UIBarButtonItem, UITableView, UIView;

@interface PTHTweetbotUserListsController : PTHViewController <UITableViewDataSource, UITableViewDelegate>
{
    PTHTweetbotUser *_user;
    UITableView *_tableView;
    UIBarButtonItem *_editBarButtonItem;
    UIBarButtonItem *_doneBarButtonItem;
    UIBarButtonItem *_backBarButtonItem;
    PTHTweetbotListsCursor *_listsCursor;
    NSMutableArray *_statusArray;
    NSMutableArray *_publicLists;
    NSMutableArray *_privateLists;
    NSMutableArray *_subscribedLists;
    UIView *_privateListsHeader;
    UIView *_publicListsHeader;
    UIView *_subscribedListsHeader;
}

@property(readonly, retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)_updateLists;
- (void)_updateEmpty;
- (void)_updateCells;
- (int)_positionAtIndexPath:(id)arg1;
- (id)_listAtIndexPath:(id)arg1;
- (void)viewMode;
- (void)editMode;
- (void)addList:(id)arg1;
- (void)loadView;
- (id)initWithTweetbotUser:(id)arg1;

@end

