//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHShadowedScrollViewController.h"

@class NSArray, NSString, PTHSettingsControlCell, PTHSwitchButton, PTHTweetbotAccount;

@interface PTHTweetbotServicesSettingsController : PTHShadowedScrollViewController
{
    PTHTweetbotAccount *_account;
    NSArray *_serviceClasses;
    PTHSwitchButton *_showMarkerButton;
    NSString *_currentServiceKey;
    PTHSettingsControlCell *_selectedCell;
    NSString *_descriptionTitle;
}

@property(copy, nonatomic) NSString *descriptionTitle; // @synthesize descriptionTitle=_descriptionTitle;
@property(retain, nonatomic) PTHSettingsControlCell *selectedCell; // @synthesize selectedCell=_selectedCell;
@property(retain, nonatomic) NSString *currentServiceKey; // @synthesize currentServiceKey=_currentServiceKey;
- (void)dealloc;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)changeShowMarker:(id)arg1;
- (void)_selectedCell:(id)arg1;
@property(nonatomic) Class currentServiceClass;
- (void)loadView;
- (id)initWithAccount:(id)arg1 serviceClasses:(id)arg2;

@end

