//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursor.h"

@class PTHTweetbotSuggestedCategory;

@interface PTHTweetbotSuggestedCategoryUsersCursor : PTHTweetbotCursor
{
    PTHTweetbotSuggestedCategory *_suggestedCategory;
}

+ (Class)itemClass;
- (void)dealloc;
- (id)itemsArrayFromResponse:(id)arg1;
- (BOOL)needsSort;
- (id)requestURLString;
- (id)uniqueID;
- (id)initWithSuggestedCategory:(id)arg1;

@end

