//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHHitInsetButton.h"

@class PTHBarItem;

@interface PTHToolbarItemView : PTHHitInsetButton
{
    PTHBarItem *_item;
}

@property(readonly, retain, nonatomic) PTHBarItem *item; // @synthesize item=_item;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithBarItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

