//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "MKMapViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class MKMapView, MKPlacemark, NSString;

@interface PTHTweetbotMapViewController : PTHViewController <MKMapViewDelegate, UIGestureRecognizerDelegate>
{
    MKMapView *_mapView;
    BOOL _hasCoordinate;
    CDStruct_feeb6407 _coordinateRegion;
    MKPlacemark *_placemark;
    NSString *_locationName;
}

@property(readonly, retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (void)dealloc;
- (void)viewDidUnload;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)modalCancelButtonTitle;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)_share:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (id)initWithCoordinateRegion:(CDStruct_feeb6407)arg1 title:(id)arg2;
- (id)initWithPlace:(id)arg1;
- (id)initWithLocationName:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

