//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PTHTweetbotNoticeController : NSObject
{
}

+ (void)endQueuingNotices;
+ (void)beginQueuingNotices;
+ (void)playError;
+ (void)playSuccess;
+ (void)showNotificationNotice:(id)arg1 message:(id)arg2;
+ (void)showSuccessNotice:(id)arg1 message:(id)arg2;
+ (void)showErrorNotice:(id)arg1 message:(id)arg2;
+ (void)showNotificationNotice:(id)arg1 message:(id)arg2 soundNamed:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)showSuccessNotice:(id)arg1 message:(id)arg2 soundNamed:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)showErrorNotice:(id)arg1 message:(id)arg2 soundNamed:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)_showNotice:(id)arg1 message:(id)arg2 type:(int)arg3 soundNamed:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (void)__showNotice:(id)arg1 message:(id)arg2 type:(int)arg3 soundNamed:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (void)_dismiss;
+ (void)initialize;

@end

