//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PTHSoundEffect, UIImageView, UILabel, UIWindow;

@interface PTHWaitingController : NSObject
{
    UIImageView *_backgroundView;
    UIImageView *_waitingView;
    UIImageView *_doneView;
    UILabel *_messageLabel;
    UIWindow *_window;
    UIWindow *_oldKeyWindow;
    PTHSoundEffect *_waitingDoneSound;
}

- (void)dealloc;
- (void)hide:(BOOL)arg1;
- (void)_cleanupHide:(id)arg1 finished:(id)arg2 window:(id)arg3;
- (void)show:(BOOL)arg1;
- (void)hide;
- (void)show;
@property(copy, nonatomic) NSString *message;
@property(nonatomic) BOOL waiting;
- (id)init;

@end

