//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@interface UIControl (PTHUIControlCategory)
+ (void)playClick;
+ (void)deselectAll:(id)arg1;
- (void)playClick;
- (void)removeClickSound;
- (void)addClickSound;
- (void)removeSound:(id)arg1;
- (void)addSound:(id)arg1;
- (void)removeBlockTarget:(id)arg1 forControlEvents:(unsigned int)arg2;
- (id)addBlockTargetForControlEvents:(unsigned int)arg1 block:(CDUnknownBlockType)arg2;
- (id)_blockTargetArray;
@end

