//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PTHTweetbotControllerCategory)
- (void)addBackToAccountsBarButtonItem:(int)arg1;
- (void)handleTweetbotURLFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 url:(id)arg4 forAccount:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)showListOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 list:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showFavoriteLongOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showRetweetLongOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showRetweetOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showReplyOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 user:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showDirectMessageOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 directMessage:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showProtectedError:(CDUnknownBlockType)arg1;
- (void)showStatusLongActionOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showStatusShareOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showStatusActionOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showBlockOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 user:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showUserOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 user:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showStockOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 stock:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showHashtagOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 hashtag:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showEntityOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 entity:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)showFilterOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 filter:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)runModalMentionToUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalReplyToFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 status:(id)arg4 text:(id)arg5 cursorPosition:(int)arg6 completion:(CDUnknownBlockType)arg7;
- (void)pushDirectMessageToUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalPostWithAccount:(id)arg1 text:(id)arg2 cursorPosition:(int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)runModalPostWithDraft:(id)arg1 cursorPosition:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)pushEntityFromRect:(struct CGRect)arg1 inView:(id)arg2 entity:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)newControllerForEntity:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)newControllerForTwitterURL:(id)arg1 withAccount:(id)arg2;
- (void)pushStatusDetail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalListDetail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)pushListDetail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalStatusDetail:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)pushQuery:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)runModalQuery:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showURLOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 url:(id)arg4 status:(id)arg5 withTitle:(id)arg6 completion:(CDUnknownBlockType)arg7;
- (void)showURLOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 url:(id)arg4 account:(id)arg5 withTitle:(id)arg6 completion:(CDUnknownBlockType)arg7;
- (void)_showURLOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned int)arg3 url:(id)arg4 status:(id)arg5 account:(id)arg6 withTitle:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (void)runModalURL:(id)arg1 forStatus:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)runModalURL:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)pushURL:(id)arg1 forStatus:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)pushURL:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)runModalUserProfile:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)pushUserProfile:(id)arg1 completion:(CDUnknownBlockType)arg2;
@end

