//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PTHUIViewControllerCategory)
@property(readonly, nonatomic) BOOL isVisible;
- (CDUnknownBlockType)modalSheetStopBlock;
- (void)setModalSheetStopBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UIViewController *modalSheetController;
- (void)stopModalSheetWithCode:(int)arg1;
- (void)runModalSheetController:(id)arg1 modalBlock:(CDUnknownBlockType)arg2;
@property(nonatomic) BOOL globalRotationDisabled;
- (id)sheetHideSoundEffect;
- (id)sheetShowSoundEffect;
- (id)newSheetOverlayView:(struct CGRect)arg1;
@end

