//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PTHTweetbotControllerActionCategory)
+ (void)_offlineBookmark:(id)arg1;
+ (void)_offlineUnfavorite:(id)arg1;
+ (void)_offlineFavorite:(id)arg1;
- (void)runModalEmailItems:(id)arg1 subject:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)runModalEmail:(id)arg1 body:(id)arg2 isHTML:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)runModalPostToStorify:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalFavstarTOTD:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalTranslateText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)browserGoogleTranslate:(id)arg1;
- (void)runModalBingTranslateText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalGoogleTranslateText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runModalHashtagDefinition:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)bookmarkURL:(id)arg1 account:(id)arg2 status:(id)arg3 title:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)unfavoriteStatus:(id)arg1 showSuccess:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)favoriteStatus:(id)arg1 showSuccess:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)unfollowUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)followUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)authenticate:(id)arg1 completion:(CDUnknownBlockType)arg2;
@end

