//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALAssetRepresentation.h"

@interface ALAssetRepresentation (TFNAdditions)
- (BOOL)tfn_streamToFile:(id)arg1;
- (BOOL)tfn_isAnimated;
- (BOOL)_readBytes:(out void *)arg1 pos:(inout long long *)arg2 length:(unsigned long)arg3;
- (id)tfn_filteredImage;
@end

