//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@interface AlertViewHelper : NSObject <UIAlertViewDelegate>
{
    CDUnknownBlockType _block;
    id _holdInMemory;
}

@property(retain, nonatomic) id holdInMemory; // @synthesize holdInMemory=_holdInMemory;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)releaseWhenDone;

@end

