//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface CLSIcon : NSObject
{
    NSData *_data;
    NSString *_dataHash;
    struct CGSize _size;
    BOOL _prerendered;
}

+ (BOOL)isWithinMaxSurfaceAreaWithImage:(id)arg1;
@property(readonly, nonatomic) BOOL prerendered; // @synthesize prerendered=_prerendered;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) NSString *dataHash; // @synthesize dataHash=_dataHash;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (BOOL)largerThanSize:(struct CGSize)arg1;
@property(readonly, nonatomic) BOOL isWithinMaxSurfaceArea;
@property(readonly, nonatomic) float surfaceArea;
- (id)initWithPNGImageAtPath:(id)arg1 size:(struct CGSize)arg2 prerendered:(BOOL)arg3;
- (id)initWithData:(id)arg1 size:(struct CGSize)arg2;
- (id)initWithData:(id)arg1 size:(struct CGSize)arg2 prerendered:(BOOL)arg3;
- (id)initWithData:(id)arg1 dataHash:(id)arg2 size:(struct CGSize)arg3 prerendered:(BOOL)arg4;
- (id)init;
- (void)dealloc;

@end

