//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLSCrashFile, CLSSDKController, CLSSettings;

@protocol CLSSDKControllerDelegate <NSObject>
- (void)controller:(CLSSDKController *)arg1 collectProcesses:(BOOL)arg2;
- (void)controller:(CLSSDKController *)arg1 willProcessFile:(CLSCrashFile *)arg2;
- (void)controllerCompletedSubmissions:(CLSSDKController *)arg1;

@optional
- (void)controllerDidLoadSettings:(CLSSettings *)arg1;
@end

