//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TweetieSignUpCaptchaViewController, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface CustomCaptchaHeader : UIView
{
    UIActivityIndicatorView *spinner;
    TweetieSignUpCaptchaViewController *controller;
}

@property(retain, nonatomic) TweetieSignUpCaptchaViewController *controller; // @synthesize controller;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

