//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GLKViewControllerDelegate.h"
#import "GLKViewDelegate.h"

@class Filter, FilterRenderer, GLKView, GLKViewController;

@interface FilterVideoView : UIView <GLKViewDelegate, GLKViewControllerDelegate>
{
    struct __CVOpenGLESTextureCache *_cvTextureCache;
    FilterRenderer *_filterRenderer;
    GLKView *_glView;
    GLKViewController *_glController;
    unsigned int _texture;
    BOOL _flipX;
    Filter *_filter;
}

@property(retain, nonatomic) Filter *filter; // @synthesize filter=_filter;
- (void).cxx_destruct;
- (void)glkViewControllerUpdate:(id)arg1;
- (void)glkView:(id)arg1 drawInRect:(struct CGRect)arg2;
- (void)setImageBuffer:(struct __CVBuffer *)arg1 flipX:(BOOL)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 filterRenderer:(id)arg2;

@end

