//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FilterContext, FilterRenderer, UIImage;

@interface FilterPreview : NSObject
{
    FilterRenderer *_filterRenderer;
    unsigned int _texture;
    struct CGSize _textureSize;
    BOOL _activeAutoLevel;
    BOOL _textureUpdatePending;
    BOOL _autoLevel;
    UIImage *_image;
    UIImage *_modifiedImage;
    int _orientation;
    struct CGSize _size;
}

+ (struct CGSize)computePreviewSize:(struct CGSize)arg1 naturalSize:(struct CGSize)arg2 cropToFill:(BOOL)arg3;
+ (id)rescaleImage:(id)arg1 imageSize:(struct CGSize)arg2;
@property(nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(nonatomic) BOOL autoLevel; // @synthesize autoLevel=_autoLevel;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly) UIImage *modifiedImage; // @synthesize modifiedImage=_modifiedImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)_updateTexture:(id)arg1;
- (struct CGSize)computePreviewTextureSize:(int)arg1;
- (void)renderFilter:(id)arg1 view:(id)arg2 size:(struct CGSize)arg3 rotation:(float)arg4 shaderParam:(float)arg5 vignetteParam:(float)arg6;
- (void)update;
@property(readonly) FilterContext *context;
- (id)createPreviewViewWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFilterRenderer:(id)arg1;

@end

