//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (TFNAdditions)
+ (id)arrayByConcatenatingArrays:(id)arg1;
- (id)tfn_firstObject;
- (BOOL)tfn_areAllObjectsKindOfClass:(Class)arg1;
- (BOOL)tfn_doAnyObjectsPassTest:(CDUnknownBlockType)arg1;
- (BOOL)tfn_doAllObjectsPassTest:(CDUnknownBlockType)arg1;
- (id)tfn_flattenedArray;
- (id)tfn_arrayByRemovingInvalidPropertyListObjects;
- (id)arrayByReplacingFirstOccurrenceOfObject:(id)arg1 withObject:(id)arg2;
- (void)tfn_diff:(id)arg1 willAdd:(id *)arg2 willRemove:(id *)arg3;
- (id)tfn_slice:(struct _NSRange)arg1;
- (BOOL)tfn_containsStringIgnoringCase:(id)arg1;
- (BOOL)tfn_isSubsetOfArray:(id)arg1;
- (id)reversedArray;
- (id)subarrayWithAtMostFromEnd:(int)arg1;
- (id)subarrayWithAtMost:(int)arg1;
- (BOOL)hasCommonObjectWithArray:(id)arg1;
- (id)arrayByRemovingDuplicates;
- (id)reverseSortedArray;
- (id)sortedArray;
- (void)applyFunction:(CDUnknownFunctionPointerType)arg1 context:(void *)arg2;
- (void)applyBlock:(CDUnknownBlockType)arg1;
- (void)apply:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (void)apply:(SEL)arg1 withObject:(id)arg2;
- (void)apply:(SEL)arg1;
- (id)filterWithBlock:(CDUnknownBlockType)arg1;
- (id)filter:(SEL)arg1 withObject:(id)arg2;
- (id)filter:(SEL)arg1;
- (id)mapFunction:(CDUnknownFunctionPointerType)arg1 context:(void *)arg2;
- (id)mapWithBlock:(CDUnknownBlockType)arg1;
- (id)map:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)map:(SEL)arg1 withObject:(id)arg2;
- (id)map:(SEL)arg1;
- (id)indexSafeObjectAtIndex:(unsigned int)arg1;
- (double)doubleAtIndex:(int)arg1;
- (float)floatAtIndex:(int)arg1;
- (long long)longLongAtIndex:(int)arg1;
- (int)integerAtIndex:(int)arg1;
- (int)intAtIndex:(int)arg1;
- (BOOL)boolAtIndex:(int)arg1;
- (id)numberAtIndex:(int)arg1;
- (id)dictionaryAtIndex:(int)arg1;
- (id)arrayAtIndex:(int)arg1;
- (id)dataAtIndex:(int)arg1;
- (id)stringAtIndex:(int)arg1;
@end

