//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (TFNAdditions)
+ (CDStruct_64709a0b)tfn_mainBundleVersion;
- (CDStruct_64709a0b)tfn_bundleVersion;
@end

