//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (TFNAdditions)
+ (id)tfn_abbreviatedCount:(int)arg1 withLimit:(int)arg2 account:(id)arg3;
+ (id)GUID;
- (id)tfn_asFileNameWithExtension:(id)arg1;
- (id)tfn_asFileName;
- (struct _NSRange)rangeOfCharactersFromSet:(id)arg1 options:(unsigned int)arg2 range:(struct _NSRange)arg3;
- (struct _NSRange)rangeOfCharactersFromSet:(id)arg1 options:(unsigned int)arg2;
- (struct _NSRange)rangeOfCharactersFromSet:(id)arg1;
- (id)stringValue;
- (id)stringByTrimmingLastSlash;
- (id)stringByTrimmingTrailingWhitespace;
- (id)stringByTrimmingLeadingWhitespace;
- (id)stringByRemovingHashSign;
- (int)hexIntegerValue;
- (BOOL)containsOnlyHexNumbers;
- (BOOL)containsOnlyNumbers;
- (int)lengthOfLastCharacter;
- (int)lineBreakModeForFormatString;
- (id)tfn_dateValueFromHTTPDate;
- (id)dateValueFromHTTPLikeDate;
- (id)tfn_URLDecodedString:(BOOL)arg1;
- (id)tfn_URLSegmentEncodedString;
- (id)tfn_URLEncodedString;
- (id)accessibilityStringWithTwitterSymbols;
- (id)stringByStrippingOuterQuotationMarks;
- (id)stringByEscapingXMLEntities;
- (BOOL)tfn_fuzzyPrefixMatch:(id)arg1;
- (int)tfn_editDistance:(id)arg1;
- (BOOL)startsWithAllTokensFromPartialsSearchString:(id)arg1;
- (BOOL)matchesPartialsSearchString:(id)arg1;
- (BOOL)startsWithSubstringIgnoringCase:(id)arg1;
- (BOOL)containsSubstringIgnoringCase:(id)arg1;
- (BOOL)containsSubstring:(id)arg1;
- (id)tfn_dictionaryFromParams;
- (id)tfn_UTF8String;
- (id)tfn_sha1Digest;
- (id)base64EncodedString;
@end

