//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (TFNDownload)
+ (id)tfn_downloadFileInDirectory:(id)arg1 forURL:(id)arg2;
- (id)tfn_processedObjectCacheKeyForKey:(id)arg1;
- (id)tfn_downloadFileInDirectory:(id)arg1;
@end

