//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (TFNInternational)
- (id)tfn_stringByRemovingCrashingSequences;
- (BOOL)tfn_shouldBeRenderedFromRight;
- (id)tfn_stringByRemovingAllDirectionMarks;
- (id)tfn_stringByAddingDirectionMarks;
- (BOOL)plainTextShouldBeRenderedFromRight;
- (BOOL)compositionShouldBeRenderedFromRight;
- (BOOL)containsRTLCharacters;
@end

