//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSUserDefaults.h"

@interface NSUserDefaults (TFNAdditions)
- (void)tfn_removeValueDidChangeTarget:(id)arg1 selector:(SEL)arg2 forKey:(id)arg3;
- (void)tfn_addValueDidChangeTarget:(id)arg1 selector:(SEL)arg2 forKey:(id)arg3;
- (id)_KVOObserver:(BOOL)arg1;
@end

