//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface SPDYSocketReadOp : NSObject
{
    NSMutableData *_buffer;
    unsigned int _bytesRead;
    unsigned int _startOffset;
    unsigned int _maxLength;
    unsigned int _fixedLength;
    unsigned int _originalBufferLength;
    double _timeout;
    _Bool _bufferOwner;
    long _tag;
}

- (void).cxx_destruct;
- (unsigned int)safeReadLength;
- (id)initWithData:(id)arg1 startOffset:(unsigned int)arg2 maxLength:(unsigned int)arg3 timeout:(double)arg4 fixedLength:(unsigned int)arg5 tag:(long)arg6;

@end

