//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, UIImage, UIImageView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface T1ActivityPartialExplanationFooterView : UIControl
{
    UILabel *_label;
    UIImageView *_iconImageView;
    UIImageView *_disclosureIcon;
    UIView *_highlightView;
    NSString *_text;
    UIImage *_image;
}

@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (CDStruct_d917fa49)_computedMetricsForRect:(struct CGRect)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

