//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

#import "TFNTwitterAuthenticated.h"

@class NSString, T1ActivityComposePlaceholderControl, T1AvatarImageView, TFNTwitterAccount, TFNTwitterActivityItem, TFNTwitterFollowControl, TFNTwitterStatus, TFNTwitterUser, UILabel;

__attribute__((visibility("hidden")))
@interface T1ActivityJoinedTwitterItemCell : TFNTableViewCell <TFNTwitterAuthenticated>
{
    T1AvatarImageView *_avatarView;
    TFNTwitterFollowControl *_followControl;
    UILabel *_messageLabel;
    UILabel *_tweetLabel;
    T1ActivityComposePlaceholderControl *_replyPromptView;
    TFNTwitterAccount *_account;
    TFNTwitterActivityItem *_activityItem;
}

+ (BOOL)accepts:(id)arg1;
@property(retain, nonatomic) TFNTwitterActivityItem *activityItem; // @synthesize activityItem=_activityItem;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (CDStruct_0b25e1d6)_computedMetricsForRect:(struct CGRect)arg1;
- (void)_touchPrompt:(id)arg1;
@property(readonly, nonatomic) NSString *replyPrompt;
@property(readonly, nonatomic) TFNTwitterStatus *status;
@property(readonly, nonatomic) TFNTwitterUser *user;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

