//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1ActivityFeaturedItemCell.h"

#import "TFNTwitterAuthenticated.h"

@class T1ActivityPartialComposeFooterView, T1ActivityPartialUserBioView, TFNTwitterAccount, UILabel;

__attribute__((visibility("hidden")))
@interface T1ActivityFeaturedFollowItemCell : T1ActivityFeaturedItemCell <TFNTwitterAuthenticated>
{
    T1ActivityPartialUserBioView *_bioView;
    T1ActivityPartialComposeFooterView *_composeFooterView;
    UILabel *_footerLabel;
    TFNTwitterAccount *_account;
}

+ (BOOL)accepts:(id)arg1;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (BOOL)_adjustEditingControlFrameInView:(id)arg1;
- (void)setActivityItem:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

