//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIColor, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface T1ActivityComposePlaceholderControl : UIButton
{
    UILabel *_label;
    UIImageView *_imageView;
    BOOL _usesAlternativeStyle;
    NSString *_text;
}

@property(nonatomic) BOOL usesAlternativeStyle; // @synthesize usesAlternativeStyle=_usesAlternativeStyle;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) UIColor *backgroundColorForCurrentStyle;
- (void)setHighlighted:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

