//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "TFNTwitterAuthenticated.h"

@class T1StatusTableRowAdapter, T1UserOrRecommendationTableRowAdapter, TFNTwitterAccount, TFNTwitterActivityItem, TFNTwitterScribeContext;

__attribute__((visibility("hidden")))
@interface T1ActivityDetailsViewController : TFNItemsDataViewController <TFNTwitterAuthenticated>
{
    TFNTwitterAccount *_account;
    TFNTwitterActivityItem *_activityItem;
    TFNTwitterScribeContext *_sourceScribeContext;
    T1UserOrRecommendationTableRowAdapter *_userTableRowAdapter;
    T1StatusTableRowAdapter *_statusAdapter;
}

+ (id)scribePageForActivityItem:(id)arg1;
@property(retain, nonatomic) T1StatusTableRowAdapter *statusAdapter; // @synthesize statusAdapter=_statusAdapter;
@property(readonly, nonatomic) T1UserOrRecommendationTableRowAdapter *userTableRowAdapter; // @synthesize userTableRowAdapter=_userTableRowAdapter;
@property(retain, nonatomic) TFNTwitterScribeContext *sourceScribeContext; // @synthesize sourceScribeContext=_sourceScribeContext;
@property(retain, nonatomic) TFNTwitterActivityItem *activityItem; // @synthesize activityItem=_activityItem;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)prefersStatusBarHidden;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)_updateSections;
- (id)_activityDetailsViewSubtitle;
- (id)_activityDetailsViewTitle;
- (id)scribeSection;
- (id)scribePage;
- (void)scribeImpressionWithParameters:(id)arg1;
- (id)scribeContext;
- (id)scribe;
- (id)init;

@end

