//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface T1AddAccountAdvancedViewController : TFNItemsDataViewController
{
    id <T1AddAccountAdvancedViewControllerDelegate> _delegate;
    NSString *_apiEndpointText;
    NSString *_configurationEndpointText;
}

@property(copy, nonatomic) NSString *configurationEndpointText; // @synthesize configurationEndpointText=_configurationEndpointText;
@property(copy, nonatomic) NSString *apiEndpointText; // @synthesize apiEndpointText=_apiEndpointText;
@property(nonatomic) __weak id <T1AddAccountAdvancedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)configurationEndpointTextDidChange:(id)arg1;
- (void)apiEndpointTextDidChange:(id)arg1;
- (struct CGSize)contentSizeForViewInPopover;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_updateSections;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;

@end

