//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "MKMapViewDelegate.h"
#import "TFNTwitterAuthenticated.h"
#import "UITextFieldDelegate.h"

@class CLGeocoder, CLLocation, NSString, T1AddPlaceMapTableRowAdapter, TFNBlockDataViewAdapter, TFNTimer, TFNTwitterAccount, UITextField;

__attribute__((visibility("hidden")))
@interface T1AddPlaceViewController : TFNItemsDataViewController <TFNTwitterAuthenticated, UITextFieldDelegate, MKMapViewDelegate>
{
    TFNTwitterAccount *_account;
    NSString *_placeName;
    UITextField *_nameField;
    UITextField *_usernameField;
    UITextField *_categoryField;
    UITextField *_addressField;
    T1AddPlaceMapTableRowAdapter *_mapAdapter;
    TFNBlockDataViewAdapter *_mapDescriptionItem;
    CLGeocoder *_geocoder;
    TFNTimer *_geocodeTimer;
    CLLocation *_location;
}

@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) TFNTimer *geocodeTimer; // @synthesize geocodeTimer=_geocodeTimer;
@property(retain, nonatomic) CLGeocoder *geocoder; // @synthesize geocoder=_geocoder;
@property(retain, nonatomic) TFNBlockDataViewAdapter *mapDescriptionItem; // @synthesize mapDescriptionItem=_mapDescriptionItem;
@property(retain, nonatomic) T1AddPlaceMapTableRowAdapter *mapAdapter; // @synthesize mapAdapter=_mapAdapter;
@property(retain, nonatomic) UITextField *addressField; // @synthesize addressField=_addressField;
@property(retain, nonatomic) UITextField *categoryField; // @synthesize categoryField=_categoryField;
@property(retain, nonatomic) UITextField *usernameField; // @synthesize usernameField=_usernameField;
@property(retain, nonatomic) UITextField *nameField; // @synthesize nameField=_nameField;
@property(retain, nonatomic) NSString *placeName; // @synthesize placeName=_placeName;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)dealloc;
- (float)_calculateMapHeight;
- (void)_handleGeocodeResponse:(id)arg1;
- (void)_geocode;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)didSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (void)_updateSections;
- (void)viewDidFullyAppear:(BOOL)arg1;
- (id)initWithAccount:(id)arg1;
- (id)init;

@end

