//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class T1AmbientNotificationTitleView;

@protocol T1AmbientNotificationPresenting <NSObject>
- (void)setNotificationTitleView:(T1AmbientNotificationTitleView *)arg1;
- (void)scribeDismissForAmbientNotificationHost:(id <T1AmbientNotificationViewControllerDelegate>)arg1;
- (void)scribeOpenForAmbientNotificationHost:(id <T1AmbientNotificationViewControllerDelegate>)arg1;
- (float)heightForAmbientNotificationHost:(id <T1AmbientNotificationViewControllerDelegate>)arg1;
- (void)titleTapActionFromAmbientNotificationHost:(id <T1AmbientNotificationViewControllerDelegate>)arg1;
@end

