//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNTwitterPushNotificationRoute.h"

@class NSString, UIViewController;

__attribute__((visibility("hidden")))
@interface T1BasicPushRoute : NSObject <TFNTwitterPushNotificationRoute>
{
}

- (id)ambientViewControllerForPayload:(id)arg1;
- (id)formattedSenderNameForPayload:(id)arg1;
- (id)ambientMessageForPayload:(id)arg1;
- (id)ambientIconForPayload:(id)arg1;
- (id)scribeParametersForPayload:(id)arg1;
- (id)scribeElementForPayload:(id)arg1;
- (id)ambientBackgroundColorForPayload:(id)arg1;
- (void)routePayload:(id)arg1 context:(int)arg2;
- (void)willRoutePushPayload:(id)arg1 context:(int)arg2;
- (void)willRoutePayload:(id)arg1;
- (void)tryRouteByURL:(id)arg1 context:(int)arg2 navigationContext:(id)arg3 otherwise:(CDUnknownBlockType)arg4;
- (void)tryRouteByURL:(id)arg1 context:(int)arg2 otherwise:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) id <T1AmbientNotificationViewControllerDelegate> ambientHostDelegate;
@property(readonly, nonatomic) UIViewController *currentViewController;
@property(readonly, nonatomic) id <T1AppNavigation> appNavigation;
- (id)ambientNotificationForPayload:(id)arg1;
- (id)t1AmbientNotificationForPayload:(id)arg1;
@property(readonly, nonatomic) NSString *associatedPanelID;
@property(readonly, nonatomic) BOOL notificationIsExpandable;
- (int)ambientPushNotificationBehaviorForPayload:(id)arg1;
- (void)handlePushPayload:(id)arg1 context:(int)arg2;

@end

