//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, T1CardController, TCAction, TCElement, TFNTwitterScribeContext;

@protocol T1CardControllerDelegate <NSObject>
- (TFNTwitterScribeContext *)cardControllerScribeContext:(T1CardController *)arg1;
- (void)cardController:(T1CardController *)arg1 openPlayerURL:(NSString *)arg2;
- (void)cardControllerDidPlayInlineMovie:(T1CardController *)arg1;
- (void)cardController:(T1CardController *)arg1 performAction:(TCAction *)arg2 onElement:(TCElement *)arg3 completion:(void (^)(BOOL))arg4;
- (void)cardControllerNeedsLayout:(T1CardController *)arg1;
- (void)cardControllerIsReady:(T1CardController *)arg1;

@optional
- (void)cardController:(T1CardController *)arg1 playMovieFromElement:(TCElement *)arg2;
- (void)cardController:(T1CardController *)arg1 scribeWithElement:(NSString *)arg2 action:(NSString *)arg3;
@end

