//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TCCardInstanceDelegate.h"

@class NSArray, NSString, TCCardInstance, TFNDownload, TFNTwitterAccount, TFNTwitterStatus;

__attribute__((visibility("hidden")))
@interface T1CardController : NSObject <TCCardInstanceDelegate>
{
    TFNDownload *_plusCardDownload;
    NSString *_compiledCardURLForCache;
    struct {
        unsigned int plusCardDownloaded:1;
        unsigned int showWarnings:1;
        unsigned int showErrors:1;
        unsigned int useCardCache:1;
        unsigned int isForwardCard:1;
    } _cardControllerFlags;
    id <T1CardControllerDelegate> _delegate;
    TCCardInstance *_cardInstance;
    TFNTwitterAccount *_account;
    TFNTwitterStatus *_status;
    NSArray *_warnings;
    NSString *_errorDescription;
}

@property(copy, nonatomic) NSString *errorDescription; // @synthesize errorDescription=_errorDescription;
@property(retain, nonatomic) NSArray *warnings; // @synthesize warnings=_warnings;
@property(readonly, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) TCCardInstance *cardInstance; // @synthesize cardInstance=_cardInstance;
@property(nonatomic) __weak id <T1CardControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)cardInstanceScribeContext:(id)arg1;
- (void)cardInstance:(id)arg1 scribeWithElement:(id)arg2 action:(id)arg3;
- (id)cardInstanceAdditionalParametersForAPIRequest:(id)arg1;
- (id)cardInstanceTwitterAccount:(id)arg1;
- (void)cardInstance:(id)arg1 playMovieFromElement:(id)arg2;
- (void)cardInstance:(id)arg1 openPlayerURL:(id)arg2;
- (void)cardInstanceDidPlayInlineMovie:(id)arg1;
- (float)cardInstance:(id)arg1 adjustedFontSizeForSize:(float)arg2;
- (void)cardInstance:(id)arg1 performAction:(id)arg2 onElement:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)cardInstanceNeedsLayout:(id)arg1;
- (id)cardInstance:(id)arg1 userWithID:(long long)arg2;
- (id)_cardStateCacheKey;
- (id)_cardState;
- (void)_createPlusCardInstanceFromJSON:(id)arg1 error:(id)arg2;
- (void)_createPlusCardInstanceFromData:(id)arg1;
- (void)_plusCardDownloadAndCreationDidFinish;
- (void)_plusCardDownloadDidChange;
- (void)_loadCardInstanceForCard:(id)arg1;
- (void)dispose;
- (void)createForwardCardInstance;
- (void)dealloc;
- (id)initWithAccount:(id)arg1 forStatus:(id)arg2;

@end

