//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol T1ComposeUnderKeyboardViewDelegate <NSObject>
- (void)didSwapToView:(UIView *)arg1 withKey:(NSString *)arg2 animated:(BOOL)arg3;
@end

