//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class T1CoachMarkView;

@protocol T1CoachMarkViewDelegate <NSObject>
- (void)didTapCloseButtonInCoachMarkView:(T1CoachMarkView *)arg1;
- (void)didTapActionButtonInCoachMarkView:(T1CoachMarkView *)arg1;
@end

