//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsTableRowAdapter.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface T1ComposePOIActionTableRowAdapter : TFNItemsTableRowAdapter
{
    int _actionType;
    NSString *_query;
}

+ (id)actionTableRowAdapterWithType:(int)arg1;
@property(copy, nonatomic) NSString *query; // @synthesize query=_query;
@property(nonatomic) int actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;
- (id)_titleFormat;
- (void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

