//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class T1ComposeUnderGeoTableViewController, TFNTwitterPlace;

@protocol T1ComposeUnderGeoTableViewControllerDelegate <NSObject>
- (void)controllerDidDeactivateFullscreenSearch:(T1ComposeUnderGeoTableViewController *)arg1;
- (void)controllerDidActivateFullscreenSearch:(T1ComposeUnderGeoTableViewController *)arg1;
- (void)controllerDidActivateSearch:(T1ComposeUnderGeoTableViewController *)arg1;
- (void)controllerDidDeselectPlace:(T1ComposeUnderGeoTableViewController *)arg1;
- (void)controller:(T1ComposeUnderGeoTableViewController *)arg1 didAutotagPlace:(TFNTwitterPlace *)arg2;
- (void)controller:(T1ComposeUnderGeoTableViewController *)arg1 didSelectPlace:(TFNTwitterPlace *)arg2;
@end

