//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "T1ComposeLockingTableViewController.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSNumberFormatter, T1ComposeLockingTableView, T1ComposePhotoGalleryViewController;

__attribute__((visibility("hidden")))
@interface T1ComposeAlbumPickerViewController : UIViewController <T1ComposeLockingTableViewController, UITableViewDataSource, UITableViewDelegate>
{
    NSArray *_assetGroups;
    T1ComposeLockingTableView *_tableView;
    NSNumberFormatter *_numberFormatter;
    BOOL _showHeader;
    T1ComposePhotoGalleryViewController *_galleryController;
    int _theme;
}

@property(nonatomic) int theme; // @synthesize theme=_theme;
@property(nonatomic) BOOL showHeader; // @synthesize showHeader=_showHeader;
@property(retain, nonatomic) NSArray *assetGroups; // @synthesize assetGroups=_assetGroups;
@property(retain, nonatomic) T1ComposePhotoGalleryViewController *galleryController; // @synthesize galleryController=_galleryController;
- (void).cxx_destruct;
- (id)lockingTableView;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)_applyThemeToCell:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)dealloc;
- (void)_applyTheme;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

