//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

@class NSString, T1AvatarImageView, UILabel;

__attribute__((visibility("hidden")))
@interface T1CustomTimelineTableViewCell : TFNTableViewCell
{
    UILabel *_nameLabel;
    UILabel *_authorLabel;
    UILabel *_descriptionLabel;
    UILabel *_detailsLabel;
    T1AvatarImageView *_avatarImageView;
}

+ (float)heightWithNameText:(id)arg1 withAuthorText:(id)arg2 withDescriptionText:(id)arg3 withDetailText:(id)arg4 withTableWidth:(float)arg5 withContentPadding:(struct UIEdgeInsets)arg6;
@property(retain, nonatomic) T1AvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UILabel *detailsLabel; // @synthesize detailsLabel=_detailsLabel;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *authorLabel; // @synthesize authorLabel=_authorLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)_updateProfileImageWithUser:(id)arg1;
- (void)_avatarImageDidUpdate:(id)arg1;
- (void)fillAvatarWithUser:(id)arg1;
@property(copy, nonatomic) NSString *detailsText;
@property(copy, nonatomic) NSString *descriptionText;
@property(copy, nonatomic) NSString *authorText;
@property(copy, nonatomic) NSString *nameText;
- (void)cleanup;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

