//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "T1CustomTimelineEditViewControllerDelegate.h"
#import "T1CustomTimelineHeaderDelegate.h"
#import "T1TweetContextActionsDelegate.h"
#import "TFNTwitterAuthenticated.h"

@class NSArray, T1CustomTimelineTableRowAdapter, T1StatusTableRowAdapter, TFNBarButtonItem, TFNTwitterAccount, TFNTwitterCustomTimeline, TFNTwitterCustomTimelineStream;

__attribute__((visibility("hidden")))
@interface T1CustomTimelineViewController : TFNItemsDataViewController <TFNTwitterAuthenticated, T1CustomTimelineEditViewControllerDelegate, T1CustomTimelineHeaderDelegate, T1TweetContextActionsDelegate>
{
    NSArray *_sectionIndexTypeMap;
    BOOL _isLayoutSubviewsDone;
    BOOL _restoredPersistedScrollPosition;
    TFNBarButtonItem *_shareBarButtonItem;
    T1CustomTimelineTableRowAdapter *_adapter;
    TFNTwitterAccount *_account;
    TFNTwitterCustomTimeline *_timeline;
    T1StatusTableRowAdapter *_statusAdapter;
    TFNTwitterCustomTimelineStream *_stream;
}

+ (id)_numberForCustomTimelineID:(id)arg1;
@property(retain, nonatomic) TFNTwitterCustomTimelineStream *stream; // @synthesize stream=_stream;
@property(retain, nonatomic) T1StatusTableRowAdapter *statusAdapter; // @synthesize statusAdapter=_statusAdapter;
@property(retain, nonatomic) TFNTwitterCustomTimeline *timeline; // @synthesize timeline=_timeline;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (id)t1_extraTweetContextActionsForStatus:(id)arg1 account:(id)arg2 entityURL:(id)arg3 supportsDismiss:(BOOL)arg4;
- (void)customTimelineEditViewControllerDidDeleteTimeline:(id)arg1;
- (void)customTimelineEditViewController:(id)arg1 didFinishWithTimeline:(id)arg2 isNew:(BOOL)arg3;
- (void)customTimelineHeaderCell:(id)arg1 didTapFollow:(id)arg2;
- (void)_displayErrorBriefly:(id)arg1;
- (void)_shareButtonTapped:(id)arg1;
- (BOOL)_shareButtonIsAvailable;
- (id)_shareBarButtonItem;
- (void)_updateNavigationItem;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)_streamDidUpdateFromAPI:(id)arg1;
- (void)_streamDidUpdate;
- (int)_sectionTypeForSectionIndex:(unsigned int)arg1;
- (unsigned int)_sectionIndexForSectionType:(int)arg1;
- (void)_updateSections;
- (void)_updateTableWithNewMap:(id)arg1;
- (id)_createSectionIndexTypeMap;
- (void)_restorePersistedScrollPosition;
- (void)_persistScrollPosition;
- (id)_scrollPositionUserDefaultsKey;
- (id)autosaveName;
- (void)loadTop;
- (BOOL)isLoadingTop;
- (BOOL)shouldHighlightItem:(id)arg1 atIndexPath:(id)arg2;
- (BOOL)useBlindView;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)prefersStatusBarHidden;
- (void)update;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)_timelineDidUpdate:(id)arg1;
- (BOOL)showsSearchButton;
- (BOOL)showsComposeButton;
- (void)dealloc;
- (id)init;

@end

