//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "TFNTwitterAuthenticated.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class TFNPlaceholderTextView, TFNTwitterAccount, TFNTwitterCustomTimeline, UIBarButtonItem, UITextField;

__attribute__((visibility("hidden")))
@interface T1CustomTimelineEditViewController : TFNItemsDataViewController <TFNTwitterAuthenticated, UITextFieldDelegate, UITextViewDelegate>
{
    int _maxDescriptionLength;
    int _maxNameLength;
    TFNTwitterAccount *_account;
    TFNTwitterCustomTimeline *_timeline;
    id <T1CustomTimelineEditViewControllerDelegate> _delegate;
    UITextField *_nameField;
    TFNPlaceholderTextView *_descriptionTextView;
    UIBarButtonItem *_saveButtonItem;
}

@property(retain, nonatomic) UIBarButtonItem *saveButtonItem; // @synthesize saveButtonItem=_saveButtonItem;
@property(retain, nonatomic) TFNPlaceholderTextView *descriptionTextView; // @synthesize descriptionTextView=_descriptionTextView;
@property(retain, nonatomic) UITextField *nameField; // @synthesize nameField=_nameField;
@property(nonatomic) __weak id <T1CustomTimelineEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterCustomTimeline *timeline; // @synthesize timeline=_timeline;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)_updateMaxFieldLengths;
- (BOOL)_isInEditMode;
- (BOOL)_needsToSaveTimeline;
- (BOOL)_canSaveTimeline;
- (void)_finishWithTimeline:(id)arg1;
- (void)_cancel:(id)arg1;
- (void)_deleteTimeline;
- (void)_promptToDeleteTimeline;
- (void)_save:(id)arg1;
- (BOOL)_validateFields;
- (void)_updateModelFromView;
- (void)_updateViewFromModel;
- (void)_updateSaveButton:(id)arg1;
- (void)_updateSections;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

