//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class UIViewController;

__attribute__((visibility("hidden")))
@interface T1DefaultModalTransitionAnimator : NSObject <UIViewControllerAnimatedTransitioning>
{
    BOOL _dismissing;
    UIViewController *_sourceViewController;
}

@property(nonatomic) BOOL dismissing; // @synthesize dismissing=_dismissing;
@property(nonatomic) __weak UIViewController *sourceViewController; // @synthesize sourceViewController=_sourceViewController;
- (void).cxx_destruct;
- (BOOL)_prefersStatusBarHidden:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)init;

@end

