//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, T1DirectMessageTopUsersViewController, TFNTwitterUser;

@protocol T1DirectMessageTopUsersViewControllerDelegate <NSObject>
- (void)directMessageTopUsersViewController:(T1DirectMessageTopUsersViewController *)arg1 didSelectUser:(TFNTwitterUser *)arg2 atIndexPath:(NSIndexPath *)arg3;

@optional
- (void)directMessageTopUsersViewControllerScrollViewWillBeginDragging:(T1DirectMessageTopUsersViewController *)arg1;
- (void)directMessageTopUsersViewControllerDidSelectImport:(T1DirectMessageTopUsersViewController *)arg1;
@end

