//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface T1DirectMessageConfiguration : NSObject
{
}

+ (BOOL)allowDirectMessageMediaCompose:(id)arg1;
+ (unsigned int)mediaTypeForMessage:(id)arg1 account:(id)arg2;
+ (BOOL)_directMessagesCanDisplayMedia:(id)arg1;
+ (BOOL)_directMessagesCanComposeMedia:(id)arg1;

@end

