//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

@class UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface T1DirectMessageStartAConversationCell : TFNTableViewCell
{
    id <T1DirectMessageStartAConversationCellDelgate> _delegate;
    UILabel *_titleLabel;
    UILabel *_bodyLabel;
    UIButton *_actionButton;
    unsigned int _startAConversationType;
}

+ (id)reuseIdentifier;
+ (float)heightWithType:(unsigned int)arg1 tableWidth:(float)arg2;
@property(nonatomic) unsigned int startAConversationType; // @synthesize startAConversationType=_startAConversationType;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UILabel *bodyLabel; // @synthesize bodyLabel=_bodyLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <T1DirectMessageStartAConversationCellDelgate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_actionButtonPressed;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

