//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol T1DiscoverViewController <NSObject>

@optional
- (void)discoverTabWasSelected:(BOOL)arg1;
- (void)showTrendsAnimated:(BOOL)arg1 withScroll:(BOOL)arg2;
@end

