//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, T1DirectMessageConversationThreadViewController, UIViewController;

@protocol T1DirectMessageConversationThreadViewControllerDelegate <NSObject>
- (void)viewController:(T1DirectMessageConversationThreadViewController *)arg1 needsPresentSelectedUserViewController:(UIViewController *)arg2;
- (void)viewController:(T1DirectMessageConversationThreadViewController *)arg1 needsPresentActiveRangeViewController:(UIViewController *)arg2;
- (void)viewController:(T1DirectMessageConversationThreadViewController *)arg1 didSelectMessages:(NSArray *)arg2 forPerformingAction:(int)arg3;
- (void)viewController:(T1DirectMessageConversationThreadViewController *)arg1 didCopyMessages:(NSArray *)arg2;
@end

