//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1DiscoverTrendsTableRowAdapter.h"

__attribute__((visibility("hidden")))
@interface T1DiscoverTrendsEventTableRowAdapter : T1DiscoverTrendsTableRowAdapter
{
}

- (id)_iconImageForItem:(id)arg1;
- (id)_detailTextForItem:(id)arg1;
- (void)_controller:(id)arg1 didSelectViewMoreOfItem:(id)arg2 indexPath:(id)arg3;

@end

