//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterAuthenticated.h"

@class NSNotification, TFNTwitterDirectMessageConversation;

@protocol T1DirectMessageCurrentConversation <TFNTwitterAuthenticated>
@property(readonly, nonatomic) TFNTwitterDirectMessageConversation *currentConversation;
- (void)directMessagesDidPostErrorNotification:(NSNotification *)arg1;
@end

