//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class T1EventContainerHeaderView;

@protocol T1EventContainerHeaderViewDelegate <NSObject>
- (void)eventContainerHeaderViewDidTapComposeButton:(T1EventContainerHeaderView *)arg1;
- (void)eventContainerHeaderViewDidTapBackButton:(T1EventContainerHeaderView *)arg1;
- (void)eventContainerHeaderViewDidUpdatePreferredSize:(T1EventContainerHeaderView *)arg1;
@end

