//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

@class CAGradientLayer, NSString, TFNDownload, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface T1ExploreTableViewCell : TFNTableViewCell
{
    BOOL _topCell;
    NSString *_imageURL;
    unsigned int _gradientType;
    TFNDownload *_imageDownload;
    CAGradientLayer *_gradientLayer;
    UIImageView *_exploreImageView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
}

+ (float)heightForCellWithTitle:(id)arg1 titleFont:(id)arg2 detail:(id)arg3 detailFont:(id)arg4 forWidth:(float)arg5 contentPadding:(struct UIEdgeInsets)arg6;
@property(readonly, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *exploreImageView; // @synthesize exploreImageView=_exploreImageView;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) TFNDownload *imageDownload; // @synthesize imageDownload=_imageDownload;
@property(nonatomic) unsigned int gradientType; // @synthesize gradientType=_gradientType;
@property(nonatomic, getter=isTopCell) BOOL topCell; // @synthesize topCell=_topCell;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (void)cleanup;
- (void)_imageDownloadDidChange;
- (void)_startDownload;
- (void)layoutSubviews;
- (void)setDetailFont:(id)arg1;
- (void)setDetailText:(id)arg1;
- (void)setTitleFont:(id)arg1;
- (void)setTitleText:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

