//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface T1FiltersCropScrollView : UIScrollView <UIScrollViewDelegate>
{
    UIImageView *_imageView;
    struct CGSize _imageSize;
    struct CGSize _cropRectSize;
    BOOL _square;
    struct CGPoint _contentOffsetBeforeResize;
    struct CGPoint _pointToCenterAfterResize;
    float _scaleToRestoreAfterResize;
    float _minScale;
}

@property(readonly, nonatomic) float minScale; // @synthesize minScale=_minScale;
- (void).cxx_destruct;
- (id)viewForZoomingInScrollView:(id)arg1;
- (void)_centerContent;
- (void)_setMaxMinZoomScalesForCurrentBounds;
- (void)_configureForImageSize:(struct CGSize)arg1;
- (void)setSquare:(BOOL)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setImageView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

