//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "T1DirectMessageTopUsersViewControllerDelegate.h"
#import "T1UsersViewControllerDelegate.h"

@class NSIndexPath, TFNTwitterUser;

@protocol T1FindUsersViewControllerDelegate <T1DirectMessageTopUsersViewControllerDelegate, T1UsersViewControllerDelegate, NSObject>

@optional
- (void)didSelectUser:(TFNTwitterUser *)arg1 atIndexPath:(NSIndexPath *)arg2;
@end

