//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, T1FiltersViewController, T1ProcessedMediaSource;

@protocol T1FiltersViewControllerDelegate <NSObject>
- (void)filtersViewControllerDidCancel:(T1FiltersViewController *)arg1;
- (void)filtersViewController:(T1FiltersViewController *)arg1 didEditImage:(T1ProcessedMediaSource *)arg2;

@optional
- (NSString *)scribeSectionForFiltersViewController:(T1FiltersViewController *)arg1;
@end

