//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1UsersItemsTableViewController.h"

__attribute__((visibility("hidden")))
@interface T1FollowingViewController : T1UsersItemsTableViewController
{
}

- (id)scribeContextForIndexPath:(id)arg1;
- (id)scribeAssociationID;
- (id)scribeSection;
- (id)scribePage;
- (id)_user;
- (void)_streamDidUpdate:(id)arg1;
- (void)update;
- (id)initWithAccount:(id)arg1 user:(id)arg2 showFavoriteFollowButton:(BOOL)arg3;
- (id)initWithAccount:(id)arg1 user:(id)arg2;

@end

