//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1UsersItemsTableViewController.h"

@class T1BadgedTextTableRowAdapter;

__attribute__((visibility("hidden")))
@interface T1FollowersViewController : T1UsersItemsTableViewController
{
    T1BadgedTextTableRowAdapter *_badgeAdapter;
    unsigned int _followerRequestCount;
}

@property(nonatomic) unsigned int followerRequestCount; // @synthesize followerRequestCount=_followerRequestCount;
- (void).cxx_destruct;
- (id)scribeContextForIndexPath:(id)arg1;
- (id)scribeAssociationID;
- (id)scribeSection;
- (id)scribePage;
- (void)_updateFollowerRequestCount;
- (BOOL)_shouldShowFollowerRequests;
- (id)_user;
- (void)_streamDidUpdate:(id)arg1;
- (void)update;
- (void)didSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (id)initWithAccount:(id)arg1 user:(id)arg2;

@end

