//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1UsersViewController.h"

@class NSMutableSet;

__attribute__((visibility("hidden")))
@interface T1FollowerRequestsViewController : T1UsersViewController
{
    NSMutableSet *_acceptedUsers;
}

- (void).cxx_destruct;
- (id)scribePage;
- (id)scribe;
- (void)_didDeclineFollowerRequestFromUser:(id)arg1;
- (void)_didAcceptFollowerRequestFromUser:(id)arg1;
- (id)title;
- (id)noUsersLabel;
- (int)userFollowControlStyleForUser:(id)arg1;
- (void)requestUsers;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)init;

@end

