//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1GenericIntroSectionView.h"

__attribute__((visibility("hidden")))
@interface T1FrontIntroSectionView : T1GenericIntroSectionView
{
}

- (id)textColor;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

