//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsGalleryTableRowAdapter.h"

@class TFNPagedGalleryCellViewCache;

__attribute__((visibility("hidden")))
@interface T1GenericEventGalleryRowAdapter : TFNItemsGalleryTableRowAdapter
{
    int _eventViewStyle;
    TFNPagedGalleryCellViewCache *_pagedGalleryViewCache;
}

@property(retain, nonatomic) TFNPagedGalleryCellViewCache *pagedGalleryViewCache; // @synthesize pagedGalleryViewCache=_pagedGalleryViewCache;
@property(nonatomic) int eventViewStyle; // @synthesize eventViewStyle=_eventViewStyle;
- (void).cxx_destruct;
- (struct UIEdgeInsets)_contentPaddingForGallery:(id)arg1;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (float)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)init;

@end

