//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1HomeTimelineBatteryPerformanceTest.h"

__attribute__((visibility("hidden")))
@interface T1HomeTimelineLaunchBatteryPerformanceTest : T1HomeTimelineBatteryPerformanceTest
{
    double _pauseIntervalBeforeExiting;
}

@property(nonatomic) double pauseIntervalBeforeExiting; // @synthesize pauseIntervalBeforeExiting=_pauseIntervalBeforeExiting;
- (void)startWithHomeTimelineViewController:(id)arg1;
- (void)_exit;
- (void)_restart;
- (id)initWithParameters:(id)arg1;
- (id)init;

@end

