//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TFNToggleButton, TFNTwitterAccount, TFNTwitterStatus, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface T1InlineActionController : NSObject
{
    TFNToggleButton *_inlineActionButton;
    UIImageView *_inlineActionAnimationView;
    UIView *_contentView;
    TFNToggleButton *_inlineActionTextButton;
    BOOL _showActionCount;
    struct UIEdgeInsets _touchInsets;
    int _countForCachedCountText;
    NSString *_cachedCountText;
    NSString *_countTextForCachedCountTextSize;
    struct CGSize _cachedCountTextSize;
    BOOL _hidden;
    CDUnknownBlockType _tapBlock;
    unsigned int _inlineActionType;
    TFNTwitterAccount *_account;
    TFNTwitterStatus *_status;
}

+ (id)_abbreviateInlineCount:(int)arg1 account:(id)arg2;
+ (id)_stringForActionType:(unsigned int)arg1 account:(id)arg2;
+ (id)inlineFeedbackTextForStatus:(id)arg1 feedbackType:(unsigned int)arg2;
+ (int)_countForStatus:(id)arg1 actionType:(unsigned int)arg2 account:(id)arg3;
+ (id)_actionImageForState:(int)arg1 pressed:(int)arg2 inlineActionType:(unsigned int)arg3 account:(id)arg4;
+ (int)_indexOfActionImageForState:(int)arg1 pressed:(int)arg2 inlineActionType:(unsigned int)arg3;
+ (id)defaultInlineActionImageForType:(unsigned int)arg1 account:(id)arg2;
+ (void)_setUpIpadInlineActionExperimentImages;
+ (void)_setUpInlineActionImages;
@property(nonatomic) BOOL showActionCount; // @synthesize showActionCount=_showActionCount;
@property(nonatomic) BOOL hidden; // @synthesize hidden=_hidden;
@property(retain, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(readonly, nonatomic) unsigned int inlineActionType; // @synthesize inlineActionType=_inlineActionType;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)_updateTextColorForLabel;
- (id)_countLabelTextWithInlineActionType:(unsigned int)arg1 account:(id)arg2;
- (void)removeViewsFromSuperview;
- (int)_actionStateForStatus:(id)arg1;
- (void)_inlineActionTapAction;
- (BOOL)isEnabled;
- (void)updateInlineActionWithStatusChanged:(BOOL)arg1 options:(unsigned int)arg2;
- (void)beginAnimation;
- (void)layoutViews:(struct CGRect)arg1 cellLayout:(id)arg2 contentRect:(struct CGRect)arg3;
@property(readonly, nonatomic) struct CGRect iconFrame;
- (void)dealloc;
- (id)initAccessibleActionControllerWithInlineActionType:(unsigned int)arg1 account:(id)arg2;
- (id)initWithInlineActionType:(unsigned int)arg1 account:(id)arg2 contentView:(id)arg3 touchInsets:(struct UIEdgeInsets)arg4 showActionCount:(BOOL)arg5 options:(unsigned int)arg6;

@end

