//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CALayer, CAShapeLayer, UIColor;

__attribute__((visibility("hidden")))
@interface T1InlineActionPromptNotchContainerView : UIView
{
    UIView *_clippingView;
    UIView *_contentView;
    CAShapeLayer *_borderNotch;
    CALayer *_borderTopLeft;
    CALayer *_borderTopRight;
    CALayer *_borderBottom;
    CALayer *_clippingLayer;
    CAShapeLayer *_notchLayer;
    CALayer *_contentBackgroundLayer;
    struct CGSize _notchSize;
    struct CGSize _renderdNotchSize;
    BOOL _collapsed;
    float _notchPosition;
    UIColor *_borderColor;
}

@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic, getter=isCollapsed) BOOL collapsed; // @synthesize collapsed=_collapsed;
@property(nonatomic) float notchPosition; // @synthesize notchPosition=_notchPosition;
- (void).cxx_destruct;
- (void)layoutSubviews;
@property(retain, nonatomic) UIColor *contentBackgroundColor;
@property(nonatomic) float notchHeight;
- (id)initWithFrame:(struct CGRect)arg1;

@end

