//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1UsersViewController.h"

@class TFNGenericItem, TFNTwitterUser, TFNTwitterUserFollowersList;

__attribute__((visibility("hidden")))
@interface T1LegacyFollowersViewController : T1UsersViewController
{
    TFNTwitterUser *_user;
    TFNGenericItem *_followerRequestItem;
    TFNTwitterUserFollowersList *_followersList;
    unsigned int _followerRequestCount;
}

@property(nonatomic) unsigned int followerRequestCount; // @synthesize followerRequestCount=_followerRequestCount;
@property(retain, nonatomic) TFNTwitterUserFollowersList *followersList; // @synthesize followersList=_followersList;
@property(retain, nonatomic) TFNGenericItem *followerRequestItem; // @synthesize followerRequestItem=_followerRequestItem;
@property(retain, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (unsigned int)indexOfSectionWithID:(unsigned int)arg1;
- (unsigned int)sectionIdentifierForIndex:(unsigned int)arg1;
- (id)indexPathForBackingObject:(id)arg1;
- (id)backingObjectAtIndexPath:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)scribeContextForIndexPath:(id)arg1;
- (id)scribeAssociationID;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)_followersListDidUpdate:(id)arg1;
- (void)requestUsers;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)_updateFollowerRequestCount;
- (BOOL)_shouldShowFollowerRequests;

@end

