//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "UITextFieldDelegate.h"

@class TFNHUD, UIBarButtonItem, UITextField;

__attribute__((visibility("hidden")))
@interface T1LinkQueueAddAccountViewController : TFNItemsDataViewController <UITextFieldDelegate>
{
    UIBarButtonItem *_saveButtonItem;
    TFNHUD *_hud;
    BOOL _hideHUDImmediatelyAfterVerifyingAccount;
    id <T1LinkQueueAddAccountViewControllerDelegate> _delegate;
    UITextField *_usernameField;
    UITextField *_passwordField;
}

@property(retain, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) UITextField *usernameField; // @synthesize usernameField=_usernameField;
@property(nonatomic) BOOL hideHUDImmediatelyAfterVerifyingAccount; // @synthesize hideHUDImmediatelyAfterVerifyingAccount=_hideHUDImmediatelyAfterVerifyingAccount;
@property(nonatomic) __weak id <T1LinkQueueAddAccountViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancel:(id)arg1;
- (void)_textFieldTextDidChange:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)save:(id)arg1;
- (void)updateSections;
- (void)dealloc;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)init;

@end

