//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class LinkQueue, T1LinkQueueAddAccountViewController;

@protocol T1LinkQueueAddAccountViewControllerDelegate
- (void)linkQueueAddAccountViewController:(T1LinkQueueAddAccountViewController *)arg1 dismissWithLinkQueue:(LinkQueue *)arg2;
@end

