//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1ListsListViewController.h"

@class TFNTwitterAccount, TFNTwitterListList, TFNTwitterUser;

__attribute__((visibility("hidden")))
@interface T1ListsFollowingViewController : T1ListsListViewController
{
    TFNTwitterAccount *_account;
    TFNTwitterUser *_user;
    TFNTwitterListList *_listsList;
}

- (void)setListsList:(id)arg1;
- (id)listsList;
- (void)setUser:(id)arg1;
- (id)user;
- (void)setAccount:(id)arg1;
- (id)account;
- (void).cxx_destruct;
- (id)scribeSection;
- (void)_membershipsDidUpdate:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

