//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface T1MediaGridCell : TFNTableViewCell
{
    NSMutableArray *_downloads;
    NSMutableArray *_imageViews;
    NSArray *_scaledSizes;
    NSArray *_validMediaPreviewInfos;
    float _width;
    id <T1MediaSearchCellDelegate> _delegate;
}

+ (float)heightWithMediaPreviewInfos:(id)arg1 width:(float)arg2;
+ (id)_scaledSizesForMediaPreviewInfos:(id)arg1 width:(float)arg2;
@property(nonatomic) __weak id <T1MediaSearchCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) float width; // @synthesize width=_width;
- (void).cxx_destruct;
- (void)willDisplayWithSectionBreaks:(int)arg1 inDataViewController:(id)arg2;
- (void)_imageDownloadStatusDidChange:(id)arg1;
- (void)layoutSubviews;
- (void)_didTapPhoto:(id)arg1;
- (void)_updateImage:(id)arg1 atIndex:(int)arg2;
- (void)_updateScaledSizes;
- (id)imageViewForMediaPreviewInfo:(id)arg1;
@property(retain, nonatomic) NSArray *mediaPreviewInfos;
- (void)_cancelDownloads;
- (void)cleanup;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

