//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "T1MediaChooserCustomEditorDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIPopoverControllerDelegate.h"

@class ALAsset, NSError, NSString, NSURL, UIImage, UIPopoverController, UIView, UIViewController, UIViewController<T1MediaChooserCustomEditor>;

__attribute__((visibility("hidden")))
@interface T1MediaChooser : NSObject <T1MediaChooserCustomEditorDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIPopoverControllerDelegate>
{
    int choices;
    UIViewController *_weakSourceViewController;
    CDUnknownBlockType _block;
    struct {
        unsigned int shouldSaveToLibrary:1;
    } _flags;
    UIImage *image;
    NSURL *movieURL;
    NSError *error;
    struct CGRect fromRect;
    UIView *inView;
    BOOL removeImage;
    int _selectionType;
    UIViewController<T1MediaChooserCustomEditor> *_customEditingController;
    NSString *_removePhotoLabel;
    UIPopoverController *popoverController;
    ALAsset *_asset;
}

+ (id)choose:(int)arg1 rect:(struct CGRect)arg2 inView:(id)arg3 customEditingController:(id)arg4 removePhotoLabel:(id)arg5 block:(CDUnknownBlockType)arg6;
+ (id)choose:(int)arg1 rect:(struct CGRect)arg2 inView:(id)arg3 block:(CDUnknownBlockType)arg4;
+ (id)choose:(int)arg1 fromViewController:(id)arg2 customEditingController:(id)arg3 removePhotoLabel:(id)arg4 block:(CDUnknownBlockType)arg5;
+ (id)choose:(int)arg1 fromViewController:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (BOOL)hasCamera;
+ (int)availableOptions:(int)arg1;
@property(retain, nonatomic) ALAsset *asset; // @synthesize asset=_asset;
@property(readonly, nonatomic) UIPopoverController *popoverController; // @synthesize popoverController;
@property(copy, nonatomic) NSString *removePhotoLabel; // @synthesize removePhotoLabel=_removePhotoLabel;
@property(retain, nonatomic) UIViewController<T1MediaChooserCustomEditor> *customEditingController; // @synthesize customEditingController=_customEditingController;
@property(nonatomic) int selectionType; // @synthesize selectionType=_selectionType;
@property(nonatomic) BOOL removeImage; // @synthesize removeImage;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(retain, nonatomic) NSURL *movieURL; // @synthesize movieURL;
@property(retain, nonatomic) UIImage *image; // @synthesize image;
- (void).cxx_destruct;
- (id)initWithMediaChoices:(int)arg1 viewController:(id)arg2 customEditingController:(id)arg3 removePhotoLabel:(id)arg4 block:(CDUnknownBlockType)arg5;
- (id)initWithMediaChoices:(int)arg1 viewController:(id)arg2 block:(CDUnknownBlockType)arg3;
- (id)initWithMediaChoices:(int)arg1 rect:(struct CGRect)arg2 inView:(id)arg3 removePhotoLabel:(id)arg4 block:(CDUnknownBlockType)arg5;
- (void)show;
- (void)showActionSheet;
- (void)recordAudio;
- (void)recordVideo;
- (void)chooseExistingVideo;
- (void)chooseExistingPhoto;
- (void)takePhoto;
- (void)takePhotoOrVideo;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)customEditorDidCancel:(id)arg1;
- (void)customEditor:(id)arg1 didEditImage:(id)arg2;
- (void)handleAssetLibraryURL:(id)arg1;
- (void)finish;
- (id)topViewController;

@end

