//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1NewDirectMessageAbstractThreadEntryCell.h"

@class T1NewDirectMessageActivityEntryDisplayModel, UILabel;

__attribute__((visibility("hidden")))
@interface T1NewDirectMessageActivityEntryCell : T1NewDirectMessageAbstractThreadEntryCell
{
    UILabel *_activityLabel;
}

@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
@property(retain, nonatomic) T1NewDirectMessageActivityEntryDisplayModel *entryDisplayModel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

