//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MKAnnotation.h"

@class NSMutableArray, NSString, TFNTwitterUser, UIImage;

__attribute__((visibility("hidden")))
@interface T1NearbyClusterAnnotation : NSObject <MKAnnotation>
{
    int _imageType;
    NSMutableArray *_items;
    TFNTwitterUser *_clusterRepresentative;
    UIImage *_iconImage;
    CDStruct_2c43369c _coordinate;
}

@property(retain, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) TFNTwitterUser *clusterRepresentative; // @synthesize clusterRepresentative=_clusterRepresentative;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) int imageType; // @synthesize imageType=_imageType;
@property(nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate=_coordinate;
- (void).cxx_destruct;
- (id)description;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) unsigned int weight;
- (CDStruct_c3b9c2ee)centroid;
- (int)_ImageTypeForCluster;
- (void)addItems:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *subtitle;

@end

