//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "UITextViewDelegate.h"

@class T1NewDirectMessageTokenizedSearchBar;

@protocol T1NewDirectMessageTokenizedSearchBarDelegate <NSObject, UITextViewDelegate>

@optional
- (void)searchBarDidChangeNumberOfLines:(T1NewDirectMessageTokenizedSearchBar *)arg1;
- (void)searchBar:(T1NewDirectMessageTokenizedSearchBar *)arg1 didRemoveTokenAtIndex:(int)arg2;
@end

