//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, TFNNewDirectMessageThread;

__attribute__((visibility("hidden")))
@interface T1NewDirectMessageThreadMetadataDisplayModel : NSObject
{
    NSArray *_participantsToDisplay;
    NSString *_threadSubtitle;
    NSString *_threadTitle;
    TFNNewDirectMessageThread *_thread;
}

+ (id)directMessageThreadMetadataDisplayModelWithThread:(id)arg1;
@property(retain, nonatomic) TFNNewDirectMessageThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) NSString *threadTitle; // @synthesize threadTitle=_threadTitle;
@property(retain, nonatomic) NSString *threadSubtitle; // @synthesize threadSubtitle=_threadSubtitle;
@property(retain, nonatomic) NSArray *participantsToDisplay; // @synthesize participantsToDisplay=_participantsToDisplay;
- (void).cxx_destruct;
- (void)_updateDisplayProperties;

@end

