//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1NewDirectMessageActivityEntryDisplayModel.h"

@class TFNNewDirectMessageParticipantsJoinedEntry;

__attribute__((visibility("hidden")))
@interface T1NewDirectMessageParticipantsJoinedEntryDisplayModel : T1NewDirectMessageActivityEntryDisplayModel
{
    TFNNewDirectMessageParticipantsJoinedEntry *_entry;
}

@property(retain, nonatomic) TFNNewDirectMessageParticipantsJoinedEntry *entry; // @synthesize entry=_entry;
- (void).cxx_destruct;
- (void)_updateText;
- (id)initWithParticipantsJoinedEntry:(id)arg1;

@end

