//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "T1OnboardingProfileBioEditViewDelegate.h"
#import "T1OnboardingProfileHeaderCellDelegate.h"
#import "TFNTwitterAuthenticated.h"
#import "UITextViewDelegate.h"

@class NSString, T1MediaChooser, T1OnboardingProfileBioEditView, T1OnboardingProfileHeaderAdapter, TFNTwitterAccount, UIButton, UIToolbar;

__attribute__((visibility("hidden")))
@interface T1OnboardingProfileViewController : TFNItemsDataViewController <T1OnboardingProfileHeaderCellDelegate, T1OnboardingProfileBioEditViewDelegate, TFNTwitterAuthenticated, UITextViewDelegate>
{
    int _prioritizedType;
    int _preparedType;
    BOOL _userAddedAvatar;
    BOOL _userAddedBanner;
    BOOL _userSawPhotoPrompt;
    NSString *_avatarFilePath;
    NSString *_bannerFilePath;
    struct CGRect _keyboardFrame;
    UIToolbar *_editingToolbar;
    BOOL _legacyMode;
    TFNTwitterAccount *_account;
    int _onboardingFlowSource;
    T1MediaChooser *_mediaChooser;
    T1OnboardingProfileHeaderAdapter *_photoHeaderAdapter;
    UIButton *_addPhotoButton;
    T1OnboardingProfileBioEditView *_bioEditView;
}

@property(retain, nonatomic) T1OnboardingProfileBioEditView *bioEditView; // @synthesize bioEditView=_bioEditView;
@property(retain, nonatomic) UIButton *addPhotoButton; // @synthesize addPhotoButton=_addPhotoButton;
@property(retain, nonatomic) T1OnboardingProfileHeaderAdapter *photoHeaderAdapter; // @synthesize photoHeaderAdapter=_photoHeaderAdapter;
@property(retain, nonatomic) T1MediaChooser *mediaChooser; // @synthesize mediaChooser=_mediaChooser;
@property(readonly, nonatomic) BOOL legacyMode; // @synthesize legacyMode=_legacyMode;
@property(nonatomic) int onboardingFlowSource; // @synthesize onboardingFlowSource=_onboardingFlowSource;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeSection;
- (id)scribePage;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (id)_bioCharacterCountItem;
- (id)_saveToolbarItems;
- (id)_finishToolbarItems;
- (void)_updateAddPhotoButton;
- (void)bioEditView:(id)arg1 characterCountChangedTo:(unsigned int)arg2;
- (void)bioEditView:(id)arg1 didChangeStateTo:(int)arg2;
- (void)profileHeaderCellBannerTapped:(id)arg1;
- (void)profileHeaderCellAvatarTapped:(id)arg1;
- (id)_guideItem;
- (id)staticSections;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)_closeTapped;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)_updateBio:(id)arg1;
- (void)_uploadBanner:(id)arg1;
- (void)_uploadAvatar:(id)arg1;
- (void)_finish;
- (void)_verifyOnboardingFinish;
- (BOOL)_shouldShowPhotoPrompt;
- (void)_finishAddingPhoto:(id)arg1 ofType:(int)arg2;
- (void)_addPhotoForType:(int)arg1;
- (void)_prepareToAddPhotoForType:(int)arg1;
- (void)_prepareToAddPhoto;
- (void)_prepareToAddPhotoForEitherType;
- (BOOL)_userHasBanner;
- (BOOL)_userHasAvatar;
- (void)_t1_keyboardWillShow:(id)arg1;
@property(readonly, nonatomic) UIToolbar *editingToolbar;
- (id)initWithLegacyMode:(BOOL)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

