//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface T1OnboardingSMSConfirmController : NSObject
{
}

+ (id)scribeSection;
+ (id)scribePageForFlowSource:(int)arg1;
+ (void)_performDeviceRegistrationHashLookupAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)prepareConfirmSMSControllerWithDelegate:(id)arg1 account:(id)arg2 onboardingFlowSource:(int)arg3 completion:(CDUnknownBlockType)arg4;

@end

