//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNViewController.h"

#import "T1SearchFiltersViewControllerDelegate.h"
#import "TFNChromeLayout.h"
#import "TFNScopedContainerViewControllerDelegate.h"
#import "TFNTwitterAuthenticated.h"

@class NSString, T1SearchFiltersViewController, TFNBarButtonItem, TFNScopedContainerViewController, TFNTwitterAccount, TFNTwitterSearchQuery, UIPopoverController;

__attribute__((visibility("hidden")))
@interface T1PadSearchContainerViewController : TFNViewController <TFNTwitterAuthenticated, TFNChromeLayout, T1SearchFiltersViewControllerDelegate, TFNScopedContainerViewControllerDelegate>
{
    TFNScopedContainerViewController *_scopedVC;
    unsigned int _searchFilterType;
    T1SearchFiltersViewController *_filtersController;
    UIPopoverController *_popoverFilterController;
    TFNBarButtonItem *_filterItem;
    TFNTwitterAccount *_account;
    TFNTwitterSearchQuery *_searchQuery;
    NSString *_scribeParameterContext;
}

@property(copy, nonatomic) NSString *scribeParameterContext; // @synthesize scribeParameterContext=_scribeParameterContext;
@property(retain, nonatomic) TFNTwitterSearchQuery *searchQuery; // @synthesize searchQuery=_searchQuery;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeImpressionParameters;
- (id)_scribeSocialFilter;
- (id)_scribeResultFilter;
- (id)_scribeParameterSearchDetails;
- (id)_searchScribeContext;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)setVisibleChromeInset:(struct UIEdgeInsets)arg1 animated:(BOOL)arg2;
- (void)setUnderChromeInset:(struct UIEdgeInsets)arg1 animated:(BOOL)arg2;
- (id)scopedContainerViewController:(id)arg1 titleForSegmentAtIndex:(int)arg2;
- (id)_videoSearchViewControllers;
- (id)_imageSearchViewControllers;
- (id)_topAllSearchControllers;
- (id)_standardSearchControllers;
- (void)_resetScopeViewControllers;
- (void)searchFiltersControllerDidApplyFilters:(id)arg1;
- (void)_showFilters:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

