//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1TabNavigationController.h"

#import "UIPopoverControllerDelegate.h"

@class T1PadSearchPopoverController, UIBarButtonItem, UIPopoverController;

__attribute__((visibility("hidden")))
@interface T1PadTabNavigationController : T1TabNavigationController <UIPopoverControllerDelegate>
{
    T1PadSearchPopoverController *_searchPopoverController;
    UIBarButtonItem *_searchPopoverItem;
    UIPopoverController *_draftsPopoverController;
    UIBarButtonItem *_draftsPopoverItem;
}

- (void).cxx_destruct;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (BOOL)popoverControllerShouldDismissPopover:(id)arg1;
- (void)draftsViewControllerDidSendAll:(id)arg1;
- (void)draftsViewControllerDidCancel:(id)arg1;
- (void)draftsViewControllerDidRemoveDraft:(id)arg1 withComposition:(id)arg2;
- (void)draftsViewControllerDidSelectDraft:(id)arg1 withComposition:(id)arg2;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidLoad;
- (void)_dismissDraftPopoverWithDraftsViewController:(id)arg1;
- (void)_adjustContentInset:(id)arg1;
- (void)setViewControllers:(id)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)_showDraftsPopoverFromBarButtonItem:(id)arg1;
- (void)showDraftsFromBarButtonItem:(id)arg1;
- (void)showComposeFromBarButtonItem:(id)arg1;
- (void)_showSearchPopoverWithQuery:(id)arg1 fromBarButtonItem:(id)arg2;
- (void)showSearchFromBarButtonItem:(id)arg1;
- (void)dealloc;

@end

