//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, TFNTwitterAccount;

@protocol T1PadMyPeepsGridViewControllerDataSource <NSObject>
@property(copy, nonatomic) CDUnknownBlockType dataSourceWasInvalidatedBlock;
@property(retain, nonatomic) TFNTwitterAccount *account;
@property(readonly, nonatomic) NSArray *followingUsers;
@property(readonly, nonatomic) NSArray *wtfUsers;
@property(readonly, nonatomic) NSArray *recentUsers;
@property(readonly, nonatomic) NSArray *favoriteUsers;
@end

