//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface T1PadMetricsButtonContainerView : UIView
{
    NSArray *_buttons;
    CDUnknownBlockType _layoutSubviewsBlock;
}

@property(copy, nonatomic) CDUnknownBlockType layoutSubviewsBlock; // @synthesize layoutSubviewsBlock=_layoutSubviewsBlock;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
- (void).cxx_destruct;
- (void)layoutSubviews;

@end

