//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABPeoplePickerNavigationController.h"

@class NSString, TFNTwitterScribeContext, UIImage;

__attribute__((visibility("hidden")))
@interface T1PeoplePickerNavigationController : ABPeoplePickerNavigationController
{
    TFNTwitterScribeContext *_scribeContext;
    UIImage *_userAvatar;
    NSString *_username;
}

@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) UIImage *userAvatar; // @synthesize userAvatar=_userAvatar;
@property(retain, nonatomic) TFNTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
- (void).cxx_destruct;

@end

