//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "T1EditProfileViewControllerDelegate.h"
#import "T1PhoneProfileActionButtonsViewDelegate.h"
#import "T1PhoneProfileHeaderInfoViewDelegate.h"
#import "T1PhoneProfileHeaderSummaryViewDelegate.h"
#import "T1PhoneProfileHeaderViewDelegate.h"
#import "T1PresentedAccountsViewControllerDelegate.h"
#import "T1ProfileViewController.h"
#import "TFNTwitterAuthenticated.h"

@class NSMutableDictionary, T1PhoneProfileHeaderView, TFNTwitterAccount, TFNTwitterScribeContext, TFNTwitterStatus;

__attribute__((visibility("hidden")))
@interface T1PhoneProfileHeaderViewController : UIViewController <T1PhoneProfileHeaderInfoViewDelegate, T1PhoneProfileActionButtonsViewDelegate, T1EditProfileViewControllerDelegate, T1PhoneProfileHeaderViewDelegate, T1PhoneProfileHeaderSummaryViewDelegate, TFNTwitterAuthenticated, T1ProfileViewController, T1PresentedAccountsViewControllerDelegate>
{
    TFNTwitterAccount *_account;
    TFNTwitterStatus *_sourceStatus;
    TFNTwitterScribeContext *_sourceScribeContext;
    id <T1ProfileDataSource> _dataSource;
    id <T1PhoneProfileHeaderViewControllerDelegate> _delegate;
    NSMutableDictionary *_tmpUserInfo;
}

@property(retain, nonatomic) NSMutableDictionary *tmpUserInfo; // @synthesize tmpUserInfo=_tmpUserInfo;
@property(nonatomic) __weak id <T1PhoneProfileHeaderViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <T1ProfileDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) TFNTwitterScribeContext *sourceScribeContext; // @synthesize sourceScribeContext=_sourceScribeContext;
@property(retain, nonatomic) TFNTwitterStatus *sourceStatus; // @synthesize sourceStatus=_sourceStatus;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)_promotedContent;
- (void)_logPromotedEvent:(int)arg1;
- (void)_didLifelineUnfollowUserWithSuccess:(BOOL)arg1 error:(id)arg2;
- (void)_didLifelineFollowUserWithSuccess:(BOOL)arg1 error:(id)arg2;
- (void)_disableTwitterAlerts;
- (void)_enableTwitterAlerts;
- (void)_viewProfileImage;
- (void)_showAvatarOptions;
- (void)_showAvatarOrPresentOptions;
- (void)_viewDrafts;
- (void)_viewFollowerRequests;
- (void)_viewCustomTimelines;
- (void)_viewLists;
- (float)_heightForNavigationBar;
- (void)_canNotUnenrollWithAccount:(id)arg1;
- (void)_removeAccount:(id)arg1;
- (void)_confirmSignOut;
- (void)_gotoSettings;
- (void)_showSettingsMenu;
- (void)_editProfile;
- (void)_restoreUserInfo;
- (void)_cacheUserInfo;
- (void)_showDirectMessagesWithScribeContext:(id)arg1;
- (void)_composeTweetWithScribeContext:(id)arg1 composition:(id)arg2;
- (void)_viewFollowers;
- (void)_viewFollowing;
- (BOOL)isUserProtectedFromViewingAccount;
- (void)_unfollowUserWithScribeContext:(id)arg1;
- (void)_followUserWithScribeContext:(id)arg1;
- (void)_presentMoreActionsMenu;
- (void)_profileDataSourceDidInvalidateForReason:(int)arg1;
- (void)_profileDataSourceDidInvalidate:(id)arg1;
- (void)_reloadAllData;
- (void)profileActionButtonsViewDidTapUnmuteButton:(id)arg1;
- (void)profileActionButtonsViewDidToggleTwitterAlertsButton:(id)arg1;
- (void)profileActionButtonsViewDidTapSwitchAccountsButton:(id)arg1;
- (void)profileActionButtonsViewDidTapSettingsButton:(id)arg1;
- (void)profileActionButtonsViewDidTapEditProfileButton:(id)arg1;
- (void)profileActionButtonsViewDidTapActionButton:(id)arg1;
- (void)profileActionButtonsView:(id)arg1 didSucceedFollowingUser:(id)arg2;
- (void)profileActionButtonsView:(id)arg1 didFailFollowingUser:(id)arg2 withError:(id)arg3;
- (void)accountsController:(id)arg1 didShowGapBelowCellWithOffset:(float)arg2 backgroundImage:(id)arg3;
- (void)accountsController:(id)arg1 willShowGapBelowCellWithOffset:(float)arg2 backgroundImage:(id)arg3;
- (void)accountsController:(id)arg1 willDismissFromOffset:(float)arg2 withAccount:(id)arg3 backgroundImages:(id)arg4;
- (void)editProfileViewControllerWillRemoveHeader:(id)arg1;
- (void)editProfileViewControllerWillChangeHeader:(id)arg1;
- (void)editProfileViewController:(id)arg1 didSave:(BOOL)arg2;
- (void)editProfileViewControllerWillSave:(id)arg1;
- (void)summaryViewDidTapFullName:(id)arg1;
- (void)summaryViewDidLongPressAvatar:(id)arg1;
- (void)summaryViewDidTapAvatar:(id)arg1;
- (void)profileHeaderInfoView:(id)arg1 didTapBioActiveRange:(id)arg2;
- (void)profileHeaderInfoViewDidTapTweetTo:(id)arg1;
- (void)profileHeaderInfoViewDidTapMessage:(id)arg1;
- (void)profileHeaderInfoViewDidTapFollowing:(id)arg1;
- (void)profileHeaderInfoViewDidTapFollowers:(id)arg1;
- (void)profileHeaderInfoView:(id)arg1 didLongPressURL:(id)arg2;
- (void)profileHeaderInfoView:(id)arg1 didTapURL:(id)arg2;
- (void)profileHeaderViewDidTapFollowNavigationButton:(id)arg1;
- (void)profileHeaderViewDidTapBackButton:(id)arg1;
- (void)profileHeaderViewDidLongPressComposeButton:(id)arg1;
- (void)profileHeaderViewDidTapComposeButton:(id)arg1;
- (void)profileHeaderViewDidTapMoreActionsButton:(id)arg1;
- (void)profileHeaderViewDidTapFollowerRequestButton:(id)arg1;
- (void)profileHeaderViewDidUpdatePreferredSize:(id)arg1;
- (BOOL)isProfileForUser:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (int)preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (struct CGSize)preferredContentSize;
- (void)dealloc;

// Remaining properties
@property(retain, nonatomic) T1PhoneProfileHeaderView *view;

@end

