//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNViewController.h"

#import "T1EditableProfileViewController.h"
#import "T1PhoneProfileHeaderViewControllerDelegate.h"
#import "T1PresentedAccountsViewControllerHost.h"
#import "T1TabbedTimelinesViewControllerDataSource.h"
#import "T1TabbedTimelinesViewControllerDelegate.h"
#import "TFNChromeLayout.h"
#import "TFNTwitterAuthenticated.h"

@class NSArray, T1PhoneProfileHeaderViewController, T1ProfileClusterFollowViewController, T1ProfileNavigationEntry, T1TabbedTimelinesViewController, TFNTwitterAccount, TFNTwitterScribeContext, TFNTwitterStatus, UIPanGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface T1PhoneProfileViewController : TFNViewController <T1PhoneProfileHeaderViewControllerDelegate, T1TabbedTimelinesViewControllerDataSource, T1TabbedTimelinesViewControllerDelegate, T1EditableProfileViewController, TFNChromeLayout, TFNTwitterAuthenticated, T1PresentedAccountsViewControllerHost>
{
    BOOL _scrollingToTop;
    BOOL _headerWillZoom;
    BOOL _headerZooming;
    BOOL _protectedAccountMessageVisible;
    TFNTwitterAccount *_account;
    TFNTwitterStatus *_sourceStatus;
    TFNTwitterScribeContext *_sourceScribeContext;
    T1ProfileNavigationEntry *_tweetsEntry;
    T1ProfileNavigationEntry *_mediaEntry;
    T1ProfileNavigationEntry *_favoritesEntry;
    NSArray *_navigationEntries;
    T1PhoneProfileHeaderViewController *_headerViewController;
    T1TabbedTimelinesViewController *_contentViewController;
    T1ProfileClusterFollowViewController *_clusterFollowViewController;
    UIView *_clusterFollowContainerView;
    UIPanGestureRecognizer *_panGestureRecognizer;
    float _preferredHeaderHeight;
    float _currentHeaderHeight;
    float _currentScrollY;
    id <T1ProfileDataSource> _dataSource;
    struct UIEdgeInsets _visibleChromeInset;
    struct UIEdgeInsets _underChromeInset;
}

@property(nonatomic, getter=isProtectedAccountMessageVisible) BOOL protectedAccountMessageVisible; // @synthesize protectedAccountMessageVisible=_protectedAccountMessageVisible;
@property(retain, nonatomic) id <T1ProfileDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) struct UIEdgeInsets underChromeInset; // @synthesize underChromeInset=_underChromeInset;
@property(nonatomic) struct UIEdgeInsets visibleChromeInset; // @synthesize visibleChromeInset=_visibleChromeInset;
@property(nonatomic) BOOL headerZooming; // @synthesize headerZooming=_headerZooming;
@property(nonatomic) BOOL headerWillZoom; // @synthesize headerWillZoom=_headerWillZoom;
@property(nonatomic) BOOL scrollingToTop; // @synthesize scrollingToTop=_scrollingToTop;
@property(nonatomic) float currentScrollY; // @synthesize currentScrollY=_currentScrollY;
@property(nonatomic) float currentHeaderHeight; // @synthesize currentHeaderHeight=_currentHeaderHeight;
@property(nonatomic) float preferredHeaderHeight; // @synthesize preferredHeaderHeight=_preferredHeaderHeight;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
@property(retain, nonatomic) UIView *clusterFollowContainerView; // @synthesize clusterFollowContainerView=_clusterFollowContainerView;
@property(retain, nonatomic) T1ProfileClusterFollowViewController *clusterFollowViewController; // @synthesize clusterFollowViewController=_clusterFollowViewController;
@property(retain, nonatomic) T1TabbedTimelinesViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(retain, nonatomic) T1PhoneProfileHeaderViewController *headerViewController; // @synthesize headerViewController=_headerViewController;
@property(copy, nonatomic) NSArray *navigationEntries; // @synthesize navigationEntries=_navigationEntries;
@property(retain, nonatomic) T1ProfileNavigationEntry *favoritesEntry; // @synthesize favoritesEntry=_favoritesEntry;
@property(retain, nonatomic) T1ProfileNavigationEntry *mediaEntry; // @synthesize mediaEntry=_mediaEntry;
@property(retain, nonatomic) T1ProfileNavigationEntry *tweetsEntry; // @synthesize tweetsEntry=_tweetsEntry;
@property(retain, nonatomic) TFNTwitterScribeContext *sourceScribeContext; // @synthesize sourceScribeContext=_sourceScribeContext;
@property(retain, nonatomic) TFNTwitterStatus *sourceStatus; // @synthesize sourceStatus=_sourceStatus;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_switchToAccount:(id)arg1;
- (void)_showAccounts;
- (void)_finishExpansion;
- (void)_collapseToHideAccounts:(BOOL)arg1;
- (void)_expandToShowAccounts;
- (void)_prepareForExpansion;
- (id)_generateProtectedAccountMessage;
- (id)_generateProtectedAccountMessageViewController;
- (id)_generateFavoritesViewController;
- (id)_generateMediaViewController;
- (id)_generateTweetsViewController;
- (void)_initializeNavigationEntries;
- (void)_removeClusterFollowViewController;
- (void)_addClusterFollowViewController;
- (void)_profileDataSourceDidInvalidate:(id)arg1;
- (void)_updatePreferredHeaderHeight;
- (void)_ensureMinimumContentOffsetForScrollView:(id)arg1;
- (void)_layoutHeader;
- (void)_applyVisibleChromeInsetToContentViewController;
- (void)_applyUnderChromeInsetToContentViewController;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)switchAccounts;
- (void)setVisibleChromeInset:(struct UIEdgeInsets)arg1 animated:(BOOL)arg2;
- (void)setUnderChromeInset:(struct UIEdgeInsets)arg1 animated:(BOOL)arg2;
- (BOOL)tfn_navigationContentScrollViewShouldScrollToTop:(id)arg1;
- (void)tfn_navigationContentScrollViewDidEndScrollingAnimation:(id)arg1;
- (void)tfn_navigationContentScrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)tfn_navigationContentScrollViewDidScroll:(id)arg1 animate:(BOOL)arg2;
- (BOOL)isProfileForUser:(id)arg1;
- (void)tabbedViewController:(id)arg1 didSelectViewControllerAtIndex:(int)arg2;
- (id)tabbedViewController:(id)arg1 countAtIndex:(int)arg2;
- (id)tabbedViewController:(id)arg1 titleAtIndex:(int)arg2;
- (id)tabbedViewController:(id)arg1 viewControllerAtIndex:(int)arg2;
- (int)numberOfViewControllersInTabbedViewController:(id)arg1;
- (void)profileHeaderViewController:(id)arg1 willCollapseViewWithOffset:(float)arg2;
- (void)profileHeaderViewControllerWillExpandView:(id)arg1;
- (void)profileHeaderViewControllerDidUpdatePreferredContentSize:(id)arg1;
- (int)preferredStatusBarStyle;
- (unsigned int)supportedInterfaceOrientations;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)editProfileActionWithCompletion:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithDataSource:(id)arg1;

@end

