//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNForm.h"

@class NSString, TFNFormField;

__attribute__((visibility("hidden")))
@interface T1PlaygroundForm : TFNForm
{
    BOOL _fullWidth;
    TFNFormField *_usernameField;
    TFNFormField *_passwordField;
    TFNFormField *_fullNameField;
    TFNFormField *_emailField;
    unsigned int _formFieldType;
}

+ (id)_invalidCharacterForUsername:(id)arg1;
@property(readonly, nonatomic) unsigned int formFieldType; // @synthesize formFieldType=_formFieldType;
@property(readonly, nonatomic) BOOL fullWidth; // @synthesize fullWidth=_fullWidth;
@property(retain, nonatomic) TFNFormField *emailField; // @synthesize emailField=_emailField;
@property(retain, nonatomic) TFNFormField *fullNameField; // @synthesize fullNameField=_fullNameField;
@property(retain, nonatomic) TFNFormField *passwordField; // @synthesize passwordField=_passwordField;
@property(retain, nonatomic) TFNFormField *usernameField; // @synthesize usernameField=_usernameField;
- (void).cxx_destruct;
- (id)sections;
- (id)_formFieldWithTitle:(id)arg1 hintText:(id)arg2;
@property(readonly, nonatomic) NSString *submissionMessage;
- (id)initWithFormFieldType:(unsigned int)arg1 fullWidth:(BOOL)arg2;

@end

