//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNProtocolHandler.h"

@class NSSet;

__attribute__((visibility("hidden")))
@interface T1ProtocolHandler : NSObject <TFNProtocolHandler>
{
    NSSet *_schemes;
}

- (void).cxx_destruct;
- (void)_loginWithTokenForPasswordReset:(id)arg1;
- (BOOL)protocolRouter:(id)arg1 handleURL:(id)arg2 context:(id)arg3;
- (BOOL)protocolRouter:(id)arg1 supportsScheme:(id)arg2;
- (id)schemes;

@end

