//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1RevenueBaseCardForwardView.h"

__attribute__((visibility("hidden")))
@interface T1RevenueBannerButtonCardForwardView : T1RevenueBaseCardForwardView
{
}

+ (struct CGSize)cardSize;
- (void)update;
- (id)callToActionForCard;
- (id)init;

@end

