//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "TFNTwitterAuthenticated.h"

@class CLLocation, NSArray, NSMutableArray, NSString, T1DownwardDisclosureRowAdapter, T1SearchFilterRowAdapter, TFNTwitterAccount, TFNTwitterScribe, TFNTwitterSearchQuery;

__attribute__((visibility("hidden")))
@interface T1SearchFiltersViewController : TFNItemsDataViewController <TFNTwitterAuthenticated>
{
    NSArray *_initialSelectedIndexes;
    NSMutableArray *_selectedIndexes;
    NSArray *_generalFilters;
    NSArray *_peopleFilters;
    NSArray *_locationFilters;
    NSArray *_staticSections;
    CLLocation *_lastLocation;
    BOOL _isSemiModal;
    NSString *_moreOptionsItem;
    T1SearchFilterRowAdapter *_selectedFilterAdapter;
    T1DownwardDisclosureRowAdapter *_moreOptionsAdapter;
    TFNTwitterAccount *_account;
    TFNTwitterSearchQuery *_searchQuery;
    id <T1SearchFiltersViewControllerDelegate> _delegate;
    TFNTwitterScribe *_scribe;
}

@property(retain, nonatomic) TFNTwitterScribe *scribe; // @synthesize scribe=_scribe;
@property(nonatomic) __weak id <T1SearchFiltersViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterSearchQuery *searchQuery; // @synthesize searchQuery=_searchQuery;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (void)_requestLocation;
- (void)_showEnableLocationServicesPrompt;
- (void)didSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (void)_updateSearchQuery;
- (void)_updateSelectedIndexes;
- (void)_didSwipeDown;
- (void)_didSwipeUp;
- (void)_showMoreOptions;
- (id)_moreOptionsIndexPath;
- (void)_updateSections;
- (void)_applyTapped;
- (void)_cancelTapped;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)init;

@end

