//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNStringDataViewAdapter.h"

#import "TFNTwitterAuthenticated.h"

@class NSString, TFNTwitterAccount;

__attribute__((visibility("hidden")))
@interface T1SearchQueryTableRowAdapter : TFNStringDataViewAdapter <TFNTwitterAuthenticated>
{
    TFNTwitterAccount *_account;
    NSString *_typeaheadString;
}

+ (struct _NSRange)reverseBoldingRangeForText:(id)arg1 withTypeaheadString:(id)arg2;
+ (id)_boldedAttributedStringForAttributedString:(id)arg1 withTypeaheadString:(id)arg2;
@property(copy, nonatomic) NSString *typeaheadString; // @synthesize typeaheadString=_typeaheadString;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (BOOL)_shouldDisplayTapaheadButtonForController:(id)arg1 forSearchQuery:(id)arg2 atIndexPath:(id)arg3;
- (void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (float)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

@end

