//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1SectionHeaderCell.h"

@class T1ClearButton, T1ClearButtonGestureRecognizer, UIImage, UILabel;

__attribute__((visibility("hidden")))
@interface T1SectionClearHeaderCell : T1SectionHeaderCell
{
    BOOL _animating;
    BOOL _clearButtonActive;
    T1ClearButton *_clearButton;
    UILabel *_buttonLabel;
    UIImage *_xImage;
    float _labelWidthLocalized;
    T1ClearButtonGestureRecognizer *_gestureRecognizer;
    id <T1SectionClearDelegate> _delegate;
}

@property(nonatomic) __weak id <T1SectionClearDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_clearButtonWillBecomeInactiveAnimated:(BOOL)arg1;
- (void)_clearButtonWillBecomeActiveAnimated:(BOOL)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)layoutSubviews;
- (void)_clearButtonTapped;
- (void)deactivateClearButton;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

