//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNDrawingTableViewCell.h"

@class NSArray, TFNAttributedTextDrawing;

__attribute__((visibility("hidden")))
@interface T1SensitiveMediaCell : TFNDrawingTableViewCell
{
    CDUnknownBlockType _tappedBlock;
    TFNAttributedTextDrawing *_textDrawing;
    NSArray *_axElements;
}

+ (struct _NSRange)_appendString:(id)arg1 withFont:(id)arg2 andColor:(id)arg3 toAttributedString:(id)arg4;
+ (id)_createTextModelAndRanges:(id *)arg1;
+ (id)sensitiveMediaItemWithTappedBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSArray *axElements; // @synthesize axElements=_axElements;
@property(retain, nonatomic) TFNAttributedTextDrawing *textDrawing; // @synthesize textDrawing=_textDrawing;
@property(copy, nonatomic) CDUnknownBlockType tappedBlock; // @synthesize tappedBlock=_tappedBlock;
- (void).cxx_destruct;
- (void)_activeRangeTapped:(id)arg1;
- (void)_setTextModel:(id)arg1 andRanges:(id)arg2;
- (id)_axElements;
- (int)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
- (void)drawingViewDrawRect:(struct CGRect)arg1;
- (void)cleanup;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

