//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1UsersViewControllerDelegate.h"

@class T1SlideshowUserListViewController, TFNTwitterUser;

@protocol T1SlideshowUserListViewControllerDelegate <T1UsersViewControllerDelegate>

@optional
- (void)slideshowUserListViewController:(T1SlideshowUserListViewController *)arg1 didSelectUser:(TFNTwitterUser *)arg2;
@end

