//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

@class TFNHighlightControl, TFNTwitterStatus, TFNTwitterUser;

__attribute__((visibility("hidden")))
@interface T1SocialProofCell : TFNTableViewCell
{
    TFNHighlightControl *_highlightControl;
    TFNTwitterUser *_primarySocialProofUser;
    TFNTwitterStatus *_status;
    CDUnknownBlockType _socialProofTapActionBlock;
}

+ (float)heightForProofText:(id)arg1 tableWidth:(float)arg2 contentPadding:(struct UIEdgeInsets)arg3;
@property(copy, nonatomic) CDUnknownBlockType socialProofTapActionBlock; // @synthesize socialProofTapActionBlock=_socialProofTapActionBlock;
@property(retain, nonatomic) TFNTwitterStatus *status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)_tapAction;
- (BOOL)_showHighlightControl;
- (void)layoutSubviews;
- (void)cleanup;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

