//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewCell.h"

@class T1SpecializedTweetButton, TFNTwitterStatus, UIViewController<TFNTwitterAuthenticated>;

__attribute__((visibility("hidden")))
@interface T1SpecializedTweetCell : TFNTableViewCell
{
    T1SpecializedTweetButton *button;
    unsigned int _tweetCellType;
}

@property(nonatomic) unsigned int tweetCellType; // @synthesize tweetCellType=_tweetCellType;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic) __weak UIViewController<TFNTwitterAuthenticated> *viewController;
@property(nonatomic) __weak TFNTwitterStatus *status;

@end

