//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class TFNDownload, TFNTwitterEventSportPlayer, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface T1SportEventRowView : UIView
{
    BOOL _hasImage;
    int _style;
    TFNTwitterEventSportPlayer *_player;
    UIImageView *_imageView;
    UILabel *_statusLabel;
    UILabel *_nameLabel;
    UILabel *_scoreLabel;
    TFNDownload *_imageDownload;
}

+ (float)rowHeight;
+ (id)_rowScoreFont;
+ (id)_rowStatusFont;
+ (id)_rowNameFont;
@property(nonatomic) BOOL hasImage; // @synthesize hasImage=_hasImage;
@property(retain, nonatomic) TFNDownload *imageDownload; // @synthesize imageDownload=_imageDownload;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) TFNTwitterEventSportPlayer *player; // @synthesize player=_player;
@property(nonatomic) int style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_imageDownloadStatusDidChange;
- (void)cleanup;
- (void)willDisplay;
- (void)layoutSubviews;
- (void)_update;
- (id)initWithFrame:(struct CGRect)arg1;

@end

