//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNCustomTabBar.h"

#import "TFNCustomTabBarDelegate.h"

@class UIView;

__attribute__((visibility("hidden")))
@interface T1TabbedTimelinesNavigationView : TFNCustomTabBar <TFNCustomTabBarDelegate>
{
    UIView *_topBorder;
    UIView *_bottomBorder;
}

@property(retain, nonatomic) UIView *bottomBorder; // @synthesize bottomBorder=_bottomBorder;
@property(retain, nonatomic) UIView *topBorder; // @synthesize topBorder=_topBorder;
- (void).cxx_destruct;
- (void)_didTapEntryButton:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setTabViews:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <T1TabbedTimelinesNavigationViewDelegate> delegate;

@end

