//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

__attribute__((visibility("hidden")))
@interface T1TFNButtonPlaygroundPerformanceViewController : UITableViewController
{
}

- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)button;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_startTest;
- (void)viewDidLoad;

@end

