//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNViewController.h"

#import "TFNChromeLayout.h"
#import "TFNSwipeViewControllerDataSource.h"
#import "TFNSwipeViewControllerDelegate.h"
#import "TFNTwitterAuthenticated.h"
#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, T1SwipeTitleView, TFNSwipeViewController, TFNTimer, TFNTwitterAccount, UITapGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface T1TimelineSwipeViewController : TFNViewController <TFNSwipeViewControllerDataSource, TFNSwipeViewControllerDelegate, TFNChromeLayout, TFNTwitterAuthenticated, UIGestureRecognizerDelegate>
{
    NSMutableArray *_timelines;
    TFNSwipeViewController *_swipeController;
    T1SwipeTitleView *_swipeTitleView;
    UIView *_swipeTitleContainerView;
    UITapGestureRecognizer *_tapRecognizer;
    int _swipingFromIndex;
    TFNTimer *_unloadUnviewedControllersTimer;
    struct UIEdgeInsets _underChromeInset;
    struct UIEdgeInsets _visibleChromeInset;
    TFNTwitterAccount *_account;
}

@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)tfn_debugStrings;
- (id)scribeSection;
- (id)scribePage;
- (BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)setVisibleChromeInset:(struct UIEdgeInsets)arg1 animated:(BOOL)arg2;
- (void)setUnderChromeInset:(struct UIEdgeInsets)arg1 animated:(BOOL)arg2;
- (void)_scribeNavigationFromIndex:(int)arg1 toViewController:(id)arg2 atIndex:(int)arg3;
- (void)swipeViewController:(id)arg1 didUpdateSwipePosition:(float)arg2;
- (void)swipeViewController:(id)arg1 didUpdateCurrentIndex:(int)arg2;
- (void)swipeViewController:(id)arg1 willUpdateCurrentIndex:(int)arg2;
- (void)_unloadViewControllersNotViewedInTimeInterval:(double)arg1;
- (void)_unloadUnviewedViewControllers;
- (id)swipeViewController:(id)arg1 viewControllerAtIndex:(int)arg2;
- (int)numberOfViewControllersInSwipeViewController:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)prefersStatusBarHidden;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)allPanelViewControllers;
- (id)currentPanelViewController;
- (void)setCurrentPanelIndex:(int)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setCurrentPanel:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (int)currentPanelIndex;
- (id)currentPanelID;
- (int)_insertionIndexForTimeline:(id)arg1;
- (void)_updateTimelineStateFromNotification:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)_timelinesDidChange:(id)arg1;
- (void)_swipeTitleViewTapped:(id)arg1;
@property(readonly, nonatomic) T1SwipeTitleView *swipeTitleView;
- (id)timelines;
- (id)timelinesScrollView;
- (void)dealloc;
- (id)initWithAccount:(id)arg1;
- (void)enableTimelineScribing;
- (void)disableTimelineScribing;
- (struct CGSize)minimumStorkPanelContentSize:(BOOL)arg1;

@end

