//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "T1BasicPushRoute.h"

__attribute__((visibility("hidden")))
@interface T1TopTweetPushRoute : T1BasicPushRoute
{
}

- (id)ambientMessageForPayload:(id)arg1;
- (id)ambientIconForPayload:(id)arg1;
- (id)scribeElementForPayload:(id)arg1;
- (void)routePayload:(id)arg1 context:(int)arg2;
- (void)willRoutePayload:(id)arg1;

@end

