//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNDataViewController.h"

#import "TFNTwitterAuthenticated.h"

@class NSArray, TFNTwitterAccount;

__attribute__((visibility("hidden")))
@interface T1TopStoriesViewController : TFNDataViewController <TFNTwitterAuthenticated>
{
    TFNTwitterAccount *_account;
    float _storyOffset;
    NSArray *_stories;
}

@property(retain, nonatomic) NSArray *stories; // @synthesize stories=_stories;
@property(nonatomic) float storyOffset; // @synthesize storyOffset=_storyOffset;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)indexPathForBackingObject:(id)arg1;
- (id)backingObjectAtIndexPath:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)resetScrollPosition;
- (void)_storyDidUpdate:(id)arg1;
- (void)loadView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)_storiesDidUpdateFromAPI:(id)arg1;
- (void)_storiesDidUpdate:(id)arg1;
- (void)dealloc;
- (id)init;

@end

