//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "T1PanelRootViewController.h"
#import "T1TrendsChangeLocationDelegate.h"
#import "TFNTwitterAuthenticated.h"
#import "UIActionSheetDelegate.h"

@class NSArray, NSDate, NSIndexPath, NSString, T1EventHeaderTableRowAdapter, T1HyperlocalEventTableRowAdapter, T1SportEventTableRowAdapter, T1StatusTableRowAdapter, T1TVEventTableRowAdapter, T1TrendHeaderTableRowAdapter, T1TrendsLocationDataSource, TFNBlockDataViewAdapter, TFNTwitterAccount, TFNTwitterScribeContext, TFNTwitterTrendsStream, TFNTwitterTrendsTimeline;

__attribute__((visibility("hidden")))
@interface T1TrendsViewController : TFNItemsDataViewController <UIActionSheetDelegate, T1TrendsChangeLocationDelegate, TFNTwitterAuthenticated, T1PanelRootViewController>
{
    BOOL _trendsTimelineCompressed;
    BOOL _isRefreshingTrends;
    BOOL _hideChangeLocationOnUpdate;
    BOOL _scrollToTopOnUpdate;
    TFNTwitterAccount *_account;
    NSDate *_lastViewed;
    TFNTwitterTrendsStream *_stream;
    TFNTwitterTrendsTimeline *_timeline;
    TFNTwitterScribeContext *_scribeContext;
    NSIndexPath *_initialPosition;
    T1StatusTableRowAdapter *_statusAdapter;
    T1EventHeaderTableRowAdapter *_eventsHeaderRowAdapter;
    T1TVEventTableRowAdapter *_tvEventAdapter;
    T1SportEventTableRowAdapter *_sportEventAdapter;
    T1HyperlocalEventTableRowAdapter *_hyperlocalEventAdapter;
    TFNBlockDataViewAdapter *_emptyTrendRowAdapter;
    T1TrendHeaderTableRowAdapter *_trendsRowAdapter;
    T1EventHeaderTableRowAdapter *_eventsRowAdapter;
    NSArray *_segmentButtons;
    unsigned int _selectedSegment;
    T1TrendsLocationDataSource *_locationsDataSource;
    NSArray *_currentTrends;
}

@property(nonatomic) BOOL scrollToTopOnUpdate; // @synthesize scrollToTopOnUpdate=_scrollToTopOnUpdate;
@property(nonatomic) BOOL hideChangeLocationOnUpdate; // @synthesize hideChangeLocationOnUpdate=_hideChangeLocationOnUpdate;
@property(nonatomic) BOOL isRefreshingTrends; // @synthesize isRefreshingTrends=_isRefreshingTrends;
@property(retain, nonatomic) NSArray *currentTrends; // @synthesize currentTrends=_currentTrends;
@property(retain, nonatomic) T1TrendsLocationDataSource *locationsDataSource; // @synthesize locationsDataSource=_locationsDataSource;
@property(nonatomic) unsigned int selectedSegment; // @synthesize selectedSegment=_selectedSegment;
@property(retain, nonatomic) NSArray *segmentButtons; // @synthesize segmentButtons=_segmentButtons;
@property(retain, nonatomic) T1EventHeaderTableRowAdapter *eventsRowAdapter; // @synthesize eventsRowAdapter=_eventsRowAdapter;
@property(retain, nonatomic) T1TrendHeaderTableRowAdapter *trendsRowAdapter; // @synthesize trendsRowAdapter=_trendsRowAdapter;
@property(retain, nonatomic) TFNBlockDataViewAdapter *emptyTrendRowAdapter; // @synthesize emptyTrendRowAdapter=_emptyTrendRowAdapter;
@property(retain, nonatomic) T1HyperlocalEventTableRowAdapter *hyperlocalEventAdapter; // @synthesize hyperlocalEventAdapter=_hyperlocalEventAdapter;
@property(retain, nonatomic) T1SportEventTableRowAdapter *sportEventAdapter; // @synthesize sportEventAdapter=_sportEventAdapter;
@property(retain, nonatomic) T1TVEventTableRowAdapter *tvEventAdapter; // @synthesize tvEventAdapter=_tvEventAdapter;
@property(retain, nonatomic) T1EventHeaderTableRowAdapter *eventsHeaderRowAdapter; // @synthesize eventsHeaderRowAdapter=_eventsHeaderRowAdapter;
@property(retain, nonatomic) T1StatusTableRowAdapter *statusAdapter; // @synthesize statusAdapter=_statusAdapter;
@property(copy, nonatomic) NSIndexPath *initialPosition; // @synthesize initialPosition=_initialPosition;
@property(nonatomic, getter=isTrendsTimelineCompressed) BOOL trendsTimelineCompressed; // @synthesize trendsTimelineCompressed=_trendsTimelineCompressed;
@property(retain, nonatomic) TFNTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(retain, nonatomic) TFNTwitterTrendsTimeline *timeline; // @synthesize timeline=_timeline;
@property(retain, nonatomic) TFNTwitterTrendsStream *stream; // @synthesize stream=_stream;
@property(readonly, nonatomic) NSDate *lastViewed; // @synthesize lastViewed=_lastViewed;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)changeLocationViewController:(id)arg1 didSelectLocation:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)_presentChangeLocationController;
- (void)_didSelectGetTailoredTrends;
- (void)didSelectChangeTrendsLocation:(id)arg1;
- (void)_listAvailableLocationsWithResponseBlock:(CDUnknownBlockType)arg1 atLocation:(id)arg2;
- (void)_listAvailableLocationsWithResponseBlock:(CDUnknownBlockType)arg1;
- (id)indexPathForItem:(id)arg1;
- (BOOL)useBlindView;
@property(readonly, nonatomic) NSString *panelID;
- (void)loadTop;
- (BOOL)isLoadingTop;
- (void)logImpressionForEvent:(id)arg1 indexPath:(id)arg2;
- (void)logImpressionForTrend:(id)arg1 indexPath:(id)arg2;
- (id)scribeImpressionParametersForIndexPath:(id)arg1;
- (id)_scribeComponentForItem:(id)arg1;
- (id)scribeComponentForIndexPath:(id)arg1;
- (id)scribeSection;
@property(readonly, nonatomic) NSString *scribePage;
- (id)scribe;
- (id)_viewMoreHyperlocalItem;
- (id)_viewMoreSportsItem;
- (id)_viewMoreTVItem;
- (void)_applySettings:(id)arg1;
- (id)_buildSections;
- (id)_sectionForHyperlocalEvent:(id)arg1;
- (id)_sectionForSportEvent:(id)arg1;
- (id)_sectionForTVEvent:(id)arg1;
- (id)_sectionForTrend:(id)arg1;
- (id)_headerItemForEvent:(id)arg1;
- (void)_updateTrends;
- (void)_updateSections:(id)arg1;
- (void)_refreshTrends;
- (void)_hideChangeLocationIfNecessary;
- (void)_setSegmentItem:(id)arg1 selected:(BOOL)arg2;
- (void)update;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)_trendsDidUpdate;
- (void)didSelectSupplementaryHeaderButton:(id)arg1;
- (void)_presentLocalGuide;
- (void)_presentSportsGuide;
- (void)_presentTVGuide;
- (id)tableViewCellForItem:(id)arg1 atIndexPath:(id)arg2;
- (id)_trendHeaderViewForTrend:(id)arg1 inSection:(int)arg2;
- (id)_eventHeaderViewForEvent:(id)arg1 inSection:(int)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(int)arg3;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (void)_updateTableRowAdapters;
- (id)_trendingHyperlocalEvents;
- (id)_trendingSportsEvents;
- (id)_trendingTvEvents;
- (id)_title;
@property(readonly, nonatomic) BOOL shouldShowDetailListSegmentControl;
- (id)_eventForSection:(int)arg1;
- (id)_trendForSection:(int)arg1;
- (void)_timelineDidFinishDeserialization:(id)arg1;
- (void)_setupStreamFromTimeline;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)prefersStatusBarHidden;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)_segmentItemWithTitle:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)init;

@end

