//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNDrawingTableViewCell.h"

@class TFNImageDrawing, TFNTextDrawing, TFNTwitterTrend;

__attribute__((visibility("hidden")))
@interface T1TrendCell : TFNDrawingTableViewCell
{
    TFNTextDrawing *_trendNameDrawing;
    TFNImageDrawing *_promotedBadgeDrawing;
    TFNTextDrawing *_promotedTextDrawing;
    TFNTextDrawing *_clusterLabelDrawing;
    TFNTwitterTrend *_trend;
}

+ (id)_clusterTextForTrend:(id)arg1;
+ (float)heightForTrend:(id)arg1 tableWidth:(float)arg2;
@property(retain, nonatomic) TFNTwitterTrend *trend; // @synthesize trend=_trend;
- (void).cxx_destruct;
- (void)drawingViewDrawRect:(struct CGRect)arg1;
- (void)cleanup;
- (void)_update;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

