//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTableViewSectionHeaderFooterView.h"

@class T1IconTitleView, TFNTwitterTrend, UIView;

__attribute__((visibility("hidden")))
@interface T1TrendHeaderView : TFNTableViewSectionHeaderFooterView
{
    TFNTwitterTrend *_trend;
    CDUnknownBlockType _tapBlock;
    T1IconTitleView *_iconTitleView;
    UIView *_backgroundHeaderView;
}

+ (id)_clusterTextForTrend:(id)arg1;
+ (id)_socialTextForTrend:(id)arg1;
+ (void)_getTitle:(id *)arg1 subtitle:(id *)arg2 subsubtitle:(id *)arg3 forTrend:(id)arg4;
+ (float)heightForTrend:(id)arg1 tableWidth:(float)arg2;
@property(retain, nonatomic) UIView *backgroundHeaderView; // @synthesize backgroundHeaderView=_backgroundHeaderView;
@property(retain, nonatomic) T1IconTitleView *iconTitleView; // @synthesize iconTitleView=_iconTitleView;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(retain, nonatomic) TFNTwitterTrend *trend; // @synthesize trend=_trend;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_iconTitleTapped:(id)arg1;
- (void)cleanup;
- (void)_update;
- (id)initWithReuseIdentifier:(id)arg1;

@end

