//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, TFNTwitterAccount, TFNTwitterEntityURL, TFNTwitterStatus;

@protocol T1TweetContextActionsDelegate <NSObject>

@optional
- (NSArray *)t1_extraTweetContextActionsForStatus:(TFNTwitterStatus *)arg1 account:(TFNTwitterAccount *)arg2 entityURL:(TFNTwitterEntityURL *)arg3 supportsDismiss:(BOOL)arg4;
@end

