//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsTableRowAdapter.h"

#import "TFNTwitterAuthenticated.h"

@class TFNTwitterAccount, TFNTwitterScribeContext;

__attribute__((visibility("hidden")))
@interface T1TypeaheadUserTableRowAdapter : TFNItemsTableRowAdapter <TFNTwitterAuthenticated>
{
    BOOL _showSocialContext;
    TFNTwitterAccount *_account;
    TFNTwitterScribeContext *_scribeContext;
}

@property(retain, nonatomic) TFNTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(nonatomic) BOOL showSocialContext; // @synthesize showSocialContext=_showSocialContext;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (float)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)_userForTypeaheadUser:(id)arg1;
- (id)init;

@end

