//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNItemsDataViewController.h"

#import "T1PanelRootViewController.h"

@class NSDate, NSMutableArray, NSString, T1StatusTableRowAdapter, TFNTwitterAccount, TFNTwitterUniversalDiscoverTimeline, TFNTwitterUniversalDiscoverTrendsStream;

__attribute__((visibility("hidden")))
@interface T1UniversalDiscoverTimelineViewController : TFNItemsDataViewController <T1PanelRootViewController>
{
    BOOL _didPerformPullToRefreshAction;
    TFNTwitterAccount *_account;
    NSDate *_lastViewed;
    TFNTwitterUniversalDiscoverTrendsStream *_stream;
    TFNTwitterUniversalDiscoverTimeline *_timeline;
    T1StatusTableRowAdapter *_statusAdapter;
    NSMutableArray *_currentlyShownTrends;
}

@property(nonatomic) BOOL didPerformPullToRefreshAction; // @synthesize didPerformPullToRefreshAction=_didPerformPullToRefreshAction;
@property(retain, nonatomic) NSMutableArray *currentlyShownTrends; // @synthesize currentlyShownTrends=_currentlyShownTrends;
@property(retain, nonatomic) T1StatusTableRowAdapter *statusAdapter; // @synthesize statusAdapter=_statusAdapter;
@property(retain, nonatomic) TFNTwitterUniversalDiscoverTimeline *timeline; // @synthesize timeline=_timeline;
@property(retain, nonatomic) TFNTwitterUniversalDiscoverTrendsStream *stream; // @synthesize stream=_stream;
@property(readonly, nonatomic) NSDate *lastViewed; // @synthesize lastViewed=_lastViewed;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)scribeContext;
- (id)scribeSection;
@property(readonly, nonatomic) NSString *scribePage;
- (id)scribe;
- (id)tfn_debugStrings;
- (int)preferredStatusBarUpdateAnimation;
- (BOOL)prefersStatusBarHidden;
- (id)_trendsFooterItem;
- (id)_trendsHeaderItem;
- (id)_trendScribingParameters;
- (void)_scribeTrendsModuleResults;
- (unsigned int)_maxSectionObjectsForClass:(Class)arg1;
- (id)_headerItemForClass:(Class)arg1;
- (id)_footerItemForClass:(Class)arg1;
- (BOOL)_classIsWTFSectionItemClass:(Class)arg1;
- (BOOL)_classIsTrendSectionItemClass:(Class)arg1;
- (BOOL)_classIsTopTweetSectionItemClass:(Class)arg1;
- (void)_scribeShowActionForItem:(id)arg1;
- (void)_timelineDidFinishDeserialization:(id)arg1;
- (id)scrollPositionObjectAtIndexPath:(id)arg1;
- (BOOL)_itemIsDiscoObject:(id)arg1;
- (id)_currentSectionItemForItem:(id)arg1 withSectionCount:(unsigned int)arg2;
- (void)update;
- (BOOL)_shouldAddSectionBreak:(Class)arg1 nextType:(Class)arg2;
- (id)_viewMorePeopleItem;
- (void)_didFollowUser:(id)arg1;
- (void)_streamDidUpdate:(id)arg1;
- (void)_setupStreamFromTimeline;
- (void)_loadFreshTimeline;
- (void)loadTop;
@property(readonly, nonatomic) NSString *panelID;
- (void)willDisplayCell:(id)arg1 forItem:(id)arg2 atIndexPath:(id)arg3;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)dealloc;
- (id)initWithAccount:(id)arg1;

@end

