//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TCActionStyleApplication : NSObject
{
    int _elementIdentifier;
    int _styleIdentifier;
}

@property(nonatomic) int styleIdentifier; // @synthesize styleIdentifier=_styleIdentifier;
@property(nonatomic) int elementIdentifier; // @synthesize elementIdentifier=_elementIdentifier;
- (id)description;

@end

