//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TCPlayerInstance.h"

#import "TFNTwitterAmplifyPlayerDelegate.h"

@class TFNTwitterAmplifyPlayer;

@interface TCAmplifyPlayerInstance : TCPlayerInstance <TFNTwitterAmplifyPlayerDelegate>
{
    TFNTwitterAmplifyPlayer *_player;
}

@property(readonly, nonatomic) TFNTwitterAmplifyPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (id)amplifyPlayer:(id)arg1 retweetActionSheetForStatus:(id)arg2 withDoneBlock:(CDUnknownBlockType)arg3 willQuoteRetweetBlock:(CDUnknownBlockType)arg4;
- (id)amplifyPlayer:(id)arg1 moreActionSheetForStatus:(id)arg2 willPresentControllerBlock:(CDUnknownBlockType)arg3;
- (void)amplifyPlayer:(id)arg1 displayRelatedVideoTimelineWithStatus:(id)arg2;
- (void)amplifyPlayer:(id)arg1 displayComposerWithComposition:(id)arg2;
- (void)amplifyPlayerPlaylistDidLoad:(id)arg1;
- (void)amplifyPlayerPlaybackDidStart:(id)arg1;
- (id)tweetForAmplifyPlayer:(id)arg1;
- (id)scribeBaseParametersForAmplifyPlayer:(id)arg1;
- (id)inlineParentViewForAmplifyPlayer:(id)arg1;
- (struct CGRect)inlineFrameForAmplifyPlayer:(id)arg1;
- (void)amplifyPlayer:(id)arg1 attachPlayerView:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (BOOL)amplifyPlayerShouldSkipAds:(id)arg1;
- (BOOL)amplifyPlayerShouldPlayInlineOnly:(id)arg1;
- (id)accountForAmplifyPlayer:(id)arg1;
- (void)unpauseIfAppropriate;
- (void)dispose;
- (void)pause;
- (id)initWithDocument:(id)arg1 element:(id)arg2 sourceURL:(id)arg3;

@end

