//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TCVector4;

@interface TCBorder : NSObject
{
    TCVector4 *_color;
    float _width;
}

@property(nonatomic) float width; // @synthesize width=_width;
@property(retain, nonatomic) TCVector4 *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (BOOL)isOpaque;
- (BOOL)isVisible;

@end

