//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TCBuildableDocument.h"
#import "TCResourceLoaderDelegate.h"

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, TCCardState, TCElement, TCInstanceValueProvider, TCResourceLoader, TCRootContainer, TFNBarButtonItem, TFNToolbar, TFNTwitterAmplifyPlayer, TFNTwitterHTTPRequest, UIView;

@interface TCCardInstance : NSObject <TCBuildableDocument, TCResourceLoaderDelegate>
{
    TCInstanceValueProvider *_instanceValueProvider;
    TCRootContainer *_rootContainer;
    NSDictionary *_elementsByID;
    NSDictionary *_actionsByID;
    NSDictionary *_apiRequestParametersByID;
    NSDictionary *_purchaseRequestParametersByID;
    int _onLoadActionID;
    NSDictionary *_tokenizedTextsByID;
    NSMutableSet *_tokenGroupIDsToDisplay;
    NSMutableDictionary *_textTokenStringsByID;
    NSDictionary *_textElementsByTokenGroupID;
    NSDictionary *_textElementsByTokenID;
    NSDictionary *_stylesByID;
    NSArray *_bindings;
    NSDictionary *_formsByID;
    TCResourceLoader *_resourceLoader;
    NSArray *_playerInstances;
    BOOL _haveCreatedPlayerInstances;
    TCElement *_highlightedElement;
    UIView *_highlightView;
    TFNTwitterHTTPRequest *_inFlightHTTPRequest;
    TFNToolbar *_textInputAccessoryToolbar;
    TFNBarButtonItem *_prevButtonItem;
    TFNBarButtonItem *_nextButtonItem;
    BOOL _performDelayedOnLoadAction;
    BOOL _isStateModified;
    BOOL _shouldCacheState;
    BOOL _enqueuedSizeMayChange;
    int _mode;
    NSArray *_valueProviders;
    NSString *_cardName;
    id <TCCardInstanceDelegate> _delegate;
    NSArray *_accessibilityElements;
    NSMutableArray *_errors;
    NSMutableArray *_warnings;
}

+ (id)cardInstanceFromCompiledCard:(id)arg1 valueProviders:(id)arg2 errorDescription:(id *)arg3 warnings:(id *)arg4 delegate:(id)arg5 mode:(int)arg6 state:(id)arg7;
+ (id)cardInstanceFromCompiledCard:(id)arg1 valueProviders:(id)arg2 errorDescription:(id *)arg3 warnings:(id *)arg4 delegate:(id)arg5 mode:(int)arg6;
+ (int)_i18nPluralTypeOfString:(id)arg1;
+ (BOOL)_isValidDeepLinkURL:(id)arg1;
+ (BOOL)_isOpenableURL:(id)arg1 forAppDeepLink:(BOOL)arg2;
@property(nonatomic) BOOL enqueuedSizeMayChange; // @synthesize enqueuedSizeMayChange=_enqueuedSizeMayChange;
@property(retain, nonatomic) NSMutableArray *warnings; // @synthesize warnings=_warnings;
@property(retain, nonatomic) NSMutableArray *errors; // @synthesize errors=_errors;
@property(copy, nonatomic) NSArray *accessibilityElements; // @synthesize accessibilityElements=_accessibilityElements;
@property(nonatomic) BOOL shouldCacheState; // @synthesize shouldCacheState=_shouldCacheState;
@property(nonatomic) __weak id <TCCardInstanceDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *cardName; // @synthesize cardName=_cardName;
@property(retain, nonatomic) NSArray *valueProviders; // @synthesize valueProviders=_valueProviders;
@property(readonly, nonatomic) int mode; // @synthesize mode=_mode;
- (void).cxx_destruct;
@property(readonly, nonatomic) TFNTwitterAmplifyPlayer *amplifyPlayer;
@property(readonly, nonatomic) TCCardState *state;
- (id)account;
- (id)followButtonScribeContext:(id)arg1;
- (id)tweetForAmplifyPlayer:(id)arg1;
- (id)scribeBaseParametersForAmplifyPlayer:(id)arg1;
- (id)presentingViewControllerForAmplifyPlayer:(id)arg1;
- (id)amplifyPlayer:(id)arg1 retweetActionSheetForStatus:(id)arg2 withDoneBlock:(CDUnknownBlockType)arg3 willQuoteRetweetBlock:(CDUnknownBlockType)arg4;
- (id)amplifyPlayer:(id)arg1 moreActionSheetForStatus:(id)arg2 willPresentControllerBlock:(CDUnknownBlockType)arg3;
- (void)amplifyPlayer:(id)arg1 displayRelatedVideoTimelineWithStatus:(id)arg2;
- (void)amplifyPlayer:(id)arg1 displayComposerWithComposition:(id)arg2;
- (BOOL)_performPurchaseRequestAction:(id)arg1;
- (BOOL)_isRevenueCardURL:(id)arg1;
- (void)_performActionWithID:(int)arg1 onElement:(id)arg2;
- (BOOL)_updateWithResponseRawBindings:(id)arg1;
- (void)_handleResponse:(id)arg1 forAPIRequest:(id)arg2;
- (BOOL)_performAPIRequestAction:(id)arg1 withAdditionalParameters:(id)arg2;
- (void)_textInputDone:(id)arg1;
- (void)_textInputNext:(id)arg1;
- (void)_textInputPrevious:(id)arg1;
- (id)_formFieldsShowingText;
- (void)_updateTextInputAccessoryToolbarWithActiveFormField:(id)arg1;
- (id)_textInputToolbarItems;
- (void)formFieldDidPressReturn:(id)arg1;
- (void)formFieldDidEndEditing:(id)arg1;
- (void)formFieldDidBeginEditing:(id)arg1;
- (id)textInputAccessoryView;
- (id)stringForAction:(id)arg1;
- (int)playerTypeForVideoURL:(id)arg1;
- (void)_openHTMLURLForPlayerElement:(id)arg1;
- (void)playerInstanceDidFailToPlay:(id)arg1;
- (void)playerInstanceDidPlay:(id)arg1;
- (void)playElement:(id)arg1;
- (id)tokenizedAttributedStringWithIdentifier:(int)arg1;
- (id)formWithIdentifier:(int)arg1;
- (id)styleWithIdentifier:(int)arg1;
- (void)_performSubmitFormAction:(id)arg1;
- (BOOL)_validateSubmitFormAction:(id)arg1;
- (BOOL)_performStylesAction:(id)arg1;
- (void)_performAction:(id)arg1 onElement:(id)arg2 withContext:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_performAction:(id)arg1 onElement:(id)arg2 withContext:(id)arg3;
- (void)performAction:(id)arg1 onElement:(id)arg2;
- (id)purchaseRequestParameterWithIdentifier:(int)arg1;
- (id)apiRequestParameterWithIdentifier:(int)arg1;
- (id)actionWithIdentifier:(int)arg1;
- (float)adjustedFontSizeForSize:(float)arg1;
- (void)elementNeedsUpdate;
- (void)rootElementSizeMayChange;
- (void)removeHighlightOnElement:(id)arg1;
- (void)addHighlightOnElement:(id)arg1;
- (void)loadImageForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadDataForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addWarningWithFormat:(id)arg1;
- (void)addWarning:(id)arg1;
- (void)addErrorWithFormat:(id)arg1;
- (void)addError:(id)arg1;
- (void)_finishedBuildingWithInvalidation:(BOOL)arg1;
- (void)finishedBuilding;
- (void)didUnpackForms:(id)arg1;
- (void)didUnpackBindings:(id)arg1;
- (void)didUnpackStyles:(id)arg1;
- (void)didBindString:(id)arg1 toTextTokenID:(int)arg2 withInvalidation:(BOOL)arg3;
- (void)didBindBool:(BOOL)arg1 toTextTokenGroupID:(int)arg2 withInvalidation:(BOOL)arg3;
- (void)_generateTextElementMaps;
- (id)_textElementsByTokenID;
- (id)_textElementsByTokenGroupID;
- (void)didUnpackTokenizedTexts:(id)arg1;
- (void)performPendingOnLoadAction;
- (void)setOnLoadActionID:(int)arg1;
- (void)didUnpackActions:(id)arg1;
- (id)elementWithIdentifier:(int)arg1;
- (void)didUnpackRootContainer;
- (id)rootContainer;
- (void)didUnpackCardName:(id)arg1;
- (id)userWithID:(long long)arg1;
- (id)_createPlayerInstances;
- (int)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(int)arg1;
- (int)accessibilityElementCount;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (id)playerView;
- (id)slideshowSourceElements;
- (void)layoutInRect:(struct CGRect)arg1;
- (float)measureHeight:(float)arg1;
- (void)removeView;
- (void)addViewAsSubviewOfView:(id)arg1;
- (void)dispose;
- (void)prepareForReuse;
- (void)_setValueProviders:(id)arg1 state:(id)arg2;
- (void)rebuildCardWithValueProviders:(id)arg1 state:(id)arg2;
- (id)initWithValueProviders:(id)arg1 mode:(int)arg2 state:(id)arg3;
- (void)setDestinationValue:(id)arg1 forBinding:(id)arg2 withInvalidation:(BOOL)arg3;
- (void)setValue:(id)arg1 ofActionProperty:(id)arg2 forBinding:(id)arg3;
- (void)setValue:(id)arg1 forPlayerElementProperty:(id)arg2 ofType:(int)arg3 forBinding:(id)arg4 withInvalidation:(BOOL)arg5;
- (void)setValue:(id)arg1 forPlayerElementStreamSizeWidthOrHeight:(BOOL)arg2 forBinding:(id)arg3 withInvalidation:(BOOL)arg4;
- (void)setValue:(id)arg1 forPlayerElementStreamProperty:(id)arg2 ofType:(int)arg3 forBinding:(id)arg4 withInvalidation:(BOOL)arg5;
- (id)destinationElementOfClass:(Class)arg1 forBinding:(id)arg2;
- (id)coerceValue:(id)arg1 toDestinationType:(int)arg2 forBinding:(id)arg3;
- (id)processedValueForCondition:(BOOL)arg1 binding:(id)arg2;
- (id)processedValueForSourceValue:(id)arg1 binding:(id)arg2;
- (id)sourceValueForBinding:(id)arg1;
- (void)applyBinding:(id)arg1 withInvalidation:(BOOL)arg2;

@end

