//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSAttributedString, NSDictionary, NSString, TCAction, TCActionAPIRequestParameter, TCActionPurchaseRequestParameter, TCElement, TCFollowButton, TCForm, TCFormFieldShowingText, TCPlayer, TCPlayerInstance, TCStyle, TFNActionSheetController, TFNTwitterAccount, TFNTwitterAmplifyPlayer, TFNTwitterComposition, TFNTwitterScribeContext, TFNTwitterStatus, UIView, UIViewController;

@protocol TCDocument <NSObject>
- (TFNTwitterScribeContext *)followButtonScribeContext:(TCFollowButton *)arg1;
- (TFNTwitterStatus *)tweetForAmplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1;
- (NSDictionary *)scribeBaseParametersForAmplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1;
- (UIViewController *)presentingViewControllerForAmplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1;
- (TFNActionSheetController *)amplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1 retweetActionSheetForStatus:(TFNTwitterStatus *)arg2 withDoneBlock:(void (^)(void))arg3 willQuoteRetweetBlock:(void (^)(void (^)(void)))arg4;
- (TFNActionSheetController *)amplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1 moreActionSheetForStatus:(TFNTwitterStatus *)arg2 willPresentControllerBlock:(void (^)(void (^)(void)))arg3;
- (void)amplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1 displayRelatedVideoTimelineWithStatus:(TFNTwitterStatus *)arg2;
- (void)amplifyPlayer:(TFNTwitterAmplifyPlayer *)arg1 displayComposerWithComposition:(TFNTwitterComposition *)arg2;
- (TFNTwitterAccount *)account;
- (int)mode;
- (void)formFieldDidPressReturn:(TCFormFieldShowingText *)arg1;
- (void)formFieldDidEndEditing:(TCFormFieldShowingText *)arg1;
- (void)formFieldDidBeginEditing:(TCFormFieldShowingText *)arg1;
- (UIView *)textInputAccessoryView;
- (int)playerTypeForVideoURL:(NSString *)arg1;
- (void)setAccessibilityElements:(NSArray *)arg1;
- (void)playerInstanceDidFailToPlay:(TCPlayerInstance *)arg1;
- (void)playerInstanceDidPlay:(TCPlayerInstance *)arg1;
- (void)playElement:(TCPlayer *)arg1;
- (NSAttributedString *)tokenizedAttributedStringWithIdentifier:(int)arg1;
- (TCForm *)formWithIdentifier:(int)arg1;
- (TCStyle *)styleWithIdentifier:(int)arg1;
- (void)performAction:(TCAction *)arg1 onElement:(TCElement *)arg2;
- (TCActionPurchaseRequestParameter *)purchaseRequestParameterWithIdentifier:(int)arg1;
- (TCActionAPIRequestParameter *)apiRequestParameterWithIdentifier:(int)arg1;
- (TCAction *)actionWithIdentifier:(int)arg1;
- (float)adjustedFontSizeForSize:(float)arg1;
- (void)elementNeedsUpdate;
- (void)rootElementSizeMayChange;
- (void)removeHighlightOnElement:(TCElement *)arg1;
- (void)addHighlightOnElement:(TCElement *)arg1;
- (void)loadImageForURL:(NSString *)arg1 completion:(void (^)(UIImage *))arg2;
- (void)loadDataForURL:(NSString *)arg1 completion:(void (^)(NSData *))arg2;
@end

