//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TCFormField.h"

@class NSString, TCVector4, UIColor, UIFont;

@interface TCFormFieldShowingText : TCFormField
{
    BOOL _fontBold;
    BOOL _fontItalic;
    BOOL _fontUnderline;
    NSString *_fontName;
    float _fontSize;
    TCVector4 *_color;
}

+ (id)_fontsByNameAndType;
+ (id)_fontNameWithBaseName:(id)arg1 bold:(BOOL)arg2 italic:(BOOL)arg3;
@property(retain, nonatomic) TCVector4 *color; // @synthesize color=_color;
@property(nonatomic) BOOL fontUnderline; // @synthesize fontUnderline=_fontUnderline;
@property(nonatomic) BOOL fontItalic; // @synthesize fontItalic=_fontItalic;
@property(nonatomic) BOOL fontBold; // @synthesize fontBold=_fontBold;
@property(nonatomic) float fontSize; // @synthesize fontSize=_fontSize;
@property(copy, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
- (void).cxx_destruct;
- (id)_styledColor;
- (float)_styledFontSize;
- (id)_styledFontName;
- (BOOL)_styledFontUnderline;
- (BOOL)_styledFontItalic;
- (BOOL)_styledFontBold;
- (int)sizingStyleMask;
- (id)backstopValueForStyleProperty:(int)arg1;
- (void)beginEditing;
- (BOOL)isEditing;
@property(readonly, nonatomic) UIColor *textColor;
@property(readonly, nonatomic) UIFont *font;

@end

