//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TCContainer.h"

@interface TCRootContainer : TCContainer
{
}

+ (Class)viewClass;
- (void)_updateAccessibility;
- (void)_voiceOverStatusChanged:(id)arg1;
- (void)updateView;
- (void)invalidateLayoutIncludingSize:(BOOL)arg1;
- (void)configureView;
- (void)dispose;

@end

