//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface TCTokenizedText : NSObject
{
    int _identifier;
    NSArray *_tokenGroups;
}

@property(retain, nonatomic) NSArray *tokenGroups; // @synthesize tokenGroups=_tokenGroups;
@property(nonatomic) int identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)description;

@end

