//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface TFNActionSheetButton : NSObject
{
    BOOL _delaysAction;
    NSString *_title;
    CDUnknownBlockType _action;
    int _style;
}

+ (id)_buttonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2 style:(int)arg3 delaysAction:(BOOL)arg4;
+ (id)cancelButtonWithTitle:(id)arg1;
+ (id)cancelButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)destructiveButtonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)buttonWithTitle:(id)arg1 delayedAction:(CDUnknownBlockType)arg2;
+ (id)buttonWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
@property(nonatomic) BOOL delaysAction; // @synthesize delaysAction=_delaysAction;
@property(nonatomic) int style; // @synthesize style=_style;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

