//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TFNAccessibilityElement;

@protocol TFNAccessibilityElementDelegate <NSObject>
- (struct CGRect)accessibilityFrameForElement:(TFNAccessibilityElement *)arg1;
- (unsigned long long)accessibilityTraitsForElement:(TFNAccessibilityElement *)arg1;
- (NSString *)accessibilityHintForElement:(TFNAccessibilityElement *)arg1;
- (NSString *)accessibilityValueForElement:(TFNAccessibilityElement *)arg1;
- (NSString *)accessibilityLabelForElement:(TFNAccessibilityElement *)arg1;
- (BOOL)isAccessibilityElement:(TFNAccessibilityElement *)arg1;
@end

