//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNSampler.h"

@class TFNBatterySample, UIDevice;

@interface TFNBatterySampler : TFNSampler
{
    UIDevice *_device;
}

- (void).cxx_destruct;
- (id)_sampleFromDevice;
@property(readonly, nonatomic) double averageDrainRate;
@property(readonly, nonatomic) TFNBatterySample *lastSample;
@property(readonly, nonatomic) TFNBatterySample *firstSample;
- (id)sample;
- (void)didStop;
- (void)willStart;
- (id)init;

@end

