//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, TFNDataViewController, UISwitch;

@interface TFNBooleanItem : NSObject
{
    UISwitch *_switch;
    TFNDataViewController *_controller;
    NSDictionary *_options;
    BOOL _value;
    BOOL _multipleTextLines;
    BOOL _multipleDetailTextLines;
    int _style;
    NSString *_text;
    NSString *_detailText;
    CDUnknownBlockType _updateAction;
}

+ (id)tfn_defaultDataViewAdapter;
@property(copy, nonatomic) CDUnknownBlockType updateAction; // @synthesize updateAction=_updateAction;
@property(nonatomic) BOOL multipleDetailTextLines; // @synthesize multipleDetailTextLines=_multipleDetailTextLines;
@property(nonatomic) BOOL multipleTextLines; // @synthesize multipleTextLines=_multipleTextLines;
@property(nonatomic) BOOL value; // @synthesize value=_value;
@property(copy, nonatomic) NSString *detailText; // @synthesize detailText=_detailText;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) int style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_invokeUpdateActionForTableViewController:(id)arg1 options:(id)arg2 indexPath:(id)arg3;
- (void)_switchAction:(id)arg1;
- (id)_switchForTableViewController:(id)arg1 options:(id)arg2;
- (void)setUpdateTarget:(id)arg1 action:(SEL)arg2;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 text:(id)arg2 value:(BOOL)arg3 updateTarget:(id)arg4 action:(SEL)arg5;
- (id)initWithStyle:(int)arg1 text:(id)arg2 value:(BOOL)arg3 updateAction:(CDUnknownBlockType)arg4;

@end

