//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TFNDataViewCellLayout : NSObject
{
    id <NSCopying> _objectIdentifier;
    struct CGSize _size;
}

+ (id)cellLayoutForDataView:(id)arg1 atIndexPath:(id)arg2 objectIdentifier:(id)arg3 initialization:(CDUnknownBlockType)arg4;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) id <NSCopying> objectIdentifier; // @synthesize objectIdentifier=_objectIdentifier;
- (void).cxx_destruct;
- (struct CGRect)offset:(struct CGRect)arg1 for:(struct CGRect)arg2;

@end

