//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TFNDatabaseConnection;

@interface TFNDatabaseStatement : NSObject
{
    TFNDatabaseConnection *_connection;
    struct sqlite3_stmt *_handle;
    NSString *_sql;
}

@property(readonly, nonatomic) NSString *sql; // @synthesize sql=_sql;
@property(readonly, nonatomic) struct sqlite3_stmt *handle; // @synthesize handle=_handle;
- (void).cxx_destruct;
- (BOOL)isNullForIndex:(int)arg1;
- (id)stringForIndex:(int)arg1;
- (id)dataForIndex:(int)arg1;
- (id)dateForIndex:(int)arg1;
- (double)doubleForIndex:(int)arg1;
- (long long)longLongForIndex:(int)arg1;
- (int)integerForIndex:(int)arg1;
- (BOOL)boolForIndex:(int)arg1;
- (void)bindNullForIndex:(int)arg1;
- (void)bindString:(id)arg1 forIndex:(int)arg2;
- (void)bindData:(id)arg1 forIndex:(int)arg2;
- (void)bindDate:(id)arg1 forIndex:(int)arg2;
- (void)bindDouble:(double)arg1 forIndex:(int)arg2;
- (void)bindLongLong:(long long)arg1 forIndex:(int)arg2;
- (void)bindInteger:(int)arg1 forIndex:(int)arg2;
- (void)bindBool:(int)arg1 forIndex:(int)arg2;
- (void)close;
- (void)reset;
- (int)step;
- (id)_connection;
@property(readonly, nonatomic) int resultSetColumnCount;
@property(readonly, nonatomic) int parameterCount;
@property(readonly, nonatomic) BOOL isValid;
- (void)dealloc;
- (id)initWithConnection:(id)arg1 sql:(id)arg2 error:(id *)arg3;

@end

