//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNCollectionViewCell.h"

#import "TFNFormTextFieldDelegate.h"

@class CAShapeLayer, TFNFormField, TFNFormFieldErrorView, TFNFormTextField, UIImageView, UILabel, UIView;

@interface TFNFormFieldCell : TFNCollectionViewCell <TFNFormTextFieldDelegate>
{
    int _sectionBreaks;
    float _previousErrorHeight;
    BOOL _showingError;
    BOOL _animating;
    UIImageView *_backgroundView;
    TFNFormField *_formField;
    id <TFNFormFieldCellDelegate> _delegate;
    UILabel *_titleLabel;
    UIView *_separatorCoverView;
    TFNFormTextField *_textField;
    TFNFormFieldErrorView *_errorView;
    CAShapeLayer *_arrowLayer;
}

+ (float)heightForFormField:(id)arg1 withWidth:(float)arg2;
@property(nonatomic, getter=isAnimating) BOOL animating; // @synthesize animating=_animating;
@property(nonatomic, getter=isShowingError) BOOL showingError; // @synthesize showingError=_showingError;
@property(readonly, nonatomic) CAShapeLayer *arrowLayer; // @synthesize arrowLayer=_arrowLayer;
@property(readonly, nonatomic) TFNFormFieldErrorView *errorView; // @synthesize errorView=_errorView;
@property(readonly, nonatomic) TFNFormTextField *textField; // @synthesize textField=_textField;
@property(readonly, nonatomic) UIView *separatorCoverView; // @synthesize separatorCoverView=_separatorCoverView;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <TFNFormFieldCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNFormField *formField; // @synthesize formField=_formField;
@property(readonly, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void).cxx_destruct;
- (BOOL)shouldShowError:(id)arg1;
- (void)textField:(id)arg1 willChangeValidityToShowError:(BOOL)arg2;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)willDisplayWithSectionBreaks:(int)arg1 inDataViewController:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)becomeFirstResponder;
- (void)dealloc;
- (void)_layoutArrowLayer;
- (void)_layoutErrorView;
- (void)_layoutText;
- (void)_layoutSeparatorCoverView;
- (void)_layoutBackgroundView;
- (void)_animateErrorViewMaskToShowError:(BOOL)arg1;
- (void)_animateToShowError:(BOOL)arg1;
- (void)_addErrorViewMaskWithOffset:(float)arg1;
- (void)_dependedOnFormFieldInputDidChange;
- (void)_validateFormFieldWithTextField:(id)arg1 editing:(BOOL)arg2 began:(BOOL)arg3;
@property(readonly, nonatomic) BOOL hasFloatingTitle;
@property(readonly, nonatomic) BOOL hasInlineTitle;
@property(readonly, nonatomic) BOOL hasTitle;

@end

