//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, UIColor;

@interface TFNFormAppearance : NSObject
{
    NSMutableDictionary *_fieldBackgroundImages;
    BOOL _insetSeparator;
    BOOL _fullWidth;
    BOOL _overlapped;
    float _margin;
    float _lineSpacing;
    float _fieldSpacing;
    float _fieldBorderWidth;
    float _fieldCornerRadius;
    UIColor *_backgroundColor;
    UIColor *_borderColor;
    struct UIEdgeInsets _sectionInset;
}

+ (id)insetAppearanceOverlapped:(BOOL)arg1 insetSeparator:(BOOL)arg2;
+ (id)fullWidthAppearanceInsetSeparator:(BOOL)arg1;
@property(readonly, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic, getter=isOverlapped) BOOL overlapped; // @synthesize overlapped=_overlapped;
@property(nonatomic, getter=isFullWidth) BOOL fullWidth; // @synthesize fullWidth=_fullWidth;
@property(nonatomic) BOOL insetSeparator; // @synthesize insetSeparator=_insetSeparator;
@property(readonly, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) struct UIEdgeInsets sectionInset; // @synthesize sectionInset=_sectionInset;
@property(nonatomic) float fieldCornerRadius; // @synthesize fieldCornerRadius=_fieldCornerRadius;
@property(nonatomic) float fieldBorderWidth; // @synthesize fieldBorderWidth=_fieldBorderWidth;
@property(nonatomic) float fieldSpacing; // @synthesize fieldSpacing=_fieldSpacing;
@property(nonatomic) float lineSpacing; // @synthesize lineSpacing=_lineSpacing;
@property(nonatomic) float margin; // @synthesize margin=_margin;
- (void).cxx_destruct;
- (id)init;
- (id)fieldBackgroundImageForSectionBreaks:(int)arg1;

@end

