//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNDrawing.h"

@class UIColor, UIImage;

@interface TFNImageDrawing : TFNDrawing
{
    UIColor *_placeholderColor;
    UIImage *_image;
    UIImage *_highlightedImage;
    int _contentMode;
}

+ (Class)animationViewClass;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(nonatomic) int contentMode; // @synthesize contentMode=_contentMode;
@property(retain, nonatomic) UIImage *highlightedImage; // @synthesize highlightedImage=_highlightedImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)animationView;
- (unsigned long long)accessibilityTraits;
- (void)drawContent:(struct CGContext *)arg1 highlighted:(BOOL)arg2;
- (id)backgroundColorHighlighted:(BOOL)arg1;
- (struct CGRect)imageFrame;
- (id)init;

@end

