//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString, TFNLegacyForm;

@interface TFNLegacyFormSection : NSObject
{
    NSString *title;
    TFNLegacyForm *form;
    NSArray *fields;
    NSMutableArray *concreteFields;
}

+ (id)sectionWithTitle:(id)arg1 fields:(id)arg2;
@property(readonly, nonatomic) NSMutableArray *concreteFields; // @synthesize concreteFields;
@property(retain, nonatomic) NSArray *fields; // @synthesize fields;
@property(nonatomic) __weak TFNLegacyForm *form; // @synthesize form;
@property(copy, nonatomic) NSString *title; // @synthesize title;
- (void).cxx_destruct;

@end

