//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNNewDirectMessageAbstractEvent.h"

@interface TFNNewDirectMessageConversationLeftEvent : TFNNewDirectMessageAbstractEvent
{
}

- (void)performUpdatesWithModel:(id)arg1;
- (int)eventType;

@end

