//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNNewDirectMessageAttachment.h"

#import "NSCoding.h"

@class TFNMediaAssetImage, UIImage;

@interface TFNNewDirectMessagePhotoAttachment : TFNNewDirectMessageAttachment <NSCoding>
{
    TFNMediaAssetImage *_mediaAssetImage;
}

@property(retain, nonatomic) TFNMediaAssetImage *mediaAssetImage; // @synthesize mediaAssetImage=_mediaAssetImage;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIImage *photo;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

