//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface TFNPaddedButton : UIButton
{
    struct UIEdgeInsets _backgroundImageInsets;
}

@property(nonatomic) struct UIEdgeInsets backgroundImageInsets; // @synthesize backgroundImageInsets=_backgroundImageInsets;
- (void)sizeToFit;
- (struct CGRect)backgroundRectForBounds:(struct CGRect)arg1;

@end

