//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface TFNPreferenceItem : NSObject
{
    NSString *_title;
    NSString *_userDefaultsKey;
    NSArray *_titles;
    NSArray *_values;
    NSString *_footerText;
    CDUnknownBlockType _updateAction;
    id _defaultValue;
    id _previousValue;
}

+ (id)tfn_defaultDataViewAdapter;
@property(readonly, nonatomic) id previousValue; // @synthesize previousValue=_previousValue;
@property(retain, nonatomic) id defaultValue; // @synthesize defaultValue=_defaultValue;
@property(copy, nonatomic) CDUnknownBlockType updateAction; // @synthesize updateAction=_updateAction;
@property(copy, nonatomic) NSString *footerText; // @synthesize footerText=_footerText;
@property(retain, nonatomic) NSArray *values; // @synthesize values=_values;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(copy, nonatomic) NSString *userDefaultsKey; // @synthesize userDefaultsKey=_userDefaultsKey;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)valueSelectionViewControllerForTableViewController:(id)arg1 withOptions:(id)arg2 atIndexPath:(id)arg3;
@property(readonly, nonatomic) id value;
- (void)setUpdateTarget:(id)arg1 action:(SEL)arg2;
- (id)initWithTitle:(id)arg1 userDefaultsKey:(id)arg2 titles:(id)arg3 values:(id)arg4 defaultValue:(id)arg5 updateTarget:(id)arg6 action:(SEL)arg7;
- (id)initWithTitle:(id)arg1 userDefaultsKey:(id)arg2 titles:(id)arg3 values:(id)arg4 defaultValue:(id)arg5 updateAction:(CDUnknownBlockType)arg6;

@end

