//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol TFNPresented <NSObject>

@optional
- (void)dismissAnimated:(BOOL)arg1 completion:(void (^)(void))arg2;
- (void)presentFromViewController:(UIViewController *)arg1 animated:(BOOL)arg2 completion:(void (^)(void))arg3;
@end

