//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, TFNPressTouchDetector, UIEvent;

@protocol TFNPressTouchDetectorDelegate <NSObject>

@optional
- (void)pressTouchDetector:(TFNPressTouchDetector *)arg1 pressEnded:(NSSet *)arg2 withEvent:(UIEvent *)arg3 forGestureType:(int)arg4;
- (BOOL)pressTouchDetector:(TFNPressTouchDetector *)arg1 allowsLongPress:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)pressTouchDetector:(TFNPressTouchDetector *)arg1 pressBegan:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
@end

