//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSMutableDictionary;

@interface TFNRailView : UIScrollView <UIScrollViewDelegate>
{
    double _lastScrollTimes[5];
    float _lastScrollOffsets[5];
    id <TFNRailViewDataSource> _datasource;
    float _contentViewSpacing;
    float _contentViewWidth;
    int _velocity;
    NSMutableArray *_visibleViews;
    NSMutableDictionary *_reusableViewCache;
}

+ (float)defaultContentViewSpacing;
@property(retain, nonatomic) NSMutableDictionary *reusableViewCache; // @synthesize reusableViewCache=_reusableViewCache;
@property(retain, nonatomic) NSMutableArray *visibleViews; // @synthesize visibleViews=_visibleViews;
@property(readonly, nonatomic) int velocity; // @synthesize velocity=_velocity;
@property(nonatomic) float contentViewWidth; // @synthesize contentViewWidth=_contentViewWidth;
@property(nonatomic) float contentViewSpacing; // @synthesize contentViewSpacing=_contentViewSpacing;
@property(nonatomic) __weak id <TFNRailViewDataSource> datasource; // @synthesize datasource=_datasource;
- (void).cxx_destruct;
- (void)_cleanupAllVisibleViews;
- (void)cleanup;
- (void)reloadData;
- (void)_updateScrollVelocity;
- (void)didEndScrolling;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (BOOL)touchesShouldCancelInContentView:(id)arg1;
- (id)dequeueRailContentViewOfType:(Class)arg1;
- (void)_addReusableContentView:(id)arg1;
- (id)_reuseArrayForId:(id)arg1;
- (void)layoutSubviews;
- (void)scrollToColumn:(int)arg1 animated:(BOOL)arg2;
- (id)viewAtColumn:(int)arg1;
- (struct CGRect)rectForViewAtColumn:(int)arg1;
- (struct _NSRange)visibleRange;
- (id)init;

@end

