//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface TFNSlicedItem : NSObject
{
    int highlightedIndex;
    NSArray *_segments;
}

+ (id)slicedItemWithSegments:(id)arg1;
@property(retain, nonatomic) NSArray *segments; // @synthesize segments=_segments;
- (void).cxx_destruct;
- (id)init;

@end

