//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNStaticTableViewElement.h"

@class NSString;

@interface TFNStaticTableViewLabelElement : TFNStaticTableViewElement
{
    NSString *labelText;
    BOOL contactStyleLabel;
}

@property(nonatomic) BOOL contactStyleLabel; // @synthesize contactStyleLabel;
@property(copy, nonatomic) NSString *labelText; // @synthesize labelText;
- (void).cxx_destruct;
- (id)cellForTableView:(id)arg1;
- (BOOL)isSelectable;

@end

