//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TFNStopwatch : NSObject
{
    double _intervalStart;
}

@property(nonatomic) double intervalStart; // @synthesize intervalStart=_intervalStart;
- (double)timeInterval;
- (id)init;

@end

