//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TFNSecurityKey : NSObject
{
}

+ (BOOL)delloginVericiationEnabledForUser:(long long)arg1 withServiceName:(id)arg2;
+ (BOOL)setsloginVerificationEnabled:(BOOL)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (BOOL)getsloginVerificationEnabled:(long long)arg1 withServiceName:(id)arg2;
+ (BOOL)addloginVerificationEnabled:(BOOL)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (BOOL)delsKeySeedForUser:(long long)arg1 withServiceName:(id)arg2;
+ (BOOL)setsKeySeed:(id)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (id)getsKeySeed:(long long)arg1 withServiceName:(id)arg2;
+ (BOOL)addsKeySeed:(id)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (BOOL)delsKeyCountForUser:(long long)arg1 withServiceName:(id)arg2;
+ (BOOL)setsKeyCount:(int)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (int)getsKeyCountForUser:(long long)arg1 withServiceName:(id)arg2;
+ (BOOL)addsKeyCount:(int)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (BOOL)_updateKeychainValue:(id)arg1 forIdentifier:(id)arg2 forUser:(long long)arg3 withServiceName:(id)arg4;
+ (BOOL)_addKeychainValue:(id)arg1 forIdentifier:(id)arg2 forUser:(long long)arg3 withServiceName:(id)arg4;
+ (id)_getKeychainValue:(id)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (BOOL)_deleteKeychainValue:(id)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (id)_newSearchDictionary:(id)arg1 forUser:(long long)arg2 withServiceName:(id)arg3;
+ (id)hashStringWithSeed:(id)arg1 count:(int)arg2 length:(int)arg3;
+ (id)generateSeed;

@end

