//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNTwitterNumberAbbreviation.h"

@class NSNumberFormatter;

@interface TFNTwitterEastAsianNumberAbbreviation : NSObject <TFNTwitterNumberAbbreviation>
{
    int _maximumLength;
    NSNumberFormatter *_formatter;
}

@property(retain, nonatomic) NSNumberFormatter *formatter; // @synthesize formatter=_formatter;
@property(nonatomic) int maximumLength; // @synthesize maximumLength=_maximumLength;
- (void).cxx_destruct;
- (id)shortUnitForHundredsOfMillions;
- (id)shortUnitForTensOfThousands;
- (id)_unitForOrder:(unsigned int)arg1;
- (id)abbreviatedStringForNumber:(id)arg1;
- (id)initWithMaximumLength:(int)arg1;

@end

