//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNTwitterPlistSerialization.h"
#import "TFNTwitterScribableItem.h"
#import "TFNTwitterTimelinePlistSerialization.h"

@class NSArray, NSDictionary, NSString, TFNTwitterUser;

@interface TFNTwitterUserRecommendation : NSObject <TFNTwitterScribableItem, TFNTwitterPlistSerialization, TFNTwitterTimelinePlistSerialization>
{
    BOOL _clusterFollowRecommendation;
    NSString *_nonComputedSocialText;
    TFNTwitterUser *_user;
    NSDictionary *_userPlistDictionary;
    NSString *_token;
    NSArray *_connections;
    NSArray *_connectionsPlistDictionaries;
}

+ (id)userFromUserOrRecommendation:(id)arg1;
+ (void)getUserAndRecommendationFromRep:(id)arg1 userRecommendation:(id *)arg2 user:(id *)arg3;
+ (id)recommendationsWithJSONArray:(id)arg1;
+ (id)recommendationsWithJSONData:(id)arg1 error:(id *)arg2;
@property(nonatomic, getter=isClusterFollowRecommendation) BOOL clusterFollowRecommendation; // @synthesize clusterFollowRecommendation=_clusterFollowRecommendation;
@property(retain, nonatomic) NSArray *connectionsPlistDictionaries; // @synthesize connectionsPlistDictionaries=_connectionsPlistDictionaries;
@property(retain, nonatomic) NSArray *connections; // @synthesize connections=_connections;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) NSDictionary *userPlistDictionary; // @synthesize userPlistDictionary=_userPlistDictionary;
@property(retain, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
@property(copy, nonatomic) NSString *socialText; // @synthesize socialText=_nonComputedSocialText;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *scribeItem;
@property(readonly, nonatomic) NSString *scribeItemImpressionID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_plistDictionaryValueForTimeline:(BOOL)arg1;
- (id)_initWithTimelinePlistDictionary:(id)arg1 forTimeline:(BOOL)arg2;
- (BOOL)populateModelObjectsInTimelinePlistDictionaryWithStatuses:(id)arg1 users:(id)arg2;
- (id)allUserIDsInTimelinePlistDictionary;
- (id)timelinePlistDictionaryValue;
- (id)initWithTimelinePlistDictionary:(id)arg1;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)tfn_debugStrings;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)initWithJSONDictionary:(id)arg1;

@end

