//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UISearchDisplayDelegate.h"

@class NSArray, UISearchBar, UISearchDisplayController;

@interface TFNTwitterFeatureSwitchesDebugUIViewController : UITableViewController <UISearchDisplayDelegate>
{
    UISearchBar *_searchBar;
    UISearchDisplayController *_searchController;
    NSArray *_items;
    NSArray *_filteredItems;
}

- (void).cxx_destruct;
- (void)_reloadData;
- (void)_scribeLoggerChanged:(id)arg1;
- (void)_close:(id)arg1;
- (void)presentFromViewController:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)dealloc;

@end

