//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "TFNTwitterPlistSerialization.h"

@class CLLocation, NSDate, NSString;

@interface TFNTwitterTrendLocation : NSObject <NSCoding, TFNTwitterPlistSerialization>
{
    NSString *_parentID;
    NSString *_name;
    NSString *_country;
    NSString *_countryCode;
    NSString *_woeid;
    unsigned int _type;
    CLLocation *_fromLocation;
    NSDate *_date;
}

+ (id)trendLocationsWithJSONData:(id)arg1 error:(id *)arg2;
+ (void)_findTrendLocationsFrom:(id)arg1;
+ (void)_flushLocationQueue;
+ (void)_detectTrendLocationWithScribe:(id)arg1;
+ (void)performWithCurrentLocation:(CDUnknownBlockType)arg1 scribe:(id)arg2;
+ (id)globalLocation;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) CLLocation *fromLocation; // @synthesize fromLocation=_fromLocation;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *woeid; // @synthesize woeid=_woeid;
@property(copy, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(copy, nonatomic) NSString *country; // @synthesize country=_country;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *parentID; // @synthesize parentID=_parentID;
- (void).cxx_destruct;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)displayNameWithCountryName:(BOOL)arg1;
- (id)displayNameWithCountryCode:(BOOL)arg1;
- (BOOL)isFresh;
- (BOOL)isGlobal;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

