//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSDate, NSString;

@interface TFNTwitterDiscovery : NSObject <NSCoding>
{
    NSArray *_stories;
    NSDate *_date;
    NSString *_scrollCursor;
    NSString *_refreshCursor;
}

+ (id)discoveryWithJSONData:(id)arg1 loadingAccountUserID:(long long)arg2 error:(id *)arg3;
@property(copy, nonatomic) NSString *refreshCursor; // @synthesize refreshCursor=_refreshCursor;
@property(copy, nonatomic) NSString *scrollCursor; // @synthesize scrollCursor=_scrollCursor;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSArray *stories; // @synthesize stories=_stories;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

