//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterUIThreadWatchdog.h"

@interface TFNTwitterUIThreadHangDetector : TFNTwitterUIThreadWatchdog
{
}

- (void)checkHeartBeatResponse:(BOOL)arg1;
- (void)heartBeat;
- (void)stop;
- (void)start:(int)arg1 thresholds:(CDStruct_b2fbf00d)arg2;
- (id)init;

@end

