//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TFNTwitterNearbyItem : NSObject
{
    id _twitterObject;
    unsigned int _clusterWeightMemory;
    CDStruct_2c43369c _coordinate;
}

@property(nonatomic) unsigned int clusterWeightMemory; // @synthesize clusterWeightMemory=_clusterWeightMemory;
@property(retain, nonatomic) id twitterObject; // @synthesize twitterObject=_twitterObject;
@property(nonatomic) CDStruct_c3b9c2ee coordinate; // @synthesize coordinate=_coordinate;
- (void).cxx_destruct;
- (int)compare:(id)arg1;
- (id)description;
- (id)initWithTwitterObject:(id)arg1 coordinate:(CDStruct_c3b9c2ee)arg2;

@end

