//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TFNTwitterPOIStreamResultsBlender : NSObject
{
    unsigned int _topPointsOfInterestCount;
}

@property(nonatomic) unsigned int topPointsOfInterestCount; // @synthesize topPointsOfInterestCount=_topPointsOfInterestCount;
- (id)findAutotagCandidate:(id)arg1;
- (id)blendReverseGeocodedResults:(id)arg1 PointsOfInterests:(id)arg2;
- (id)init;

@end

