//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray;

@interface TFNTwitterCustomTimelineSearchResponseGallery : NSObject <NSCoding>
{
    unsigned int _pivotType;
    NSArray *_customTimelineSearchResponses;
}

@property(retain, nonatomic) NSArray *customTimelineSearchResponses; // @synthesize customTimelineSearchResponses=_customTimelineSearchResponses;
@property(nonatomic) unsigned int pivotType; // @synthesize pivotType=_pivotType;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

