//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString;

@interface TFNTwitterPromotionLogItem : NSObject <NSCoding>
{
    BOOL _isEarned;
    NSString *_impressionID;
    int _event;
    int _tries;
    int _logType;
    NSDictionary *_extraParameters;
}

@property(readonly, nonatomic) NSDictionary *extraParameters; // @synthesize extraParameters=_extraParameters;
@property(readonly, nonatomic) int logType; // @synthesize logType=_logType;
@property(nonatomic) int tries; // @synthesize tries=_tries;
@property(readonly, nonatomic) BOOL isEarned; // @synthesize isEarned=_isEarned;
@property(readonly, nonatomic) int event; // @synthesize event=_event;
@property(readonly, nonatomic) NSString *impressionID; // @synthesize impressionID=_impressionID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithImpressionID:(id)arg1 event:(int)arg2 logType:(int)arg3 isEarned:(BOOL)arg4 extraParameters:(id)arg5;
- (id)initWithImpressionID:(id)arg1 event:(int)arg2 logType:(int)arg3 isEarned:(BOOL)arg4 extraParameters:(id)arg5 tries:(int)arg6;

@end

