//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, TFNTwitterAccount, TFNTwitterCustomTimelineStream, TFNTwitterUser;

@interface TFNTwitterCustomTimeline : NSObject
{
    BOOL _following;
    BOOL _isPublic;
    TFNTwitterAccount *_account;
    NSString *_timelineID;
    NSString *_name;
    NSString *_timelineDescription;
    NSURL *_timelineURL;
    NSURL *_associatedURL;
    TFNTwitterUser *_user;
    TFNTwitterCustomTimelineStream *_stream;
}

+ (id)timelinesWithJSONArray:(id)arg1;
+ (id)timelineWithJSONDictionary:(id)arg1;
+ (id)timelineWithJSONData:(id)arg1 error:(id *)arg2;
+ (id)timelinesWithJSONDictionary:(id)arg1;
+ (id)timelinesWithJSONData:(id)arg1 error:(id *)arg2;
@property(retain, nonatomic) TFNTwitterCustomTimelineStream *stream; // @synthesize stream=_stream;
@property(retain, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
@property(nonatomic) BOOL isPublic; // @synthesize isPublic=_isPublic;
@property(nonatomic, getter=isFollowing) BOOL following; // @synthesize following=_following;
@property(retain, nonatomic) NSURL *associatedURL; // @synthesize associatedURL=_associatedURL;
@property(retain, nonatomic) NSURL *timelineURL; // @synthesize timelineURL=_timelineURL;
@property(copy, nonatomic) NSString *timelineDescription; // @synthesize timelineDescription=_timelineDescription;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *timelineID; // @synthesize timelineID=_timelineID;
@property(nonatomic) __weak TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)removeStatus:(id)arg1;
- (void)_refreshStreamFromNotification:(id)arg1;
- (void)_timelineDidUpdate:(id)arg1;
- (void)refreshStream;
- (void)refresh;
- (void)assimilateTimeline:(id)arg1;
- (void)_postUpdateNotification;
- (void)dealloc;
- (id)initWithJSONDictionary:(id)arg1;
- (id)init;
- (BOOL)isTweetBookmarksTimeline;

@end

