//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class TFNDatabaseReadWriteTransaction;

@interface TFNTwitterAccountModelTransaction : NSObject
{
    TFNDatabaseReadWriteTransaction *_transaction;
}

@property(readonly, nonatomic) TFNDatabaseReadWriteTransaction *transaction; // @synthesize transaction=_transaction;
- (void).cxx_destruct;
- (void)_handleDatabaseError:(id)arg1;
- (BOOL)resetNewDirectMessagesFeatureSchema;
- (void)clearDirectMessagesFromProduction;
- (void)moveDirectMessageEntriesFromShadowTableToProduction;
- (void)moveDirectMessageThreadsFromShadowTableToProduction;
- (void)moveMessagesFromShadowTableToProduction;
- (void)moveListsFromShadowTableToProduction;
- (void)moveUsersFromShadowTableToProduction;
- (void)moveStatusesFromShadowTableToProduction;
- (void)writeTextHeightCache:(id)arg1;
- (BOOL)deleteMyRetweetAndReduceRetweetCountForStatusID:(long long)arg1;
- (BOOL)writeMyRetweetID:(long long)arg1 forStatusID:(long long)arg2 increaseRetweetCount:(BOOL)arg3;
- (BOOL)updateMessageReadState:(unsigned int)arg1 messageID:(long long)arg2;
- (BOOL)deleteMessageWithMessageID:(long long)arg1;
- (BOOL)deleteStatusesFromUser:(id)arg1;
- (BOOL)deleteStatusWithStatusID:(long long)arg1;
- (BOOL)updateEntities:(id)arg1 statusID:(long long)arg2;
- (BOOL)updateFavorited:(BOOL)arg1 statusID:(long long)arg2;
- (BOOL)updateConversationLengthForStatusID:(long long)arg1 increaseCount:(BOOL)arg2;
- (id)initWithTransaction:(id)arg1;

@end

