//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterStream.h"

#import "TFNTwitterGenericTimelineStream.h"

@class NSArray, NSMutableDictionary, NSString, TFNTimer, TFNTwitterSearchActivity, TFNTwitterSearchQuery;

@interface TFNTwitterSearchStream : TFNTwitterStream <TFNTwitterGenericTimelineStream>
{
    NSString *_cursor;
    BOOL _isAtEnd;
    BOOL _firstLoad;
    double _pollingInterval;
    double _tempPollingInterval;
    unsigned int _adaptiveRefreshInterval;
    BOOL _needsSerialization;
    BOOL _isPendingRefresh;
    BOOL _isLoadingTop;
    BOOL _isLoadingBottom;
    TFNTwitterSearchQuery *_searchQuery;
    id _pinnedStreamObject;
    TFNTwitterSearchActivity *_activity;
    NSArray *_streamObjects;
    NSMutableDictionary *_statusesByUnifiedID;
    NSMutableDictionary *_clustersByID;
    TFNTimer *_pollingTimer;
}

@property(retain, nonatomic) TFNTimer *pollingTimer; // @synthesize pollingTimer=_pollingTimer;
@property(retain, nonatomic) NSMutableDictionary *clustersByID; // @synthesize clustersByID=_clustersByID;
@property(retain, nonatomic) NSMutableDictionary *statusesByUnifiedID; // @synthesize statusesByUnifiedID=_statusesByUnifiedID;
@property(nonatomic) BOOL isLoadingBottom; // @synthesize isLoadingBottom=_isLoadingBottom;
@property(nonatomic) BOOL isLoadingTop; // @synthesize isLoadingTop=_isLoadingTop;
@property(retain, nonatomic) NSArray *streamObjects; // @synthesize streamObjects=_streamObjects;
@property(retain, nonatomic) TFNTwitterSearchActivity *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) id pinnedStreamObject; // @synthesize pinnedStreamObject=_pinnedStreamObject;
@property(retain, nonatomic) TFNTwitterSearchQuery *searchQuery; // @synthesize searchQuery=_searchQuery;
@property(nonatomic) BOOL isPendingRefresh; // @synthesize isPendingRefresh=_isPendingRefresh;
@property(nonatomic) BOOL needsSerialization; // @synthesize needsSerialization=_needsSerialization;
- (void).cxx_destruct;
- (id)mainTextForError:(id)arg1;
- (id)emptyStreamMessage;
- (BOOL)canRetryForError:(id)arg1;
@property(readonly, nonatomic) BOOL hasClusterResults;
- (BOOL)canFillInGaps;
- (BOOL)isAtEnd;
- (void)loadGap;
- (id)displayName;
- (BOOL)loadBottom;
- (BOOL)loadTopFromPolling:(BOOL)arg1;
- (void)stopPolling;
- (void)startPolling;
- (void)_postStreamUpdateNotification:(int)arg1 count:(unsigned int)arg2 error:(id)arg3;
- (void)_pollingTimerDidFire:(id)arg1;
- (void)_backoffPollingInterval;
- (void)_startPolling;
- (void)_resetPollingTimer;
- (void)setPollingInterval:(double)arg1;
- (double)pollingInterval;
- (void)_receiveRelationships:(id)arg1 forUsers:(id)arg2;
- (id)_dummyLoadingStatus;
- (void)_updateStreamObjectsWithObjects:(id)arg1 top:(BOOL)arg2;
- (void)_handleLoadingError:(id)arg1 top:(BOOL)arg2;
- (unsigned int)_handleJSONResponse:(id)arg1 top:(BOOL)arg2;
- (void)_processStatusModule:(id)arg1 isNews:(BOOL)arg2 processedObjects:(id)arg3;
- (BOOL)_processStatusGalleryModule:(id)arg1 isMedia:(BOOL)arg2 allowClustering:(BOOL)arg3 allowClusterMerging:(BOOL)arg4 processedObjects:(id)arg5;
- (void)_processTimelineGalleryDictionary:(id)arg1 processedObjects:(id)arg2;
- (void)_processTimelineModuleDictionary:(id)arg1 processedObjects:(id)arg2;
- (void)_processSuggestionsModuleDictionary:(id)arg1 processedObjects:(id)arg2;
- (BOOL)_processUserGalleryDictionary:(id)arg1 allowClustering:(BOOL)arg2 allowClusterMerging:(BOOL)arg3 processedObjects:(id)arg4 processedUsers:(id)arg5;
- (void)_processUserModuleDictionary:(id)arg1 processedObjects:(id)arg2 processedUsers:(id)arg3;
- (void)_processEventModuleUpdate:(id)arg1;
- (id)_eventForJSONDictionary:(id)arg1;
- (void)_processEventModule:(id)arg1 processedObjects:(id)arg2;
- (void)loadNewerFromPolling:(BOOL)arg1;
- (id)itemsToBeSerialized;
- (id)serializationDictionaryValue;
- (void)_didDeleteStatus:(id)arg1;
- (void)dealloc;
- (id)init;

@end

