//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"
#import "TFNActiveTextRange.h"
#import "TFNTwitterPlistSerialization.h"

@class NSString;

@interface TFNTwitterActiveTextRange : NSObject <NSCoding, NSCopying, TFNActiveTextRange, TFNTwitterPlistSerialization>
{
    struct _NSRange _range;
    struct _NSRange _rangeInDisplayText;
}

@property(nonatomic) struct _NSRange rangeInDisplayText; // @synthesize rangeInDisplayText=_rangeInDisplayText;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
@property(readonly, nonatomic) int rangeFlavor;
@property(readonly, nonatomic) struct _NSRange rangeValue;
@property(readonly, nonatomic) NSString *displayString;
- (void)sanitizeForTextLength:(unsigned int)arg1;
- (int)compare:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithJSONDictionary:(id)arg1 strict:(BOOL)arg2;
- (id)initWithJSONDictionary:(id)arg1;
- (BOOL)_initializeRangeWithJSONDictionary:(id)arg1;

@end

