//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNTwitterPlistSerialization.h"
#import "TFNTwitterStatusBanner.h"

@class NSArray;

@interface TFNTwitterRecommendedContent : NSObject <TFNTwitterStatusBanner, TFNTwitterPlistSerialization>
{
    NSArray *_users;
    unsigned int _displayStyle;
}

+ (unsigned int)_displayStyleForString:(id)arg1;
- (void).cxx_destruct;
- (id)bannerText;
- (id)badgeName;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (unsigned int)displayStyle;
- (id)inlineAccountText;
- (id)initWithUsers:(id)arg1 displayStyle:(unsigned int)arg2;
- (id)initWithJSONDictionary:(id)arg1 users:(id)arg2;
- (id)init;

@end

