//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterStory.h"

@class NSMutableArray;

@interface TFNTwitterUserStory : TFNTwitterStory
{
    NSMutableArray *users;
}

@property(retain, nonatomic) NSMutableArray *users; // @synthesize users;
- (void).cxx_destruct;
- (id)uniqueID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

