//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterConcreteStatusesStream.h"

@interface TFNTwitterTimelineStream : TFNTwitterConcreteStatusesStream
{
    int _maxNumberOfTweets;
}

- (void)_unretweetStatusNotification:(id)arg1;
- (id)emptyStreamSubtext;
- (id)emptyStreamMessage;
- (BOOL)shouldPersistScrollPosition;
- (id)autosaveName;
- (void)_performWithApproximateLocation:(CDUnknownBlockType)arg1;
- (void)_loadOlder;
- (void)_loadBeforeGap:(id)arg1;
- (void)_loadNewerFromPolling:(BOOL)arg1;
- (void)addStreamObjects:(id)arg1 needsSortAndDedupe:(BOOL)arg2 notify:(BOOL)arg3;
- (void)addStatus:(id)arg1;
- (BOOL)shouldIndexUsersInAutocomplete;
- (BOOL)canFillInGap;
- (void)dealloc;
- (id)serializationDictionaryValue;
- (id)initWithAccount:(id)arg1 serializationDictionary:(id)arg2;

@end

