//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, NSValue, TFNMediaAssetImage, TFNTwitterAccount, TFNTwitterDirectMessage, TFNTwitterDirectMessageConversation, TFNTwitterGeoLocation, TFNTwitterPlace, TFNTwitterStatus, TFNTwitterTagSet, TFNTwitterUser;

@interface TFNTwitterComposition : NSObject <NSCoding>
{
    unsigned int _backgroundIdentifier;
    NSValue *_initialSelectedRange;
    int _remainingCharacterCount;
    BOOL _isSending;
    BOOL _didBeginSend;
    BOOL _calculateCharCount;
    BOOL _shouldCountLeadingMentions;
    NSMutableArray *_attachments;
    TFNTwitterAccount *_sendingAccount;
    BOOL isDraft;
    BOOL dirty;
    BOOL hadFailedSend;
    BOOL isAlertMode;
    TFNTwitterUser *replyToUser;
    TFNTwitterStatus *replyToStatus;
    TFNTwitterUser *directMessageUser;
    NSString *_initialText;
    NSString *text;
    TFNTwitterGeoLocation *geotag;
    TFNTwitterPlace *place;
    TFNTwitterDirectMessage *_directMessage;
    TFNTwitterDirectMessageConversation *_directMessageConversation;
    NSString *_replyPlaceholderText;
    TFNTwitterTagSet *_tagSet;
    NSDictionary *_extraScribeParameters;
}

+ (id)quoteTweetTextForStatus:(id)arg1 fromAccount:(id)arg2;
+ (id)replyAllPlaceholderForStatus:(id)arg1 fromAccount:(id)arg2;
+ (id)replyAllTextForStatus:(id)arg1 fromAccount:(id)arg2 getReplyToUser:(id *)arg3 initialSelectionRange:(struct _NSRange *)arg4;
@property(readonly, nonatomic) NSArray *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) NSDictionary *extraScribeParameters; // @synthesize extraScribeParameters=_extraScribeParameters;
@property(retain, nonatomic) TFNTwitterTagSet *tagSet; // @synthesize tagSet=_tagSet;
@property(copy, nonatomic) NSString *replyPlaceholderText; // @synthesize replyPlaceholderText=_replyPlaceholderText;
@property(nonatomic) __weak TFNTwitterDirectMessageConversation *directMessageConversation; // @synthesize directMessageConversation=_directMessageConversation;
@property(nonatomic) __weak TFNTwitterDirectMessage *directMessage; // @synthesize directMessage=_directMessage;
@property(nonatomic) BOOL isAlertMode; // @synthesize isAlertMode;
@property(nonatomic) BOOL hadFailedSend; // @synthesize hadFailedSend;
@property(nonatomic) BOOL dirty; // @synthesize dirty;
@property(retain, nonatomic) TFNTwitterPlace *place; // @synthesize place;
@property(retain, nonatomic) TFNTwitterGeoLocation *geotag; // @synthesize geotag;
@property(nonatomic) BOOL isDraft; // @synthesize isDraft;
@property(copy, nonatomic) NSString *text; // @synthesize text;
@property(readonly, copy, nonatomic) NSString *initialText; // @synthesize initialText=_initialText;
@property(retain, nonatomic) TFNTwitterUser *directMessageUser; // @synthesize directMessageUser;
@property(retain, nonatomic) TFNTwitterStatus *replyToStatus; // @synthesize replyToStatus;
@property(retain, nonatomic) TFNTwitterUser *replyToUser; // @synthesize replyToUser;
- (void).cxx_destruct;
- (BOOL)hasImageAttachments;
- (void)addCoordinate:(CDStruct_c3b9c2ee)arg1;
- (void)addPlaceId:(id)arg1;
- (BOOL)hasAttachments;
@property(readonly, nonatomic) TFNMediaAssetImage *primaryImageAttachment;
- (BOOL)hasInlineAttachment;
- (void)toggleAlertMode;
- (void)scribeSendWithScribe:(id)arg1;
@property(nonatomic) struct _NSRange initialSelectedRange;
- (id)fileURL;
- (id)displayName;
- (void)assetUploadCanceled:(id)arg1;
- (void)assetUploadFailed:(id)arg1;
- (void)assetUploadSuccess:(id)arg1;
@property(readonly, nonatomic) float sendProgress;
- (void)sendFromAccount:(id)arg1;
- (BOOL)hasInlineAttachments;
- (BOOL)hasPendingAttachments;
- (void)errorSending;
- (void)didSendDM:(id)arg1;
- (void)didSend:(id)arg1;
- (void)_sendFromAccount:(id)arg1;
- (id)textWithAttachment;
- (void)willDiscard;
- (BOOL)matchesSearchString:(id)arg1;
- (id)appropriateImage;
- (id)appropriateDraftTitle;
- (id)appropriateTitle;
- (BOOL)isDocumentEdited;
- (BOOL)containsMoreThanMentions;
- (BOOL)isWorthSending;
- (BOOL)isEqualToComposition:(id)arg1;
- (BOOL)isEmpty;
- (BOOL)isWorthSaving;
- (int)_tweetLengthCountingLeadingMentions:(id)arg1 httpURLLength:(int)arg2 httpsURLLength:(int)arg3 possibleHandles:(id)arg4;
- (int)remainingCharacters:(BOOL)arg1;
- (int)alertHashtagLength;
- (int)_attachmentsLength;
- (int)_secureLinkLength;
- (int)_plainLinkLength;
- (void)switchToDirectMessage;
- (void)switchToPublicReply;
- (void)_removeUsernamePrefix;
- (BOOL)_removePrefix:(id)arg1;
- (void)_addUsernamePrefixIfNeeded;
- (BOOL)isPublicReply;
- (BOOL)isDirectMessage;
- (BOOL)isGeoTaggable;
@property(readonly, nonatomic) int compositionType;
- (void)_endSendStatus:(id)arg1 directMessage:(id)arg2;
- (void)_beginSend;
@property(readonly, nonatomic) BOOL isSending;
- (void)_cleanupAsset:(id)arg1;
- (void)_initAsset:(id)arg1;
- (void)removeAllAttachments;
- (void)removeAttachment:(id)arg1;
- (void)addAttachment:(id)arg1 atIndex:(unsigned int)arg2;
- (void)addAttachment:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithInitialText:(id)arg1;
- (id)init;

@end

