//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "TFNTwitterPlistSerialization.h"

@class NSDate, NSString, TFNTwitterMediaImageInformation;

@interface TFNTwitterMediaInformation : NSObject <NSCoding, TFNTwitterPlistSerialization>
{
    NSString *_mediaID;
    int _mediaType;
    TFNTwitterMediaImageInformation *_imageInformation;
    NSDate *_expiryDate;
    long long _size;
}

+ (id)mediaInformationWithJSONData:(id)arg1 error:(id *)arg2;
@property(retain, nonatomic) NSDate *expiryDate; // @synthesize expiryDate=_expiryDate;
@property(retain, nonatomic) TFNTwitterMediaImageInformation *imageInformation; // @synthesize imageInformation=_imageInformation;
@property(nonatomic) long long size; // @synthesize size=_size;
@property(nonatomic) int mediaType; // @synthesize mediaType=_mediaType;
@property(copy, nonatomic) NSString *mediaID; // @synthesize mediaID=_mediaID;
- (void).cxx_destruct;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

