//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImageView, UILabel;

@protocol TFNTextDataViewCell <NSObject>
@property(nonatomic) float detailTextPadding;
@property(nonatomic) int verticalAlignment;
@property(nonatomic) BOOL multipleDetailTextLines;
@property(readonly, nonatomic) UILabel *detailTextLabel;
@property(nonatomic) BOOL multipleTextLines;
@property(readonly, nonatomic) UILabel *textLabel;
@property(readonly, nonatomic) UIImageView *imageView;
@end

