//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterList.h"

#import "TFNTwitterDummyObject.h"

@class NSString;

@interface TFNTwitterDummyList : TFNTwitterList <TFNTwitterDummyObject>
{
    BOOL _loading;
    NSString *_messageText;
    NSString *_messageSubtext;
    int _dummyObjectType;
    CDUnknownBlockType _actionBlock;
}

+ (id)dummyListOfType:(int)arg1;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(nonatomic) int dummyObjectType; // @synthesize dummyObjectType=_dummyObjectType;
@property(nonatomic, getter=isLoading) BOOL loading; // @synthesize loading=_loading;
@property(copy, nonatomic) NSString *messageSubtext; // @synthesize messageSubtext=_messageSubtext;
@property(copy, nonatomic) NSString *messageText; // @synthesize messageText=_messageText;
- (void).cxx_destruct;

@end

