//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface TFNTwitterFavoriteFollowButton : UIButton
{
}

+ (struct CGSize)sizeForControl;
+ (id)_iconImageNameForStyle:(int)arg1 active:(BOOL)arg2;
+ (id)_backgroundImageForStyle:(int)arg1 active:(BOOL)arg2 pressed:(BOOL)arg3;
+ (id)buttonWithStyle:(int)arg1;

@end

