//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "TFNTwitterPlistSerialization.h"

@class NSArray, NSString;

@interface TFNTwitterCluster : NSObject <NSCoding, TFNTwitterPlistSerialization>
{
    NSString *_clusterID;
    NSString *_title;
    NSString *_subtitle;
    NSArray *_galleries;
}

+ (id)statusWithClusterFromModuleDictionary:(id)arg1;
+ (id)clusterFromGalleryDictionary:(id)arg1;
+ (id)metadataKeyForClusterClass;
+ (id)clusterWithJSONDictionary:(id)arg1;
@property(retain, nonatomic) NSArray *galleries; // @synthesize galleries=_galleries;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *clusterID; // @synthesize clusterID=_clusterID;
- (void).cxx_destruct;
- (id)description;
- (id)duplicateClusterExcludingGalleries;
@property(readonly, nonatomic) BOOL isVirtual;
- (BOOL)deleteStatus:(id)arg1 excludeMediaGalleries:(BOOL)arg2;
- (void)addUserGallery:(id)arg1;
- (void)addStatusGallery:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)init;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

