//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterTypeaheadObject.h"

@class NSString;

@interface TFNTwitterTypeaheadHashtag : TFNTwitterTypeaheadObject
{
    NSString *_hashtag;
}

@property(copy, nonatomic) NSString *hashtag; // @synthesize hashtag=_hashtag;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)initWithJSONDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

