//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"
#import "TFNTwitterPlistSerialization.h"

@class NSMutableArray;

@interface TFNTwitterEntityMediaFeatureSet : NSObject <NSCoding, NSCopying, TFNTwitterPlistSerialization>
{
    NSMutableArray *_faces;
}

+ (float)cropPositionFromLeft:(float)arg1 width:(float)arg2 cropWidth:(float)arg3;
+ (float)cropPositionFromTop:(float)arg1 height:(float)arg2 cropHeight:(float)arg3;
+ (float)_cropPosition:(float)arg1 length:(float)arg2 cropLength:(float)arg3 inflectionPoint:(float)arg4;
@property(retain, nonatomic) NSMutableArray *faces; // @synthesize faces=_faces;
- (void).cxx_destruct;
- (struct CGRect)contentsRectForImageOfSize:(struct CGSize)arg1 displayedAtSize:(struct CGSize)arg2;
- (id)description;
- (_Bool)isEqualToFeatureSet:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;

@end

