//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNTwitterStatusSocialContext.h"

@class NSArray, NSString;

@interface TFNTwitterStatusAuthorAndActorSocialContext : NSObject <TFNTwitterStatusSocialContext>
{
    BOOL _isFollowingAuthor;
    BOOL _isFollowedByAuthor;
    NSString *_genericSocialContext;
    NSArray *_relatedUserGroups;
}

+ (int)_socialContextTypeForString:(id)arg1;
@property(retain, nonatomic) NSArray *relatedUserGroups; // @synthesize relatedUserGroups=_relatedUserGroups;
@property(copy, nonatomic) NSString *genericSocialContext; // @synthesize genericSocialContext=_genericSocialContext;
@property(nonatomic) BOOL isFollowedByAuthor; // @synthesize isFollowedByAuthor=_isFollowedByAuthor;
@property(nonatomic) BOOL isFollowingAuthor; // @synthesize isFollowingAuthor=_isFollowingAuthor;
- (void).cxx_destruct;
- (id)plistDictionaryValueForTimeline:(BOOL)arg1;
- (id)timelinePlistDictionaryValue;
- (id)plistDictionaryValue;
- (id)initWithTimelinePlistDictionary:(id)arg1;
- (id)initWithPlistDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)allUsers;
- (id)primaryUser;
- (BOOL)updateActivityCountsWithFavoriteCount:(unsigned int)arg1 retweetCount:(unsigned int)arg2;
- (BOOL)socialTextIsActivityCount;
- (id)activityName;
- (id)socialText;
- (id)_primaryRelatedUserFullName;
- (int)_primarySocialContextType;
- (id)initWithJSONDictionary:(id)arg1;

@end

