//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, TFNTwitterUser;

@interface TFNTwitterConversationStructure : NSObject
{
    BOOL _hasHeaderInfo;
    NSArray *_ancestors;
    NSArray *_ancestorIDs;
    int _repliesCount;
    int _participantsCount;
    NSArray *_participants;
    NSArray *_participantIDs;
    NSArray *_entityIDArray;
    NSNumber *_targetStatusID;
    TFNTwitterUser *_rootUser;
    NSNumber *_rootUserID;
}

@property(retain, nonatomic) NSNumber *rootUserID; // @synthesize rootUserID=_rootUserID;
@property(retain, nonatomic) TFNTwitterUser *rootUser; // @synthesize rootUser=_rootUser;
@property(retain, nonatomic) NSNumber *targetStatusID; // @synthesize targetStatusID=_targetStatusID;
@property(retain, nonatomic) NSArray *entityIDArray; // @synthesize entityIDArray=_entityIDArray;
@property(retain, nonatomic) NSArray *participantIDs; // @synthesize participantIDs=_participantIDs;
@property(retain, nonatomic) NSArray *participants; // @synthesize participants=_participants;
@property(nonatomic) int participantsCount; // @synthesize participantsCount=_participantsCount;
@property(nonatomic) int repliesCount; // @synthesize repliesCount=_repliesCount;
@property(retain, nonatomic) NSArray *ancestorIDs; // @synthesize ancestorIDs=_ancestorIDs;
@property(retain, nonatomic) NSArray *ancestors; // @synthesize ancestors=_ancestors;
@property(nonatomic) BOOL hasHeaderInfo; // @synthesize hasHeaderInfo=_hasHeaderInfo;
- (void).cxx_destruct;
- (id)plistDictionaryValue;
@property(readonly, nonatomic) int unseenRepliesCount;
- (id)initWithPlistDictionary:(id)arg1;

@end

