//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TFNTwitterDateComparable.h"

@class NSDate;

@interface TFNTwitterStreamControlObject : NSObject <TFNTwitterDateComparable>
{
    BOOL _triggered;
    NSDate *_comparableDate;
    id <TFNTwitterStreamControlObjectDelegate> _delegate;
}

@property(nonatomic) __weak id <TFNTwitterStreamControlObjectDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL triggered; // @synthesize triggered=_triggered;
@property(readonly, nonatomic) NSDate *comparableDate; // @synthesize comparableDate=_comparableDate;
- (void).cxx_destruct;
- (int)compare:(id)arg1;
- (void)trigger;
- (id)initWithComparableDate:(id)arg1;

@end

