//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectContext, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSURL;

@interface TFNTwitterScribeService : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSURL *_storeURL;
    int _requestID;
    NSManagedObjectContext *_managedObjectContext;
    unsigned int _flags;
    NSMutableDictionary *_accountScribedItemImpressions;
    NSMutableDictionary *_accountScribeDisabledPages;
    NSObject<OS_dispatch_queue> *_accountScribeDisabledPagesLock;
}

+ (id)appDownloadTrackingValue:(id)arg1 deviceId:(id)arg2;
+ (BOOL)isDebugEnabled;
+ (void)_purgeScribeDirectory;
+ (void)_purgeScribeDirectoryIfNecessary;
+ (id)sharedService;
- (void).cxx_destruct;
- (void)_handleScribeError:(id)arg1;
- (id)_clientName;
- (id)_userIDForAccount:(id)arg1;
- (void)_clearItemImpressionsCache;
- (void)_applicationWillStopRunning;
- (void)_applicationDidCompleteBackgroundFetch:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (void)_applicationDidReceiveMemoryWarning:(id)arg1;
- (void)_didRemoveAccount:(id)arg1;
- (void)_resetScribeEvents;
- (void)_removePersistentStore;
- (void)_performInManagedObjectContext:(CDUnknownBlockType)arg1;
- (void)_setupManagedObjectContext;
- (void)_deleteImpressionsForUserID:(id)arg1 managedObjectContext:(id)arg2;
- (void)_deleteEventsForUserID:(id)arg1 managedObjectContext:(id)arg2;
- (void)deleteAccount:(id)arg1;
- (void)_didFlushEventsWithRequestID:(int)arg1 request:(id)arg2 userID:(id)arg3 managedObjectContext:(id)arg4;
- (id)_flushEventsWithRequestID:(int)arg1 userID:(id)arg2 managedObjectContext:(id)arg3;
- (void)_batchImpressionsForUserID:(id)arg1 managedObjectContext:(id)arg2;
- (void)flushAccount:(id)arg1;
- (void)_enqueueItemImpression:(id)arg1 eventName:(id)arg2 query:(id)arg3 parameters:(id)arg4 timestamp:(id)arg5 userID:(id)arg6 managedObjectContext:(id)arg7;
- (void)_enqueueItemImpression:(id)arg1 page:(id)arg2 section:(id)arg3 component:(id)arg4 element:(id)arg5 parameters:(id)arg6 deduplicate:(BOOL)arg7 userID:(id)arg8;
- (void)logItemImpression:(id)arg1 page:(id)arg2 section:(id)arg3 component:(id)arg4 element:(id)arg5 parameters:(id)arg6 deduplicate:(BOOL)arg7 account:(id)arg8;
- (void)_enqueueCardEvent:(id)arg1 eventName:(id)arg2 query:(id)arg3 timestamp:(id)arg4 userID:(id)arg5 managedObjectContext:(id)arg6;
- (void)_enqueueEvent:(id)arg1 timestamp:(id)arg2 userID:(id)arg3 managedObjectContext:(id)arg4;
- (void)_enqueueEvent:(id)arg1 userID:(id)arg2;
- (id)_eventWithName:(id)arg1 parameters:(id)arg2 clientVersion:(id)arg3 userID:(id)arg4;
- (id)_eventWithName:(id)arg1 parameters:(id)arg2 userID:(id)arg3;
- (void)logCrashWithID:(id)arg1 crashName:(id)arg2 crashDetails:(id)arg3 crashTimestamp:(id)arg4 crashClientVersion:(id)arg5 account:(id)arg6;
- (void)logErrorWithType:(id)arg1 filename:(id)arg2 lineNumber:(int)arg3 functionName:(id)arg4 description:(id)arg5 account:(id)arg6;
- (void)logPerformanceEvent:(id)arg1 startTime:(double)arg2 endTime:(double)arg3 account:(id)arg4;
- (void)_logEvent:(id)arg1 parameters:(id)arg2 userID:(id)arg3;
- (void)logSignedOutEvent:(id)arg1 parameters:(id)arg2;
- (void)logEvent:(id)arg1 parameters:(id)arg2 account:(id)arg3;
- (void)logAction:(id)arg1 page:(id)arg2 section:(id)arg3 component:(id)arg4 element:(id)arg5 parameters:(id)arg6 account:(id)arg7;
- (void)clearScribeDisabledPagesForAccount:(id)arg1;
- (void)addScribeDisabledPage:(id)arg1 account:(id)arg2;
- (void)resume;
- (void)suspend;
- (void)close;
- (void)open;
- (void)dealloc;
- (id)initWithStoreURL:(id)arg1;

@end

