//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TFNTwitterUserStream.h"

@interface TFNTwitterUserTimelineStream : TFNTwitterUserStream
{
    BOOL _forMyOwnUserTimeline;
}

@property(nonatomic) BOOL forMyOwnUserTimeline; // @synthesize forMyOwnUserTimeline=_forMyOwnUserTimeline;
- (void)_unretweetStatusNotification:(id)arg1;
- (void)_loadOlder;
- (void)_loadBeforeGap:(id)arg1;
- (void)_loadNewerFromPolling:(BOOL)arg1;
- (void)_checkIfForMyUserTimeline;
- (void)setUser:(id)arg1;
- (void)setAccount:(id)arg1;
- (void)dealloc;

@end

