//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "T1ComposeAttachmentPreviewDelegate.h"

@class T1ComposeAttachmentPreview, UIButton;

__attribute__((visibility("hidden")))
@interface TIComposeAttachmentsView : UIView <T1ComposeAttachmentPreviewDelegate>
{
    id <TIComposeAttachmentsViewDelegate> _delegate;
    T1ComposeAttachmentPreview *attachmentView;
    UIButton *cameraButton;
    UIButton *libraryButton;
    struct {
        unsigned int hasLoaded:1;
    } _flags;
}

@property(nonatomic) __weak id <TIComposeAttachmentsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)attachmentPreviewDidDeleteAttachment:(id)arg1;
- (void)layoutSubviews;
- (void)reload;
- (void)_updateAddMoreButtonState;
- (void)didDelete:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)photoLibrary:(id)arg1;
- (void)camera:(id)arg1;
- (id)account;
- (id)initWithFrame:(struct CGRect)arg1;

@end

