//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationItem.h"

@class NSArray;

@interface UINavigationItem (TFNNavigationControllerAdditions)
- (void)tfn_setSupplementaryNavigationBarItemViews:(id)arg1 withDividers:(BOOL)arg2;
@property(retain, nonatomic) NSArray *tfn_supplementaryNavigationBarItemViews;
@property(readonly, nonatomic) BOOL tfn_supplementaryNavigationBarDividersEnabled;
- (void)tfn_setSupplementaryNavigationBar:(id)arg1;
- (id)tfn_supplementaryNavigationBar;
@end

