//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (T1ModalPresentation)
- (void)t1_childViewController:(id)arg1 didSetModalPresentationHeightAnimated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)t1_setModalPresentationHeight:(float)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)t1_setModalPresentationHeight:(float)arg1 animated:(BOOL)arg2;
@property(nonatomic) float t1_modalPresentationHeight;
@property(nonatomic) __weak id <T1ModalPresentationDelegate> t1_modalPresentationDelegate;
@end

