//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (TFNTwitterScribe)
- (id)scribeAssociationID;
- (id)scribeElementForIndexPath:(id)arg1;
- (id)scribeElement;
- (id)scribeComponentForIndexPath:(id)arg1;
- (id)scribeComponent;
- (id)scribeSectionForIndexPath:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (id)scribeContextForIndexPath:(id)arg1;
- (id)scribeContext;
- (id)scribeImpressionParametersForIndexPath:(id)arg1;
- (id)scribeImpressionParameters;
- (id)scribe;
- (void)scribeImpressionWithParameters:(id)arg1;
- (id)amplifyScribePage;
@end

